### ISSUE TITLE
Video file streaming

### ISSUE THREAD

**Issue by BYulia** [fluid-player/fluid-player#109]
Please, tell, how display the video duration and rewind the video file for streaming video? And what are the opportunities for video streaming?

**Comment by BYulia** [comment]
should there be an opportunity to rewind while watching advertising?

**Comment by cian-exads** [comment]
Hi @BYulia, the ability to interact with in-stream advertisements is restricted, and so rewinding is not an option during this. Regarding video streaming, this is something that's being actively discussed as a future feature. I will update this ticket once we have more information on when this might be available.

**Comment by golikov** [comment]
The possibility DASH-MPEG and HLS streaming has been added in v2.2.0
The streaming videos duration and rewinding is done from UI perspective the same as for normal videos.
As for the ads - it should not be possible to rewind them by design, we do not intend to be changing that.
