### ISSUE TITLE
timelinePreview looking thumbnails.jpg from always from the url root

### ISSUE THREAD

**Issue by Luppakorva** [fluid-player/fluid-player#113]
Heya,

Encountered this issue today while looking to integrate the player.

If I set vtt path as follows: 

timelinePreview: {
                file: 'mysite.com/videos/thumbs/' + videoid + '/thumbnails.vtt',
                type: 'VTT'
            }

thumbnails.vtt is loaded, but the player is looking the thumbnails.jpg from the site root url "mysite.com/thumbnails.jpg", which naturally is not found as it is in the same directory where the .vtt file is.
Using the CDN and the latest current version of player v2

**Comment by cian-exads** [comment]
Hi @Luppakorva, 

The paths to the **thumbnails.jpg** are specified in the **thumbnails.vtt** file, and are not configured via the Fluid Player params. These are relative to root url, and do not assume the images to be in the same location. You can try altering the **thumbnails.vtt** so that the paths are full.

```
00:00:00.000 --> 00:00:02.000
/path/to/thumbnails.jpg#xywh=0,0,120,68

00:00:02.000 --> 00:00:04.000
/path/to/thumbnails.jpg#xywh=120,0,120,68

00:00:04.000 --> 00:00:06.000
/path/to/thumbnails.jpg#xywh=240,0,120,68
```

I hope the above information helps, please let me know if that resolves the issue.

**Comment by Luppakorva** [comment]
Heya @cian-exads 

And thanks for  the prompt reply. 

The problem with that is, if you're integrating from another player such as jwplayer or videojs, they both use plain thumbnails.jpg without absolute path in the thumbnails.vtt file. 

Also if you happen to have 50k videos (like I do for example) and you're using various cdn's, having to move the videos and file locations based to them, it would be extremely annoying to keep updated having to update every .vtt file involved when file location changes. It really makes the scalability difficult.

So if possible, may I suggest the thumbnails.jpg would be assumed to be in the same folder as .vtt file if no path is mentioned in the .vtt file?

**Comment by cian-exads** [comment]
Absolutely @Luppakorva, the option for either is the ideal solution. When discussing the next release this will be put into consideration. I will keep this issue open and update with information once I have it.

**Comment by Luppakorva** [comment]
@cian-exads many thanks!

**Comment by barthmania** [comment]
I am having the same issue and suggestion. :)

I'm also a JWPlayer user currently switching to Fluid Player.

Thank you in advance.

**Comment by barthmania** [comment]
@Luppakorva Just to tell you that I made a little change in the script for my personal use as I needed the same function as you.

If you want me to post it here, I can share it. :) It only needs to change 2 lines in fluidplayer.js ;)

**Comment by cradonn** [comment]
@barthmania: Why not contribute via a PR? 😄

**Comment by Luppakorva** [comment]
@barthmania please do! That would be much appreciated!

**Comment by Luppakorva** [comment]
@barthmania great, will be waiting :). Big thank you for doing so! much needed for myself.

**Comment by Luppakorva** [comment]
@barthmania thank you! Working perfectly.

**Comment by b202020** [comment]
Just mentioning that Fluid Player already supports a "sprite" configuration where you can set the thumbnail image as well. This will overwrite the one in the thumbnails.vtt if defined.
So alternatively you can configure:
`
...
	timelinePreview: {
		file: "thumbs/thumbnails.vtt",
		type: "VTT",
		sprite: "thumbs/thumbnails.jpg"
	},
...
`

This sprite option is not documented though. I will add it to documentation.
