### ISSUE TITLE
skip_button and fluid_ad_cta same position 

### ISSUE THREAD

**Issue by ERI123** [fluid-player/fluid-player#114]
Hello
Mobile - tablet users can not skip vast ad. The reason is that ad-cta is on top because they have the same bottom position.
.fluid_video_wrapper.mobile .skip_button,.fluid_video_wrapper.mobile .fluid_ad_cta{bottom:75px}

I have fixed it by adding after style file this css code.
<style>
.fluid_video_wrapper.mobile .skip_button{bottom:50px}
.fluid_video_wrapper.mobile .fluid_ad_cta{bottom:100px}
</style>

**Comment by cian-exads** [comment]
Hi @ERI123, this is a known issue and a fix is being put in place. Thank you for the feedback on a fix.

**Comment by golikov** [comment]
The positioning fixes for skip_button and fluid_ad_cta were introduced as part of v2.2.0
