### ISSUE TITLE
Player on Chrome Mobile isn't working

### ISSUE THREAD

**Issue by dani708** [fluid-player/fluid-player#117]
How can i fix that? Is working everywhere but not in the Chrome app for mobile.

**Comment by tapplz** [comment]
Can you describe how it's showing up (if at all), and can you paste a copy of how you implemented the player? Also is this Android Chrome Mobile or iOS Chrome Mobile?

I'm able to get it working on all browsers (albeit with some glitches).

**Comment by dani708** [comment]
I actually throwed the vast link and now it's working even on Chrome Mobile

**Comment by cian-exads** [comment]
Hi @dani708, there should be no reason for the addition of VAST ads would cause the player to break for Chrome Mobile. If you have the code that in use when this happened please paste it here.

**Comment by cian-exads** [comment]
Closing this issue as @dani708 has said it's now working.
