### ISSUE TITLE
Destroy function

### ISSUE THREAD

**Issue by arvai** [fluid-player/fluid-player#119]
Hello, What if my Fluid Player is inside an overlay, and I close this overlay ?
Fluidplayer will be removed from the DOM and I get some JS errors. 
Do we have any solution to remove the FP instance before I'm removing the object from the DOM ?

**Comment by cian-exads** [comment]
Hi @arvai, I think a **destory()** function makes a lot of sense to have, for cases similar to yours. I will add it as a feature request for the developers to discuss for upcoming development. Thank you.

**Comment by Addvilz** [comment]
Fixed with v2.4.11
