### ISSUE TITLE
Guide for adultvideoscript

### ISSUE THREAD

**Issue by gamejump** [fluid-player/fluid-player#12]
Hello

do you have any tutorial to install these player on
adultvideoscript script please let us know

Want to install this on my tube site

**Comment by cian-exads** [comment]
Hi @gamejump, I've been speaking with AdultVideoScript as this is a paid service and we have no access ourselves. The response I received regarding access to code and file structure was as follows: "You get complete unencoded source codes, complete access to everything". My answer will therefore assume you have access to the code and directories.

- Download the required FluidPlayer files
- Extract the files to the desired location on your domain
- Include the necessary scripts as normal defined in the Fluid Player installation guide, ensuring all file paths are correct - https://github.com/fluid-player/fluid-player

When querying integration of players they also mentioned that they will integrate Fluid Player for a cost. Their reply was as follows: "We can integrate JWPlayer if you wish, or other players, for an extra price. We can integrate it fluidplayer, too, but for an extra cost."

I hope you find this information useful, and if there is any further clarification needed please let us know.
