### ISSUE TITLE
Safari preroll and postroll

### ISSUE THREAD

**Issue by ERI123** [fluid-player/fluid-player#120]
Hello
When you have pre-roll and post-roll, non-linear mid-roll and on pause banners is a mess on Safari desktop, iPad, and iPhone.
Sometimes plays the post-roll first
Sometimes need double click the play button to play.
Sometimes the main video does not start at all.
Sometimes the counting seconds never start counting and the vast video is playing.

But if you remove the post-roll everything is working.
Thank you

**Comment by cian-exads** [comment]
Hi @ERI123, what version of Fluid Player are you currently using? Also is this on all versions of Safari, iPad and iPhone? Thanks for any information you can provide to help us identify the cause.

**Comment by ERI123** [comment]
version 2.1.2 
yes  on all versions of Safari 11.1, iPad, and iPhone

**Comment by ERI123** [comment]
http://www.alotporn.com/test.html

**Comment by golikov** [comment]
This issue should be solved in v2.2.0
