### ISSUE TITLE
Enable .svg compression for some speed

### ISSUE THREAD

**Issue by ERI123** [fluid-player/fluid-player#123]
Hello
I am using fluid player CDN and got this from google page speed.

Enable compression
Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.
Enable compression for the following resources to reduce their transfer size by 5.4KiB (67% reduction).
Compressing https://cdn.fluidplayer.com/v2/current/images/fluid_icons.svg could save 5.4KiB (67% reduction).

Minify JavaScript
Compacting JavaScript code can save many bytes of data and speed up downloading, parsing, and execution time.
Minify JavaScript for the following resources to reduce their size by 1KiB (24% reduction).
Minifying https://cdn.fluidplayer.com/v2/current//scripts/webvtt.js could save 1KiB (24% reduction) after compression.

Thank you

**Comment by cian-exads** [comment]
Hi @ERI123, this is useful information, and it makes sense to apply both of these reccomendations
