### ISSUE TITLE
height: 100% not working

### ISSUE THREAD

**Issue by Magi5** [fluid-player/fluid-player#133]
Hi!

I'm trying to implement Fluid Player into a page with 100% width and 100% height.
Example: https://yucloud.co/direct/embed.php?s=b

The problem is that the video player does "not want" to have a 100% height. This generates problems when I want to take the page through an iframe.

Also, only the width is adjusted accordingly. If the above mentioned page is accessed from a mobile device, only the width is displayed properly. The height does not adjust for the entire screen, leaving an empty space.

Can you help me with that? How can I make the player work with 100% width and height parameters?

**Comment by cian-exads** [comment]
Hi @Magi5, I'm guessing from your example that you want the player to be the full height of the users screen? This is issue occurs when trying to set 100% without specifying a parent height, here's a thread that has some solutions - https://stackoverflow.com/questions/1122381/how-to-force-child-div-to-100-of-parents-div-without-specifying-parents-heigh

If the goal is to have a video the full screen size then the easiest solution taken from there is to add:
`html,body { height:100%; }`. Or you could use js to set the video height on the fly: `document.getElementById('video-id').style.height = window.innerHeight + 'px';`. Let me know if one of these solutions help, however I do not believe this is a Fluid Player issue.

**Comment by Magi5** [comment]
Hi!

Thanks for the reply.

Unfortunately, none of the solutions helped me.
https://yucloud.co/direct/embed.php?s=b

I have tried many variants.

```
<style>
html,body { height:100% !important; margin: 0px; };
</style>
```

- no change, nothing happened.

    `<video id='video-id' controls style="width: 100%; height: 100%;">`
  
- no change, nothing happened.

```
<script type="text/javascript">
document.getElementById('video-id').style.height = window.innerHeight + 'px';
</script>
```
-- no change, nothing happened.
```
<script type="text/javascript">
function resize()
            {
                var heights = window.innerHeight;
                document.getElementById("video-id").style.height = heights + "px";
            }
            resize();
            window.onresize = function() {
                resize();
            };
</script>
```

This code apparently solved the problem, but not completely...For better understanding, go to the page https://yucloud.co/direct/embed.php?s=b -> enter in Full-Screen mode, after that exit full-screen mode.
The result will be a perfect display with 100% width and height (I want it by default).

**Comment by cian-exads** [comment]
If you place your resize function after initialising the Fluid Player element it should work, as Fluid Player also forces the size on it when called. Alternatively you can try to include `.fluid_video_wrapper { height: 100%; }` alongside the html and body elements being height 100%.

**Comment by Magi5** [comment]
Now it's perfect!

Thank you so much!

**Comment by cian-exads** [comment]
My pleasure @Magi5, happy to hear it's working!
