### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by gibigate** [fluid-player/fluid-player#144]
1. More events like video stop*/skip/progress/end/enter fullscreen/exit fullscreen/format changed
* ability to add stop button

2. context menu API to add some button(with callbacks) and remove defaults

3. if user changes format, it will be saved in cookies or storage, and the next page video will automatically change to chosen format. Same changes apply to volume, speed, and theatre mode.

4. double click for fullscreen. Example code for realize this function:
```
var clickHandlers = [];
player.on('click', function(e) {
                    clickHandlers.push(setTimeout(function() {
                        player.togglePlayPause();
                    }, 300));
                
            });

            player.on('dblclick', function(e) {
                
                    player.fullscreen();
                
                clickHandlers.forEach(function(handler) {
                    clearTimeout(handler);
                });
                clickHandlers = [];
            });
```
5. Ability to add/show custom html when video finished (for show related videos)

**Comment by gibigate** [comment]
6. Hide private functions

7. Ability to add custom buttons in toolbar, for example:
```
{ 
    buttons: {
        'custom' : {
            position: left|right,
            class: 'myCustomButton',
            text:'click to view full video', 
            icon: false or '<i class="fa fa-link"></i>', 
            url: 'some url' or false, 
            callback: function(){ console.log('Button Clicked'); }, 
        }
    }
}
```
8. Bug 
<img width="178" alt="screenshot 2018-05-03 19 14 53" src="https://user-images.githubusercontent.com/1709390/39578576-4f371534-4f06-11e8-9d8a-f808b4914e80.png">

**Comment by cradonn** [comment]
Thanks for your suggestions @gibigate, they will be reviewed and added to our our backlog if deemed useful.

As FluidPlayer is open source, I would encourage you to get involved and contribute to the project, we are happy to review community contributions.

Can you provide some more context for the bug you mention (point 8) above please?
Additional screenshots and player configuration would also be useful.

**Comment by gibigate** [comment]
@cradonn  point 8: 
time pop-up icon goes over the border of video player as you set a time scale close to the end of video while using a mouse.

**Comment by vmartian** [comment]
Does it support vpaid tag also

**Comment by gibigate** [comment]
BUG: iphone safari, ipad safari (maybe all touch devices)
controlbar autohide doesn't work after video seeked, and working fine again after pausePlay toggle

**Comment by cian-exads** [comment]
@gibigate, version 2.2.1 just went live, which contains a fix for the iOS source switch time issue. We'll keep this ticket open for now as we're still in discussions regarding your initial recommendations.

**Comment by atmovies** [comment]
can you please add seek button 10sec forword 10sec back and i want to disable right click menu, how i can do please help

**Comment by gibigate** [comment]
Bug when exiting full screen mode on ios, icon does not change

**Comment by Addvilz** [comment]
This ticket is effectively 8 or more different issues/feature requests. If any of them are still relevant, please open new tickets for them, a ticket per each individual issue please. Issues that contain more than one actual issue are unmanageable.
