### ISSUE TITLE
VAST Wrappers support

### ISSUE THREAD

**Issue by sanex3339** [fluid-player/fluid-player#15]
Looks like `fluid-player` currently not support VAST wrappers through `<VASTAdTagURI>`

Example: http://am15.net/video.php?s=5459&show=preroll&type=direct

**Comment by cian-exads** [comment]
Hi @sanex3339, thank you for the feedback. You are correct that we currently don't support this feature, however we will have it in mind when planning future improvements.

**Comment by cian-exads** [comment]
Hi @sanex3339, in the latest release (v2.2.2) we have added in support for VAST wrappers. Closing this issue.
