### ISSUE TITLE
Not support Vast 3.0

### ISSUE THREAD

**Issue by JuliaTeasernet** [fluid-player/fluid-player#150]
Continuation #124

After fix #124  Vast can't playing: http://site.teasernet.com/fluidnew2.html
(version 2.2.0)

Example Vast Teasernet http://site.teasernet.com/lila/vast3.xml
The player does not launch it
Example http://site.teasernet.com/fluidnew2.html

Our partners can not start working with fluid and teasernet vast

**Comment by cian-exads** [comment]
Hi @JuliaTeasernet, we're going to look into this and hope to have a fix soon.

**Comment by JuliaTeasernet** [comment]
kristijanexads wrote:
... it seems that there is a similar problem as before, trimming whitespaces between CDATA solved previous issue, but we will have to apply the same on XML nodes around CDATA...

**Comment by JuliaTeasernet** [comment]
@cian-exads we try make without trimming whitespaces

vast http://site.teasernet.com/vast3.xml (without whitespaces )
player http://site.teasernet.com/fluidnew3.html

Does not work

**Comment by cian-exads** [comment]
Hi @JuliaTeasernet, we have just released version 2.2.1 of Fluid Player, which contains the fix for your issue. I've checked http://site.teasernet.com/fluidnew3.html and http://site.teasernet.com/fluidnew2.html and got VAST ads on both. Closing this issue.
