### ISSUE TITLE
[Error] (202): Failed to play video

### ISSUE THREAD

**Issue by jon900** [fluid-player/fluid-player#152]
Hi, I have a problem. When I go back and forth in the video several times, at the end of the video it gives this error in the console:

[Error] (202): Failed to play video.

And now it pauses, I can not reproduce it again, I have to click several times to reproduce it again.

**Comment by jon900** [comment]
I wanted to show a div at the end of the video, so I tried to modify this function:

`     onMainVideoEnded: function () {
         var player = fluidPlayerClass.getInstanceById (this.id);
         // we can remove timer as no more ad will be shown
         if (Math.floor (player.getCurrentTime ())> = Math.floor (player.mainVideoDuration)) {
             clearInterval (player.timer);
             jQuery ('. class'). show (); // this is what I added
         }

     },`

Everything works perfect, except when I do what I said earlier. Error 202 and "onmainvideoended" is not executed

**Comment by cian-exads** [comment]
Hi @jon900, thanks for the feedback. As you've mentioned there's two issues, the 202 error and "onMainVideoEnded", both of which I've been able to reproduce. Both issues will be looked into.

**Comment by cian-exads** [comment]
Hi @jon900, fixes for your issues just went live with v2.2.1 of Fluid Player. I hope these fixes solve your problem!

**Comment by adtechnology** [comment]
Hello @cian-exads I still have the same problem with the current version. The Muted Autoplay is not working on Chrome, Safari and Mobile Browsers. 
I get the error [Error] (202): Failed to play video.

Here you have my sourcecode
https://github.com/adtechnology/adtechnology.github.io/blob/master/tests/autoplay.html

A Preview: https://adtechnology.github.io/tests/autoplay.html


Thank you!
