### ISSUE TITLE
How do i add 2 video sources?

### ISSUE THREAD

**Issue by nathapol1992** [fluid-player/fluid-player#16]
I tried to read all of instructor but i can't find the solution to add more source or separated for HQ-video button and SD-video.
I can only add just 1 source video on 1 player. Is it possible to add 2 video sources on 1 player?

**Comment by cian-exads** [comment]
Hi @nathapol1992, currently the player only allows 1 video source. The ability to add multiple sources is a feature which will be considered in future versions. Thank you very much for your feedback.
