### ISSUE TITLE
Video Preview Thumbnails seem to be broken for DASH/ HLS

### ISSUE THREAD

**Issue by majamee** [fluid-player/fluid-player#161]
Hi,
I was testing to get video previews working following your guide at https://docs.fluidplayer.com/preview_configuration/, but so far without success.

I have also hosted here a demo that you can check it out:
https://majamee.000webhostapp.com/player/fluid-player.html

The WebVTT is included in the player code as shown in your documentation and the WebVTT file itself can be found here view-source:https://majamee.000webhostapp.com/player/thumbnails/thumbnails.vtt next to the referenced images.

I checked the WebVTT file for issues, but it is reported to be valid by several online WebVTT validators. I also checked, if the player throws any errors in the console, but also nothing. Therefore, I need to ask you, can you please check the issue and see if it is indeed a bug of some kind?

Thank you very much & keep up your great work, I am a fan of your player especially since version 2.0 and therefore I included it in my transcoding pipeline (http://alpine-dash-hls.gq/), testing it with each release and following its development closely.

Thank you & best regards

**Comment by cian-exads** [comment]
HI @majamee, thank you for the feedback, we're happy to see the community growing and are excited to continue to improve Fluid Player with the help of users like yourself.

Regarding your issue I believe it's related to the path you've set in the vastOptions. The path set here goes from the route, and not the current file directory. What you have set is `file: 'thumbnails/thumbnails.vtt'`, whereas the file is located under `player/thumbnails/thumbnails.vtt`. Can you change your params to set `file: 'player/thumbnails/thumbnails.vtt'` and see if that resolves the issue? Let me know if this doesn't resolve it and I'll take a deeper look into it.

We have a feature in discussion at the moment to improve how the vtt files are set, as this sort of issue has occurred in the past. We're aware and hope to improve this feature.

**Comment by majamee** [comment]
Hi @cian-exads, than you for your response.
I changed the source according to your input, but it seems to make no difference.
Updated version can be found here: view-source:https://majamee.000webhostapp.com/player/fluid-player.html

**Comment by cian-exads** [comment]
I'll look into this issue further @majamee

**Comment by solanex** [comment]
Seems like the convertVttRawData function does not handle seperate images. It will check for sprite images by checking for the existence of a # in the URL and an xywh= value, if so, there will be some data added to the result array. However when it is not a sprite, it does nothing, resulting in an empty result array being returned and saved into player.timelinePreviewData

Further more the function drawTimelinePreview expects these sprite coordinates to be set so it can setup the css values for the preview overlay div.

I have modified the function convertVttRawData quickly to test and now it does show something, but depending on the thumb size the width & height values hardcoded here will probably only show a section of the thumb.

As a workaround one could just add #xywh=0,0,w,h to each seperate thumbnail image in the VTT file, where the w & h are the actual width and height of the thumb.

modified convertVttRawData function for test:
`var convertVttRawData = function(vttRawData) {
                    if (!(
                            (typeof vttRawData.cues !== 'undefined') &&
                            (vttRawData.cues.length)
                        )) {
                        return [];
                    }

                    var result = [];
                    var tempThumbnailData = null;
                    var tempThumbnailCoordinates = null;

                    for (var i = 0; i < vttRawData.cues.length; i++) {
                        tempThumbnailData = vttRawData.cues[i].text.split('#');

                        if (
                            (tempThumbnailData.length === 2) &&
                            (tempThumbnailData[1].indexOf('xywh=') === 0)
                        ) {
                            tempThumbnailCoordinates = tempThumbnailData[1].substring(5);
                            tempThumbnailCoordinates = tempThumbnailCoordinates.split(',');

                            if (tempThumbnailCoordinates.length === 4) {
                                result.push({
                                    startTime: vttRawData.cues[i].startTime,
                                    endTime: vttRawData.cues[i].endTime,
                                    image: (player.displayOptions.layoutControls.timelinePreview.sprite ? player.displayOptions.layoutControls.timelinePreview.sprite : tempThumbnailData[0]),
                                    x: parseInt(tempThumbnailCoordinates[0]),
                                    y: parseInt(tempThumbnailCoordinates[1]),
                                    w: parseInt(tempThumbnailCoordinates[2]),
                                    h: parseInt(tempThumbnailCoordinates[3])
                                });
                            }
                        }
                        else
                        {
                            result.push({
                                startTime: vttRawData.cues[i].startTime,
                                endTime: vttRawData.cues[i].endTime,
                                image: tempThumbnailData[0],
                                x: 0,
                                y: 0,
                                w: 120,
                                h: 120
                            });
                        }
                    }

                    return result;
                };`

**Comment by majamee** [comment]
@solanex Thank you very much for your input. 

@cian-exads So, if I understand everything correctly, the documentation was misleading as separate images where actually not yet supported, but with the new merge request becoming available in one of the next releases, everything should be working as intended. Is this correct? Will the merge be part of the next release or is anything still blocking it from being included?

**Comment by majamee** [comment]
@cian-exads Just tested with the latest release, now the preview area for pictures is shown, but no preview thumbnails inside. Do I have to change something in my code as well in order to make it work now?
I followed strictly your documentation here to implement: https://docs.fluidplayer.com/preview_configuration/#vtt-format
(for separate images)

**Comment by cian-exads** [comment]
We can see 404 errors in the console, so the image paths don't seem to be correct. Could you try setting the new **spriteRelativePath** parameter to **true** so it looks in the *thumbnails* folder instead of just inside *player*?
```
fluidPlayer(
    'my-video',
    {
        layoutControls: {
            timelinePreview: {
                file: 'thumbs/thumbnails.vtt',
                spriteRelativePath: true,
                type: 'VTT'
            }
        }
    }
);
```

**Comment by majamee** [comment]
That's it! Great job, everyone. Btw. I will integrate Fluid Player in the newest version in my conversion pipeline project here: http://alpinde-dash-hls.gq

Fluid Player is now the only one which supports automatic generation of DASH, HLS & WebVTT files ready configured to be used. 

@cian-exads If you find the project remotely interesting, I would be happy to provide the solution for getting fluid-player set up in now time with sane defaults and focus on UX in an automated way. :) Happy to discuss anytime.

**Comment by majamee** [comment]
@cian-exads One improvement suggestion:
In order to make it more obvious that the new `relativePath` parameter applies also for separate images, it would be great to have it renamed without the `sprite` in the name. :)

**Comment by majamee** [comment]
Everything updated in the trancoding pipeline to include also automatic thumbnail generation and inclusion in player. Will create drag'n'drop-able files in `output` folder created next to input video file. :)

Thank you for your great support so far. I moved fluid player up to visually increase its importance for the overall project. If you want you can check it out at http://alpine-dash-hls.gq
I am open to interact even stronger with you and I am open for contact about any questions, concerns, feedback and improvement ideas.

**Comment by majamee** [comment]
Bug seems fixed. Thanks again. :)
