### ISSUE TITLE
When VAST server has the content-type not as XML, xmlHttpReq.responseXML is null

### ISSUE THREAD

**Issue by sinni800** [fluid-player/fluid-player#162]
When the VAST server sends it's VAST xml with a content type that is not "application/xml", the script will error out on "xmlHttpReq.responseXML is null". 

Now, I have a few ideas on how to handle this, since the error might not be too straightforward to diagnose.

1. Put a hint in the documentation that the VAST should have the http header "content-type" set to "application/xml"
2. Add a custom error if `xmlHttpReq.responseXML` is null,
3. Parse the XML manually using `DOMParser::parseFromString` (erroring when the XML is invalid) when `responseXML` is null. 

Option 1 and 2 would be the most "correct" way to handle this, while option 3 is the way to make the code the most "compatible" and "out of the box" working. I don't know of any disadvantages beyond that (is parsing manually maybe slower? No idea!). Another tangent with option 3 is when you have an ad server you have no power over and it would be a hassle to get through to the right people to get it changed server-side.

**Comment by b202020** [comment]
Hi @sinni800 , thanks for the feedback, an active community helps us identify the areas that need improvement so we appreciate messages like these.

I've reproduced this issue and will put a fix in place, will go with your 1. and 2. suggestions. Regarding 3rd point I would prefer to stay with RFC standards.

**Comment by b202020** [comment]
Hi @sinni800 , this issue is now handled in version 2.2.1, as you recommended in point 1 and 2.
