### ISSUE TITLE
Firefox, height = 0?

### ISSUE THREAD

**Issue by jndorst** [fluid-player/fluid-player#183]
I downloaded the latest version of firefox to test if fluidplayer works correct in this browser, unfortunately it doesnt. For some reason it sets the height to 0 which i found out in the developer mode.
![naamloos](https://user-images.githubusercontent.com/39653715/40589733-182ead9a-61f3-11e8-8828-e0716415b889.jpg)

**Comment by jndorst** [comment]
It seems the problem is with the var 'clientHeight' in fluidplayer.js, when i set this manually to a certain height it works fine, the player is visible. I only have this problem in firefox, other browsers, including mobile, work just fine.

**Comment by ShpendBerisha** [comment]
You can try this css it worked for me there was a conflict with bootstap helpers for me.
My solution is:

```
.fluid_video_wrapper {
    width: 100%;
    max-width: 100%;
    height: 0;
}
.fluid_video_wrapper {
    padding-top: 56.25%;
}

Maybe it helps.
```

**Comment by jndorst** [comment]
It was actually a pretty simple solution for me. 
After adding fillToContainer:true to LayoutControls it worked like it should work.
Thanks for your thoughts.
