### ISSUE TITLE
How to keep volume persistence among different video ?

### ISSUE THREAD

**Issue by ngodup** [fluid-player/fluid-player#187]
When I change video player volume, I need to keep the same volume for next video also. Currently when a change in volume will not safe or remember in next video. It just set to full volume?

**Comment by cian-exads** [comment]
Hi @ngodup, currently the volume will always go back to default. In the next Fluid Player release the volume settings should persist in the next videos. I will update this ticket when the release is live.

**Comment by ngodup** [comment]
Thanks @cian-exads

**Comment by cian-exads** [comment]
Hi @ngodup this feature went live with v2.3.0. Persistent settings for volume, quality, speed and theatre settings are available. More details available on the docs - https://docs.fluidplayer.com/layout_configuration/#persistentsettings
