### ISSUE TITLE
CTA link overlays Skip Button and hides it on Twitter in-app browser

### ISSUE THREAD

**Issue by jf-he** [fluid-player/fluid-player#204]
Hi,

I am using 2.2.1

The CTA link is overlaying the Skip Button and hides it on Twitter in-app browser.

If you click on a link in a Tweet and land on a page with fluidplayer and an in-stream ad, you won't see the Skip button. This is obviously an issue as uses might not understand it is an ad and/or are forced to watch the full ad thus increasing the bounce rate.

The only workaround I have found thus far is to hide the CTA all together. Changing the position will not work. This is not ideal, since some advertises pay per click.

This is a problem since I send some significant amount of my traffic from Twitter.

Kind regards,
JF

**Comment by cian-exads** [comment]
Hi @drexlspivey, we'll take a look into this. Is it correct that this is on mobile devices?

**Comment by drexlspivey** [comment]
You are correct, I reproduced it on an Android phone.

**Comment by HariPriyaKuberSingh** [comment]
@jf-he - Can you confirm if you could still reproduce the same issue ?

**Comment by HariPriyaKuberSingh** [comment]
@jf-he - is there any update? does the issue persist?

**Comment by jf-he** [comment]
The issue is fixed, I was unable to reproduce. The CTA link now appears above the "Skip" button which is good.
