### ISSUE TITLE
Video malfunction

### ISSUE THREAD

**Issue by machonatural** [fluid-player/fluid-player#21]
Hi guys, can you please help me solve this situation: when i upload a video and post the first and second time a got a gray screen with  the ad banner in corner upleft in  the space should show up the player and no play. I have to update the browser page and  then the video player appears, but no longe ad banner. What could this be?

If i place the video in the body of the post it works normally. Appearing the banner, disappear when play  and appears at the end.

**Comment by cian-exads** [comment]
Hi @machonatural, from reading the description the cause of this issue is not clear. Could you please provide us with a link to a page where we can see this happening? Thank you very much.

**Comment by machonatural** [comment]
Hi cian-exads, as i said before. Its hard to see because it happens randomly i post the video ,but just to check i ll send the links:
http://machosaonatural.com.br/fodeu-com-encanador-no-quintal-de-casa/
Right now i got the picture i sent you.![capturar](https://cloud.githubusercontent.com/assets/25014633/26829251/2b78534e-4a9b-11e7-9c24-48195e3d43d8.PNG)

At this second link the video was placed in the body of post
. Its the first one called "flagrados"
http://machosaonatural.com.br/flagrados-mecanico-pentelhos-cozinha-bigode-videos-curtos/

How you can see its working perfecly.

**Comment by cian-exads** [comment]
Hi @machonatural, from looking at the page it seems that there is some custom css affecting the appearance of the Fluid Player. I have tried to reproduce this on my own test page with no success. This video also uses the example thumbnails.vtt, which is perhaps not giving the results expected. 

Could you please create a test page that contains only the necessary Fluid Player code to play a video? Also note the the necessary js and css files are now available via cdn to keep up to date with the latest version, example below:

```
<link rel="stylesheet" href="http://cdn.fluidplayer.com/current/fluidplayer.css" type="text/css"/>
<script src="http://cdn.fluidplayer.com/current/fluidplayer.js"></script>
```
