### ISSUE TITLE
Touching the video will trigger play/pause twice in a row

### ISSUE THREAD

**Issue by sinni800** [fluid-player/fluid-player#210]
This is due to two events being fired, check here:

https://github.com/fluid-player/fluid-player/blob/ab6c51bb79558678e0dc93c5d89f075a4cab98c4/fluidplayer.js#L3243

When the video is touched, both click and touchstart are triggered, toggling the play/pause state of the video twice in a row!

**Comment by cian-exads** [comment]
Hi @sinni800, yes we are aware of this issue and will be putting a fix in place for this.

**Comment by cian-exads** [comment]
Hi @sinni800, the fix for this issue went live with v2.4.0. This may require cache to be cleared before it's visible. Closing this issue.
