### ISSUE TITLE
[Issue] When adblock is enabled and there is an in-video most controls don't work

### ISSUE THREAD

**Issue by entrailz** [fluid-player/fluid-player#211]
Hey,

Seems there is a bug where if there is an in-video advert and adblock is enabled, seeking the video, changing quality etc does not work.

Thanks.

**Comment by cian-exads** [comment]
Hi @entrailz, we're aware of this particular issue and are looking into a solution. Can you please link a test page where we can see this occur as there have been some differences in the issue reported? Thank you very much.

**Comment by cian-exads** [comment]
Hi @entrailz, the fix for this issue went live with v2.4.0. Thank you for reporting it! Closing this issue.
