### ISSUE TITLE
Android clicking in the middle of the video does not work as expected

### ISSUE THREAD

**Issue by majamee** [fluid-player/fluid-player#215]
Hello dear fluid player developers,

during my tests of the latest version I discovered a small bug:
On Android (Chrome) the fluid player has an issue with "clicking" in the middle of the video.

Expected behavior: The Play/ Pause animation is visible and the playback status toggles accordingly.
Actual behavior: The Play/ Pause animation is visible, but the playback status stays as it is.

Can be checked at: http://alpine-dash-hls.gq/player/fluid-player.html

Maybe, it is connected to this bug reported here: https://github.com/fluid-player/fluid-player/issues/210

**Comment by cian-exads** [comment]
Hi @majamee, yes it does seem to be related to the reported issue. There will be a fix for this in the next release. Thanks for letting us know!

**Comment by cian-exads** [comment]
Hi @majamee, the fix for this issue went live with v2.4.0. It may require clearing cache before it's visible. Closing this issue.

**Comment by majamee** [comment]
Hi @cian-exads just tested on Android using Chrome and incognito tab to exclude caching issues, but the playback touch control by tapping the middle of the video is still extremely unreliable unfortunately. Using a double click gesture helps often (tapping shortly 2 times with the finger), but not always. Most times you see the animation, about the playback change, but the playback status gets not updated.
Playing keeps playing and the stopped keeps stopped.

Could you please re-check? https://alpine-dash-hls.gq/player/fluid-player.html
OS: Android 8.0
Browser: Chrome latest

**Comment by cian-exads** [comment]
Is it the same behaviour as always @majamee? I've just tested on multiple android devices and I'm getting correct behaviour. What device are you using?

**Comment by majamee** [comment]
Xiaomi Mi A1 alias tissot @cian-exads
