### ISSUE TITLE
Progressbar doesnt hide in Edge

### ISSUE THREAD

**Issue by jndorst** [fluid-player/fluid-player#216]
When skipping to another point in the video (by clicking on the progressbar) the progressbar doesnt hide itself.

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by cian-exads** [comment]
Hi @jndorst, I'm going to mark this as a bug and look to get a fix in place, as I was able to reproduce this.

**Comment by jndorst** [comment]
Great, thanks. I love the player!

**Comment by cian-exads** [comment]
Hi @jndorst, the fix for this issue went live with v.2.4.0. Closing this issue.
