### ISSUE TITLE
After last upgrade the videos got small even in desktop

### ISSUE THREAD

**Issue by machonatural** [fluid-player/fluid-player#220]
Can you guys verigy why the videos are displayin in small size (smartphone size) even when we watch them in desktop computer? It seems a chrome bug because in firefox i see it normal.

**Comment by cian-exads** [comment]
Hi @machonatural, can you share a link to a page where I can check this out myself?

**Comment by machonatural** [comment]
***adult content***
http://machosaonatural.com.br/deu-carona-e-tambem-a-bunda-ao-mochileiro/

**Comment by cian-exads** [comment]
I'm unsure what's causing it but the video size seems to be changing, depending on when it's initialised. It's different on page reloads for me, not specific to a browser. This is added in via WordPress is that correct? 

Can you set the params *fillToContainer* to *true*, as I believe this will ensure the expected results. https://docs.fluidplayer.com/layout_configuration/#filltocontainer

**Comment by machonatural** [comment]
Do you know the path that contains that string in wordpress?

**Comment by machonatural** [comment]
Tks it worked like a charm...

**Comment by cian-exads** [comment]
Brilliant stuff, happy to hear it's resolved!
