### ISSUE TITLE
[Error] (204): Timeout error. Failed to play video.

### ISSUE THREAD

**Issue by malyduo** [fluid-player/fluid-player#225]
Hi,
i have problem on IE/EDGE, source hls m3u8: [Error] (204): Timeout error. Failed to play video. 

On other browsers streaming is OK.

**Comment by cian-exads** [comment]
Hi @malyduo, I just tested hls and m3u8 files on Edge 17 & 16 and IE11 and they worked correctly for me. Can you link me a page where I can see this occur?

**Comment by malyduo** [comment]
For now there's impossible because it's private business streaming. I will try to prepare link for you as soon as it is possible to show this issue.

Thanks!

**Comment by acislak** [comment]
I can confirm this issue. 

Sample stream:
http://obradyonline.pl/live/qp9gxm7ooi

This live stream works well in chrome. In FF 60 one sees only black screen.

Console log shows:
[Error] (204): Timeout error. Failed to play video. fluidplayer.min.js:1:9164

**Comment by Addvilz** [comment]
I have seen this happen in Chrome too. Not sure what causes this.

`[Error] (204): Timeout error. Failed to play video.`

**Comment by rryuno** [comment]
bump
