### ISSUE TITLE
v2.4.0 Play/Pause center buttons not working in Chrome/Android

### ISSUE THREAD

**Issue by det66** [fluid-player/fluid-player#226]
After I started a video with the center play button I tap on the same spot (center) and the pause button appears for half a second but the video doesn't pause. I have to tap 2 or three times more to make it pause.
Same problem is to make it play again.
Tapping outside the area of the center buttons is working correct.

**Comment by cian-exads** [comment]
Reproduced, will look to get this resolved. Thanks for the report @det66

**Comment by majamee** [comment]
@det66 Thank you for your bug report. I am affected by the same issue, but I didn't notice that it is working outside that middle area correctly. Always tried just the middle. So thanks for your better description.

**Comment by toha-chernovol** [comment]
Are there any fixes to this issue?
Have the same problem

**Comment by Addvilz** [comment]
I could not reproduce this issue in the latest version of Fluid Player. Considering that and how old this issue is, closing. Submit a new issue if this happens again.
