### ISSUE TITLE
 Vast seems not working after upgrade

### ISSUE THREAD

**Issue by machonatural** [fluid-player/fluid-player#232]
Hi can you  verify if the vast tag is working in my page? as  my earnings dropped,  i  see theres no video  ads in  stats.  It started around  22 this month.  Url - machosaonatural.com.br

**Comment by golikov** [comment]
Hi @machonatural!
It doesn't seem to be a player-related issue. The VAST tag comes empty.
Please contact the ad network customer support.
This is an open-source repository dedicated to the fluid-player only.
