### ISSUE TITLE
Can we have a new class or id on full screen mode?

### ISSUE THREAD

**Issue by ShpendBerisha** [fluid-player/fluid-player#239]
Hi, in one template Im using a bootstrap helper and on all my sites I have a `padding-top:56%;`
But I noticed a problem on chrome and and opera when I open the video in full screen mode.

So, I'm adding two screenshots about that.

1. https://image.ibb.co/nxVOMd/Schermata_2018_07_03_alle_19_58_11_copy.png
2. https://image.ibb.co/jTVZSJ/Schermata_2018_07_03_alle_19_58_28.png (second image is the solution for me)

Maybe its possible to add the class via jquery from here too I will do some tests, but would be great if you can do it in fluidplayer.js file.

Thank You.

**Comment by ShpendBerisha** [comment]
resolved with css thank you anyway :)
```
.fluid_video_wrapper:-webkit-full-screen {padding:0 !important;}
.fluid_video_wrapper:-moz-full-screen {padding:0 !important;}
```

**Comment by cian-exads** [comment]
Hi @ShpendBerisha, glad to see you came across a solution! As this is a custom css resolution I'm going to close this issue. Thank you!
