### ISSUE TITLE
I have the question about video url (src='example.mp4') -  #Help Wanted #Question 

### ISSUE THREAD

**Issue by crnidario** [fluid-player/fluid-player#240]
I use fluidplayer on my sites and I really love this player. I have the next question:
 Is there any way to hide the video url (example.mp4) from this part of the <source src='**example.mp4**' type='video/mp4' /> through some script or some encryption. So when someone read a page source can't easily find the file, it need to be masked. This is because some people are stealing my mp4 files (which are static) and that way troubles my bandwidth. 
Please help me if you have a solution, or an idea how I could do it, but it's important to Google VideoBot can still read video file... 
It would mean to me a lot..
Thanks in advance

**Comment by gibigate** [comment]
you must do this in the backend, for example generate some encrypted url, and in .htaccess write right rules

**Comment by cradonn** [comment]
Hiding the video URL will not be an option, you should however investigate “hotlinking” specific to your web server. 

Some general info that should point you in the right direction: https://www.keycdn.com/support/what-is-hotlinking/
