### ISSUE TITLE
myFluidPlayer.on('error', function(){ })

### ISSUE THREAD

**Issue by Yahook** [fluid-player/fluid-player#241]
Dear deverlopers of Fluid Player,

I started to use FluidPlayer on my websites, but I can't find a very important function which will allow me to do something on errors. For example video is missing for some reason and in this case I want to catch this error, load a new video url into a player and play it and if it's needed to repeat this again. How can I do that?

**Comment by cian-exads** [comment]
Hi @Yahook, we'll be continuing to add more Fluid Player API calls like those outlined in the [Fluid Player Docs](https://docs.fluidplayer.com/api/), but at the moment there's none for catching errors. For now you'll need to do it manually, there are plenty of articles on handling html5 video errors - https://stackoverflow.com/questions/5573461/html5-video-error-handling

I'll keep this issue open and will bring it up to be looked at for future development.

**Comment by HariPriyaKuberSingh** [comment]
@Yahook  - Does the issue persist ?

**Comment by tallesairan** [comment]
I'm studying how to implement this error handling, but I'm not very good with code patterns, if I can implement it I'll let you know here

**Comment by sergiomcsousa** [comment]
@Yahook does this error persist? Do you still need this feature?

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.

**Comment by AlejandroAkbal** [comment]
Hey, I still need this, otherwise its a hassle to handle player errors
