### ISSUE TITLE
Video url with 302 redirect

### ISSUE THREAD

**Issue by Yahook** [fluid-player/fluid-player#242]
Dear deverlopers of Fluid Player,

I've noticed that Fluid Player can't play video urls which do 302 or other redirect. It's possible to play such video urls in other players (flowplayer for example). It would be great if you could add this feature in your next releases.

**Comment by cian-exads** [comment]
Hi @Yahook, thanks for your suggestion. We'll put it into consideration for future development work!

**Comment by crnidario** [comment]
On my site mp4 urls with 302 redirect works properly. I also use fluid-player

**Comment by Yahook** [comment]
I tryed this 302 redirect with hls files. May be it works properly for mp4 urls, I haven't checked.

**Comment by Addvilz** [comment]
Not something we can address in Fluid Player. See video-dev/hls.js#104 for more details
