### ISSUE TITLE
Fluid player overflowing page

### ISSUE THREAD

**Issue by machonatural** [fluid-player/fluid-player#244]
Hi guys. i ve got an issue in my page: the player shows itself in his size and takes all page, going outside the visible area. It should detect and adapt the video size to the place wheres holded. How fix this?

Exemple link (adult content)
http://machosaonatural.com.br/brechando-a-foda-no-banheiro-do-colega-de-ap/

**Comment by machonatural** [comment]
In all browser desktop  i ve tested: chrome, edge and firefox. In mobile is ok.

**Comment by bharath-exads** [comment]
Hi,

I look like you have used the attribute **'fillToContainer: true',**  it makes the player take full height and width of parent element it is enclosed.
Some solutions which can be used are 
1. setting max-height and max-width to the parent element of the player is enclosed.
2. or to fix height and width to the player, here is sample code https://codepen.io/bharath-exads/pen/ydroKL
