### ISSUE TITLE
Problem with: fillToContainer: true,

### ISSUE THREAD

**Issue by crnidario** [fluid-player/fluid-player#245]
I changed the fillToContainer from false to true, but nothing happens.. effect is same.
All this works properly on your site https://docs.fluidplayer.com/builder/
Can you check this?
p.s.
I use last version 2.4.2 (I also noticed that with some earlier versions this does not work)

**Comment by cian-exads** [comment]
Hi @crnidario, this parameter will work based on the element the player is inside, for this reason I'd need to see it on your own site. Can you please link a page where I can see this behaviour? Thank you

**Comment by crnidario** [comment]
Can you please check?

**Comment by crnidario** [comment]
Sorry for late answer, I was setup as you write but again have same problem, can you please check on https://vaixo.com/scr/test.php

**Comment by crnidario** [comment]
Is there any chance to be solved?

**Comment by cian-exads** [comment]
@crnidario the test page looks correct to me, the player is confined to the specified div.

**Comment by crnidario** [comment]
as you can see in the page source at https://vaixo.com/scr/test.php , I set up:
fillToContainer: true,
why the image was not spread via the whole player
Check image: https://i.imgur.com/oxdU3XI.jpg
All this works properly on your site https://docs.fluidplayer.com/builder/
Check image: https://i.imgur.com/O46uIva.jpg

**Comment by bharath-exads** [comment]
Hi,

Please check this ticket
https://github.com/fluid-player/fluid-player/issues/302

**Comment by bharath-exads** [comment]
Duplicate of #302
