### ISSUE TITLE
Support for VR Video?

### ISSUE THREAD

**Issue by jinyus** [fluid-player/fluid-player#246]
Any plans for vr support in the near future?

**Comment by cian-exads** [comment]
Hi @jinyus, this isn't something we have planned for any upcoming releases. I will bring it up with the other developers to be discussed.

**Comment by ferminq989** [comment]
It would be great to play this type of videos.

**Comment by Addvilz** [comment]
We have added limited VR support in version 2.4.10, see #399. 

Is this what you were looking for?

**Comment by Addvilz** [comment]
Closing as inactive
