### ISSUE TITLE
How to add the preload

### ISSUE THREAD

**Issue by freddiehdxd** [fluid-player/fluid-player#247]
Hello l want to know how to add the 
preload="auto" or something like that

**Comment by cian-exads** [comment]
Hi @freddiehdxd, we don't have this as a Fluid Player parameter but we will look to include it in a future release.

**Comment by Addvilz** [comment]
That depends. Preload seems to work fine with basic VOD videos. For streaming, this is controlled by streamers, so nothing to do here.
