### ISSUE TITLE
postmessage support

### ISSUE THREAD

**Issue by supersh86** [fluid-player/fluid-player#250]
Hello everyone, thank you for such a handy player.

I often have to communicate with the player in the iframe via postmessage.

I would like to see that the player, in addition to transferring the download, playerInitCallback 

transmitted the same pause
the launch and end of video advertising
the end of playing the video.

Sorry for my english.

**Comment by cian-exads** [comment]
Hi @supersh86, we have a few ways to interact with the different events and will continue to add in additional calls. Please let us know when you are missing specific events so we can consider them as a priority. 

Regarding your current events I believe there are ways to help with this.
For pause we have a function call that you can use, it's documented here -https://docs.fluidplayer.com/api/#on-pause-function
For the end of VAST video we have a specific parameter that can be used called **vastVideoEndedCallback** - https://docs.fluidplayer.com/ad_configuration/#vastadvanced
I don't believe we have a Fluid Player parameter for the end of the video but you could use a custom event. There's an internal parameter used to detect if it's VAST or main video ending which you can use. **videoPlayerElement** is the <video> element and **player** is the Fluid Player element
```
videoPlayerElement.addEventListener('ended', function() {
  if (player.isCurrentlyPlayingAd) { return; }

  // custom function stuff
}
, false);
```

Let me know if these help!

**Comment by Addvilz** [comment]
Not sure what is meant here - not updated for a long time, so closing.
