### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by jozef5198** [fluid-player/fluid-player#252]
One of main functions is missing in player. Subtitle support.

**Comment by cian-exads** [comment]
Hi @jozef5198, subtitle support is in the development pipeline, but I will mention this issue to maybe look to prioritise it.

**Comment by plonknimbuzz** [comment]
@cian-exads where we can find it? i browse all non master branch but not find any `subtitle` string in fluidplayer.js, and changelog.md
thanks

**Comment by plonknimbuzz** [comment]
owh. i see
i just miss understand your word.
thanks for the clarification. this means alot to me.

**Comment by Media182** [comment]
Would be really good to have .VTT support in player.

**Comment by bharath-exads** [comment]
#348

We are adding Multiple Subtitles (VTT) support

**Comment by bharath-exads** [comment]
Duplicate of #59

**Comment by bharath-exads** [comment]
Hi,

Please check our latest release which has support for subtitles

**Comment by Media182** [comment]
Subtitles are not working in current version?
Can't see them working on demo page: https://docs.fluidplayer.com/docs/configuration/subtitles/
