### ISSUE TITLE
vpaid support

### ISSUE THREAD

**Issue by supersh86** [fluid-player/fluid-player#253]
Hi
Is it possible to support the vpaid format in the future?

On the site in the documentation about this nothing is said.

**Comment by cian-exads** [comment]
Hi @supersh86, at the moment VPAID is not supported. We'll discuss it for consideration in upcoming releases.

**Comment by KrzyMadejski** [comment]
Some decisions/progress regarding these enhancement ?

**Comment by bharath-exads** [comment]
#383

**Comment by Addvilz** [comment]
I should now support VPAID. See #383
