### ISSUE TITLE
[Error] (900): Failed to load Vast  && [Error] (401): Failed to load Vast

### ISSUE THREAD

**Issue by supersh86** [fluid-player/fluid-player#257]
I installed a link on the VAST player and it does not work.
Please help.
var myFluidPlayer = fluidPlayer('hls-video',
  {
      layoutControls: {
          primaryColor:           false,
          playButtonShowing:      true,
          playPauseAnimation:     true,
          fillToContainer:        true,
          autoPlay:               false,
          mute:                   false,
          keyboardControl:        true,
          layout:                 'default',
          allowDownload:          false,
          playbackRateEnabled:    false,
          allowTheatre:           true,
          logo: {
              imageUrl:           null,
              position:           'top left',
              clickUrl:           null,
              opacity:            1
          },
          controlBar: {
              autoHide:           true,
              autoHideTimeout:    3,
              animated:           true
          },
          timelinePreview:        {},
          htmlOnPauseBlock: {
              html:               null,
              height:             null,
              width:              null
          },
          playerInitCallback:     (function() { })
      },
       vastOptions: {
          adList: [
              {
                  roll: 'preRoll',
                  vastTag: 'https://out.pladform.ru/getVast?pl=115226&type=1&license=1&thematic=687&age=4&duration=1448&target=web-html5&mobile&mobileapp&adformat=1&dl='+refer,
                  adText: ''
              } 
          ]
      }
  }
);

**Comment by rdimouro7373** [comment]
I too am experiencing a similar issue with VAST for a client's site. I was able to successfully install the video player and connect to the sources, but the ads should play when the user click's play, and they don't do so.

**Comment by supersh86** [comment]
I thoroughly examined the XML of my source and noticed that it produces a list of other external XML.
The tag is called <VASTAdTagURI>.
And if we go there, there will already be <MediaFiles>

**Comment by cian-exads** [comment]
@supersh86 the end _mediaFile_ of the shown *vastTag* is a VPAID link which is not supported at the moment, so is causing the error.

@rdimouro7373 I would need to see a test page or example of your code to be able to tell if it's the same issue you're having. Can you link provide additional information?

**Comment by supersh86** [comment]
@cian-exads 
Maybe you will be interested. MOL has released an SDK for advertising.
https://github.com/MailOnline/mol-video-ad-sdk

**Comment by killown** [comment]
same here [Error] (900): Failed to load Vast

**Comment by Addvilz** [comment]
No update since 2018 and some information missing. I am closing this, but please do comment if this is still an issue.
