### ISSUE TITLE
New Features Request

### ISSUE THREAD

**Issue by amanrajveer** [fluid-player/fluid-player#259]
Hi, can we have these below features with Fluid Player?

1. VPAID, VMAP, Google IMA support.

2. Match codecs to browsers dynamically which can deliver the best quality possible for each user, based on their browser which will save 50% bandwidth or more.

3. DRM stream support.

4. Cast video directly to the television screen using Chromecast and the Fluid Player.

5. The adaptive bitrate choosing feature to avoid re-buffering and minimize the startup time, while providing the best possible quality.

6. Fast Channel Switching between two channels without destroying the player and speeding up the process. (Fluid Player&apos;s ability to switch between streams without having to run setup twice. This improves the speed immensely.)

7. Display multi language and audio options available with the Fluid player.

8. The ability to keep a minimized player in the corner of the screen when user scroll too far. (This keeps the Fluid Player visible to users in any case.).

9. Android and ios SDK

Thanks

**Comment by cian-exads** [comment]
Hi @amanrajveer, thanks for the feedback, there's a lot of great recommendations to look into here. Some points have been discussed before, and we'll consider the other points for future development planning!

**Comment by amanrajveer** [comment]
Hi @cian-exads
Thanks for replying and considering these all features in future development planning.

Regards
Aman

**Comment by Addvilz** [comment]
This ticket is effectively 9 different issues/feature requests. If any of them are still relevant, please open new tickets for them, a ticket per each individual issue please. Issues that contain more than one actual issue are unmanageable and will be closed. Thanks!
