### ISSUE TITLE
PLUGIN WORDPRESS

### ISSUE THREAD

**Issue by cespa92** [fluid-player/fluid-player#260]
Hello, I installed on my site with wordpress the plugin of this player, but when I post the player appears very small here a screenshoot https://prnt.sc/kkd284

and here link of my site: https://cespaplay.com/peliculas/shot-caller/

How can I solve it?

**Comment by cian-exads** [comment]
Hi @cespa92, for wordpress related issues we recommend you post in the wordpress support page so the plugin developer will be able to address where others can also benefit from the response. https://wordpress.org/support/plugin/fluid-player

Let me know when you get sorted and I'll close out this ticket.

**Comment by Addvilz** [comment]
Not related to the player itself.
