### ISSUE TITLE
postRoll video is not always shown

### ISSUE THREAD

**Issue by java168** [fluid-player/fluid-player#261]
Hi,

i recently received a project and started to dig into the codes. have some issues with the postRoll.
a simple test script below.  but the results are really weird.  the postRoll video sometimes showed up.
sometimes it doesn’t. (most of the time) can you guys give me some suggestions. thank you very much

...
 vastOptions: {
                adList: [
                    {
                        roll: 'postRoll',
                        vastTag: '/test/postRoll-vastLinear.xml',
			adText: 'Thanks for watching',
                        adTextPosition: 'top right'
                    }
                ]
            }
...

**Comment by java168** [comment]
i looked it again today and debugged into it.
i found out if i give a few second to clean it up then my postRoll will show.

fluid-player.js
.....
 //we can remove timer as no more ad will be shown
        if (Math.floor(player.getCurrentTime()) >= Math.floor(player.mainVideoDuration)) {
	    ///////maybe too premature to clean it
            ///////clearInterval(player.timer);
		    setTimeout(function(){ 
				clearInterval(player.timer);
		    }, 3000);
        }
...

**Comment by bharath-exads** [comment]
Hi,

Please try using our latest release
https://github.com/fluid-player/fluid-player/releases/tag/v2.4.7

We have fixed the postRoll uncertainty
