### ISSUE TITLE
Can you render from JS and switch video source via JS ?

### ISSUE THREAD

**Issue by kevin074** [fluid-player/fluid-player#262]
I understand that you can appenChild a <source> before calling fluidPlayer('#selector'), but is there a way to do that purely just in javascript through the API ? 

Also if I have to change the video on the same element, do I have to remove the source, add in new source, then call fluidPlayer('#selector') again ???

**Comment by java168** [comment]
this looks like an answer to you.
Failed to play video. #234
https://github.com/fluid-player/fluid-player/issues/234#issuecomment-402101059

**Comment by Addvilz** [comment]
1. Sources can not be added programmatically except for manipulating DOM.
2. You need to recreate FluidPlayer instances, yes.
