### ISSUE TITLE
Hls is not defined error

### ISSUE THREAD

**Issue by kevin074** [fluid-player/fluid-player#263]
Hi I tried to use the library with 
```
<video id="video">
    <source src='https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8' type='application/x-mpegURL'/>
</video>
```
and in the corresponding JS file:
fluidPlayer('video')

and the console log gives this error:
Uncaught ReferenceError: Hls is not defined
    at Object.initialiseHls (fluidPlayer.js:1)

I am not sure what I am doing wrong, thought at first it might be CORS so I went to try a .m3u8 url from our domain but still got the same error. Am I doing something wrong and what does the error mean ?

**Comment by cian-exads** [comment]
Hi @kevin074, can you link me a test page where this is occurring?

**Comment by bharath-exads** [comment]
Hi,

HLS is playing fine in fluidplayer
https://docs.fluidplayer.com/streaming/

Please provide test page so we can debug
