### ISSUE TITLE
VAST not working

### ISSUE THREAD

**Issue by killown** [fluid-player/fluid-player#267]
I am using the following vast xml

    <VAST version="3.0">
    <Ad>
    <InLine>
    <AdSystem>Test</AdSystem>
    <AdTitle/>
    <Impression>
    <![CDATA[
    ]]>
    </Impression>
    <Error>
    <![CDATA[
    ]]>
    </Error>
    <Creatives>
    <Creative sequence="1">
    <Linear skipoffset="00:00:02">
    <Duration>00:00:15.0</Duration>
    <TrackingEvents>
    <Tracking event="progress" offset="00:00:10.000">
    <![CDATA[
    ]]>
    </Tracking>
    </TrackingEvents>
    <VideoClicks>
    <ClickThrough>
    <![CDATA[
    ]]>
    </ClickThrough>
    </VideoClicks>
    <MediaFiles>
    <MediaFile delivery="progressive" type="video/mp4">
    <![CDATA[
    https://mysite.com/pre-ad.mp4
    ]]>
    </MediaFile>
    </MediaFiles>
    <Icons>
    <Icon>
    <IconClicks>
    <IconClickThrough>mysite.com</IconClickThrough>
    </IconClicks>
    </Icon>
    </Icons>
    </Linear>
    </Creative>
    </Creatives>
    </InLine>
    </Ad>
    </VAST>
    
    
    
and to load the player

    var myScript = document.createElement('script');
    myScript.src = 'https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js';
    myScript.onload = function() {
    fluidPlayer(
       'player',
        {
            layoutControls: {
                primaryColor:           false,
                playButtonShowing:      true,
                playPauseAnimation:     true,
                fillToContainer:        false,
                autoPlay:               false,
                mute:                   false,
                keyboardControl:        true,
                layout:                 'default',
                allowDownload:          false,
                playbackRateEnabled:    true,
                allowTheatre:           false,
                controlBar: {
                    autoHide:           true,
                    autoHideTimeout:    3,
                    animated:           true
                },
                timelinePreview:        {},
                htmlOnPauseBlock: {
                    html:               null,
                    height:             null,
                    width:              null
                },
                vastOptions: {
                adList: [
                    {
                        roll: 'preRoll',
                        vastTag: 'https://mysite.com/vast.xml',
                        skipButtonCaption: 'Espere [seconds] segundo(s)',
                        vastTimeout:                5000
    
                    }
                ]
            },
    
                playerInitCallback:     (function() {})
            }
        }
    );
    
    
    };

    document.body.appendChild(myScript);

But the vast is not being loaded, no ads no preroll,

Can anybody help me?

**Comment by cradonn** [comment]
Can you provide your real VAST tag?

**Comment by cian-exads** [comment]
Hi @killown, I think this is occurring because your Fluid Player parameters are misplaced. The *vastOptions* should not be placed within the *layoutControls*. See below and update accordingly for your VAST file and let us know if this resolves your issue.

```fluidPlayer(
    'player',
    {
        layoutControls: {
            primaryColor:           false,
            playButtonShowing:      true,
            playPauseAnimation:     true,
            fillToContainer:        false,
            autoPlay:               false,
            mute:                   false,
            keyboardControl:        true,
            layout:                 'default',
            allowDownload:          false,
            playbackRateEnabled:    true,
            allowTheatre:           false,
            controlBar: {
                autoHide:           true,
                autoHideTimeout:    3,
                animated:           true
            },
            timelinePreview:        {},
            htmlOnPauseBlock: {
                html:               null,
                height:             null,
                width:              null
            },
            playerInitCallback:     (function() {})
        },
        vastOptions: {
            adList: [
                {
                    roll: 'preRoll',
                    vastTag: 'https://mysite.com/vast.xml',
                    skipButtonCaption: 'Espere [seconds] segundo(s)',
                    vastTimeout:                5000

                }
            ]
        }
    }
);
```

**Comment by killown** [comment]
> Hi @killown, I think this is occurring because your Fluid Player parameters are misplaced. The _vastOptions_ should not be placed within the _layoutControls_. See below and update accordingly for your VAST file and let us know if this resolves your issue.
> 
> ```
>     'player',
>     {
>         layoutControls: {
>             primaryColor:           false,
>             playButtonShowing:      true,
>             playPauseAnimation:     true,
>             fillToContainer:        false,
>             autoPlay:               false,
>             mute:                   false,
>             keyboardControl:        true,
>             layout:                 'default',
>             allowDownload:          false,
>             playbackRateEnabled:    true,
>             allowTheatre:           false,
>             controlBar: {
>                 autoHide:           true,
>                 autoHideTimeout:    3,
>                 animated:           true
>             },
>             timelinePreview:        {},
>             htmlOnPauseBlock: {
>                 html:               null,
>                 height:             null,
>                 width:              null
>             },
>             playerInitCallback:     (function() {})
>         },
>         vastOptions: {
>             adList: [
>                 {
>                     roll: 'preRoll',
>                     vastTag: 'https://mysite.com/vast.xml',
>                     skipButtonCaption: 'Espere [seconds] segundo(s)',
>                     vastTimeout:                5000
> 
>                 }
>             ]
>         }
>     }
> );
> ```

Thanks a lot I will try your code

**Comment by killown** [comment]
Sorry but still not working with the following, no pre roll is displayed in the videos
fluidPlayer(
   'player',
    {
        layoutControls: {
            primaryColor:           false,
            playButtonShowing:      true,
            playPauseAnimation:     true,
            fillToContainer:        false,
            autoPlay:               false,
            mute:                   false,
            keyboardControl:        true,
            layout:                 'default',
            allowDownload:          false,
            playbackRateEnabled:    true,
            allowTheatre:           false,
            logo: {
                imageUrl:           'https://www.mysite.com/wp-content/uploads/2018/08/twitter.png',
                position:           'top left',
                clickUrl:           'https://twitter.com/mysite',
                opacity:            1
            },
            controlBar: {
                autoHide:           true,
                autoHideTimeout:    3,
                animated:           true
            },
            timelinePreview:        {},
            htmlOnPauseBlock: {
                html:               null,
                height:             null,
                width:              null
            },


            playerInitCallback:     (function() {})
        },


        vastOptions: {
            adList: [
                {
                    roll: 'preRoll',
                    vastTag: 'https://media.mysite.com/vast.xml',
                    skipButtonCaption: 'Espere [seconds] segundo(s)',
                    vastTimeout:                5000

                }
            ]
        }




    }
);


};

**Comment by killown** [comment]
working now, issue with permissions, thanks a lot

**Comment by flozanoh** [comment]
Hello, I also want to display pre-roll, I have this code, but not pre-roll video is displaying:

```
<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>

                        <video id="video-id">
                            <source
                                src="https://xxxxxxxxx.b-cdn.net/xxxxxxxx/playlist.m3u8?v=xxxxxxxx"
                                type="application/x-mpegURL" />
                            <script>
                                var myFP = fluidPlayer(
                                    'video-id', {
                                    "layoutControls": {
                                        "controlBar": {
                                            "autoHideTimeout": 3,
                                            "animated": true,
                                            "autoHide": true
                                        },
                                        "htmlOnPauseBlock": {
                                            "html": null,
                                            "height": null,
                                            "width": null
                                        },
                                        "autoPlay": true,
                                        "mute": false,
                                        "allowTheatre": true,
                                        "playPauseAnimation": true,
                                        "playbackRateEnabled": true,
                                        "allowDownload": false,
                                        "playButtonShowing": true,
                                        "fillToContainer": true,
                                        "posterImage": ""
                                    },
                                    "vastOptions": {
                                        "adList": [
                                            {
                                                "roll": "preRoll",
                                                "vastTag": "https://pubads.g.doubleclick.net/gampad/ads?iu=/xxxxxxxx,xxxxxxxxxx/vast_player/myurl.com_vast_player&description_url=https%3A%2F%2Fmyurl.com&tfcd=0&npa=0&sz=1x1%7C300x250%7C400x300%7C640x360%7C640x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
                                                "adText": ""
                                            }
                                        ],
                                        "skipButtonCaption": 'Skip ad in [seconds]',
                                        "skipButtonClickCaption": 'Skip ad <span class="skip_button_icon"></span>',
                                        "adText": null,
                                        "adTextPosition": 'top left',
                                        "adCTAText": 'Visit now!',
                                        "adCTATextPosition": 'bottom right',
                                        "vastTimeout": 5000,
                                        "showPlayButton": false,
                                        // maxAllowedVastTagRedirects: 1,

                                        
                                    }
                                })
                            </script>
```
