### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by protechnology** [fluid-player/fluid-player#271]
Hi,

I have an issue with the latest version of fluid player.
I included the player on our website. There is a preroll video (managed with a proper VAST xml file). But on iOS the player goes into infinite loading when I click on the play-button.
On Android smartphones it works nicely.
When I check firebug I get the following error code in the console: 
```
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
(fluidplayer.min.js?ver=4.9.8:1)
```
Anybody who has an idea what the bugfix could be?
the URL for the website is [www.medienmanager.at](url)

Thanks a lot!
BR, George

**Comment by gibigate** [comment]
just update your IOS to latest version or safari to 11 version.
https://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

**Comment by protechnology** [comment]
Hi gibigate, Thanks for your fast answer! 
I tried it now with an iPhoneX+Safari11 but the problem is there too. But I have to admit, that I cannot access the console on that device.
Could there be any other solution for this?

**Comment by Addvilz** [comment]
To the best of my knowledge there is no fix to this - but I will add test code to check if this bug is present in the browser and bail if so detected.
