### ISSUE TITLE
Fluid-Player

### ISSUE THREAD

**Issue by AMGTech1** [fluid-player/fluid-player#280]
How can I add "Mute" to this code Please help me ?

[fluid-player-extended
layout="funky"
auto-play="autoPlay"
logo="https://www.fluidplayer.com/images/yourlogo.png"
logo-position="top right"
logo-opacity=".8"
ad-text="adText"
ad-cta-text="adCTAText"
html-on-pause-block-width="100"
html-on-pause-block-height="100"
responsive="responsive"]

[fluid-player-multi-res-video]
    [
        {"label": "720", "url": "http://cdn.fluidplayer.com/current/examples/video.mp4"},
        {"label": "360", "url": "http://cdn.fluidplayer.com/current/examples/video360.mp4"}
    ]
[/fluid-player-multi-res-video]

[fluid-player-html-block]
    <div>
        <img src="https://www.fluidplayer.com/images/yourbanner.png" />
    </div>
[/fluid-player-html-block]
[/fluid-player-extended]

**Comment by cian-exads** [comment]
Hi @AMGTech1, I don't believe the mute option is available for the WordPress version of Fluid Player. However I'd advise posting on the WordPress support board to get the answer from the plugin developer directly - https://wordpress.org/support/plugin/fluid-player

**Comment by Addvilz** [comment]
Not related to the player itself.

**Comment by Rog62** [comment]
How many fing times you going to send this crap???

**Comment by Addvilz** [comment]
@Rog62 you are subscribed to view **all changes** (as a watcher) to this repository. If you do not want to receive notifications about the updates to this repository, you should not subscribe to them. :)
