### ISSUE TITLE
Player hangs with VAST contains Wrapper and Creative sections

### ISSUE THREAD

**Issue by pavelkdev** [fluid-player/fluid-player#281]
If VAST code contains one or several VAST Wrapper sections - player works fine, and loads Wrapped VAST code.
If VAST code contains one or several Creative sections - player works fine, too, and loads preroll.
But if there is wrapper and creative section in one vast, player hangs, and does not responde to start button. Not even preroll, but video could not be played.

**Comment by bharath-exads** [comment]
Hi,

Can u please provide the VAST URL or Page link where u are experiencing this

**Comment by Addvilz** [comment]
No update since 2018, and we can't continue without examples. Please, reopen the issue if this is still a problem and provide some examples.
