### ISSUE TITLE
download video

### ISSUE THREAD

**Issue by krvam** [fluid-player/fluid-player#282]
Hi, what code do I have to edit or do so that the videos can be downloaded?

**Comment by cian-exads** [comment]
Hi @krvam, this will be by using the *allowDownload* parameter outlined here - https://docs.fluidplayer.com/layout_configuration/#allowdownload

**Comment by krvam** [comment]
Thank you cian.

**Comment by krvam** [comment]
i have this:
`{layoutControls:{mediaType:i.getCurrentSrcType(),primaryColor:!1,posterImage:!1,adProgressColor:"#f9d300",playButtonShowing:!0,playPauseAnimation:!0,closeButtonCaption:"Close",fillToContainer:!1,autoPlay:!1,mute:!1,loop:null,keyboardControl:!0,allowDownload:!1,`

Would you have to remove the "! 1" and place true?

**Comment by krvam** [comment]
Thanks, i  will prove it.
What I do not understand because the code that is in the documentation, is different from the one I have installed and because nowhere in the code does it appear true or false and it appears to me ! 0 -! 1

**Comment by krvam** [comment]
I modified it

 it works but badly. LOL
The icon appears to download the video, but when you press, you download another video and not the one you were watching.
Pass with all the videos always download the same

**Comment by cian-exads** [comment]
Can you link me a test page where I can see the behaviour? I'm not sure where the **!0** and **!1** settings came from, as nothing I've seen has had them.

**Comment by krvam** [comment]
Warning. the website is for adults. http pornvox .com 

I can if you want to pass all the code that I have of fluidplayer.min.js  you can view here : http://pasted.co/135ac403

**Comment by Addvilz** [comment]
@krvam not sure what the issue here is - seems like several issue reports mixed together? Can you provide more details? Thanks!

**Comment by Addvilz** [comment]
No feedback, closing.

**Comment by HoussyCH89** [comment]
please guys ... any one have guide mehtod on youtube or videos ..... i want to try but i i failed
