### ISSUE TITLE
Play Video by clicking only on Play button

### ISSUE THREAD

**Issue by kulvir97** [fluid-player/fluid-player#283]
Hello,

First of all, very thanks for the Fluid Player, it has lot of options, but I've a concern about video playing.

I want to play video only by clicking on Play button, not on the video. How can I do that?

Thanks

**Comment by gibigate** [comment]
https://github.com/fluid-player/fluid-player/blob/95a439f9db5a5d12e98ca008ed04d0017477e9cf/fluidplayer.js#L3282
`
document.getElementById(this.videoPlayerId).addEventListener(listenTo, function() {
    player.playPauseToggle(videoPlayerTag);
}, false);`
change to:
`
if(!fluidPlayerClass.isTouchDevice()) {
    document.getElementById(this.videoPlayerId).addEventListener(listenTo, function() {
        player.playPauseToggle(videoPlayerTag);
    }, false);
}
`

**Comment by krvam** [comment]
> open your fluidplayer.js and find this part:
> [fluid-player/fluidplayer.js](https://github.com/fluid-player/fluid-player/blob/95a439f9db5a5d12e98ca008ed04d0017477e9cf/fluidplayer.js#L3283-L3285)
> 
> Lines 3283 to 3285 in [95a439f](/fluid-player/fluid-player/commit/95a439f9db5a5d12e98ca008ed04d0017477e9cf)
> 
>  document.getElementById(this.videoPlayerId).addEventListener(listenTo, function() { 
>      player.playPauseToggle(videoPlayerTag); 
>  }, false); 
> 
> `
> If you want disable click only on touch devices, replace to:
> 
> ```
> if(!fluidPlayerClass.isTouchDevice()) {
>     document.getElementById(this.videoPlayerId).addEventListener(listenTo, function() {
>         player.playPauseToggle(videoPlayerTag);
>     }, false);
> }
> ```
> If you want disable for all devices, just delete listener

Thanks, i would try this !

**Comment by gibigate** [comment]
it will be work only when user click on play button icon in controlbar, not a big play icon at center of player

**Comment by rmilyushkevich** [comment]
You can configure it by config. See https://github.com/fluid-player/fluid-player/pull/326

**Comment by Addvilz** [comment]
I believe this issue is resolved in the latest versions. Please reopen if that is not correct.

**Comment by phansheng89** [comment]
> I believe this issue is resolved in the latest versions. Please reopen if that is not correct.

Any option to set this in new version?

**Comment by Addvilz** [comment]
> Any option to set this in new version?
What do you mean?

**Comment by phansheng89** [comment]
It said that the issue "Play Video by clicking only on Play button" is solved in new version, but I don't see any control options to set it.

Also, not really related but is there control to disable fullscreens button please?

**Comment by guyko** [comment]
raising this issue again. please assist?

**Comment by Kilixn** [comment]
The control option is still not available.
I tried pauseOnlyOnPause: true but it doesn't work.
Am I just too dumb for it or is it still not implemented ?

**Comment by puzonevan** [comment]
@Addvilz @kilixn @guyko if there's still interest, we should re open this issue. The PR that contains the fix never got merged in
