### ISSUE TITLE
Video won't play

### ISSUE THREAD

**Issue by Kreiny** [fluid-player/fluid-player#285]
Hi,

I'm visiting a site that uses Fluid Player 2.4.2 and when I click on the video nothing happens.

What info can I provide for someone to assist me?

Thanks

**Comment by cian-exads** [comment]
Hi @Kreiny, can you link the site in question and I'll take a look.

**Comment by Kreiny** [comment]
Hi,

It's NSFW......

https://www.youramateurporn.com/video/latin-wife-maria-riding-75854.html

**Comment by cian-exads** [comment]
That's no problem Kreiny. What device & browser are you using to play view this page?

**Comment by Kreiny** [comment]
I'm on a PC running Windows 10, with a NVIDIA GeForce GTX 1060 6GB graphics card and using Firefox Quantum 62.0.3. But I also have the issue if it try Google Chrome 69.0.3497.100.

**Comment by Kreiny** [comment]
Bump.

**Comment by Kreiny** [comment]
bump

**Comment by cradonn** [comment]
Cant reproduce on FF 64.0 / Chrome 71.0.3578.98.

Anything useful in either browser console?

**Comment by Addvilz** [comment]
Most likely related to #225
