### ISSUE TITLE
Stop caching the stream

### ISSUE THREAD

**Issue by anme98** [fluid-player/fluid-player#291]
Hello,

I have a problem with the streaming function in the latest player version:
**The player is caching the full livestream and after i.e. 1 hour the user is able to rewind the full stream**.
I couldn't find an option to turn it off or to limit the rewind.
Is it possible somehow or is it not implemented yet?

Thanks a lot!

BR: anme98

**Comment by DaYYY** [comment]
If it helps, inside of the fluid player object there is an hlsPlayer object that has methods that could stop streaming. You can read more about it in docs to hls.js library

**Comment by Addvilz** [comment]
This is indeed controlled by HLS/DASH. V3 has api objects to interact with those.
