### ISSUE TITLE
FLV

### ISSUE THREAD

**Issue by ShpendBerisha** [fluid-player/fluid-player#292]
Hi, I don't belive that FLV will be around much longer but there are many webmasters using old affiliate systems. I was looking around and I found a known source called flv.js, is there any way or possibility to integrate a similar script into your javascript file? Would be great to have this without using flash, like all other media types described in your documentation page. For example m3u8 and mdp work perfect except a small thing maybe its an issue of my browser because on my macbook/safari hls video doesn't play but on my iphone and other other browsers, yes.

**Comment by Addvilz** [comment]
Is this still an issue?

**Comment by Addvilz** [comment]
This seems outdated. Closing.
