### ISSUE TITLE
only VAST as preRoll

### ISSUE THREAD

**Issue by pixprod** [fluid-player/fluid-player#294]
Hi there, at first I'd like to thank you for this great player :) 

I'm still experiment with the VAST files and like to setup only one(!) VAST file and repeat these if the ad is at the end. Is this possible??

I've tried reinit the player with myFP.play() in vastVideoEndedCallback or try to destroy and rebuild the player - but none of these approaches does work 👎 

Can you help or give me some advice how to replay the preroll or rebuild the player??? Thanks!!!

**Comment by cradonn** [comment]
Hi @pixprod,

If I understand your questions correctly you are looking for something like pre/mid/post roll while reusing the same VAST file?

If so take a look at https://docs.fluidplayer.com/ad_configuration/#adlist
```json
fluidPlayer(
   'my-video',
    {
        vastOptions: {
            adList: [
                {
                    roll: 'preRoll',
                    vastTag: 'vastPreRoll.xml',
                    adText: 'Advertising supports us directly'
                },
                {
                    roll: 'midRoll',
                    vastTag: 'vastMidRoll.xml',
                    timer: 8
                },
                {
                    roll: 'midRoll',
                    vastTag: 'vastMidRoll2.xml',
                    timer: 10,
                    adClickable: false // Default true
                },
                {
                    roll: 'postRoll',
                    vastTag: 'vastPostRoll.xml',
                    adText: 'Thanks for watching',
                    adTextPosition: 'top right'
                }
            ]
        }
    }
);
```

**Comment by pixprod** [comment]
@cradonn: thanks for your quick response!! In principle i'd like to reuse the same VAST file for pre/mid/post roll or just use a pre roll => is this possible or did i understand the logic behind VAST wrong?

After setting the same VAST for all rolls (or just setting the preroll) the video plays and after the first loop of the video, the play button is striked through and i can't restart the player without reloading the site. 

What am i doing wrong? Thanks for your help :)

```
<video [divi_php] if($fluid_config_autoplay==='on'){echo'autoplay="true" muted="true"';}else{echo'autoplay="false"';} [/divi_php] id='fp-video-0' controls loop>
<source type='video/mp4' title="">
</video>

<script type="text/javascript">

var fluidPlayerPlugin0 = function() {
    var myFP = fluidPlayer(
        'fp-video-0',
            {
            layoutControls: {
                    fillToContainer: true,
                    posterImage: '%%fluid_config_poster_image%%',
                    autoPlay: [divi_php] if($fluid_config_autoplay==='on'){echo'true';}else{echo'false';} [/divi_php],
                    playButtonShowing: true,
                    playPauseAnimation: true,
                    mute: [divi_php] if($fluid_config_mute==='on'){echo'true';}else{echo'false';} [/divi_php],
                logo: {
                    imageUrl: '%%fluid_config_logo%%',
                    position: 'top left',
                    clickUrl: '%%fluid_config_logo_link%%',
                    opacity: 1,
                    mouseOverImageUrl: null,
                    imageMargin: '2px',
                    hideWithControls: false,
                    showOverAds: false
                },
                htmlOnPauseBlock: {
                    html: '<div style="background: #FFF; color: #000; padding: 5px; text-align: center">%%fluid_config_ad_text_on_pause%%',
                    height: 100,
                    width: 200
                },
                allowDownload: false,
                allowTheatre: true,
                playbackRateEnabled: false,
                controlBar: {
                    autoHide: false,
                    autoHideTimeout: 3,
                    animated: true
                },
            },
            vastOptions: {
                // To implement ads see http://docs.fluidplayer.com/ad_configuration/
                adList: [
                {
                    roll: 'preRoll',
                    vastTag: '%%fluid_file_vast%%',
                    adClickable: false, // Default true
                },
                {
                    roll: 'midRoll',
                    vastTag: '%%fluid_file_vast%%',
                    adClickable: false, // Default true
                    timer: 8,
                },
                {
                    roll: 'postRoll',
                    vastTag: '%%fluid_file_vast%%',
                    adClickable: false, // Default true
                }
                ],
                    adText: '%%fluid_config_ad_text%%',
                    adTextPosition: 'top left',
                    adCTAText: '%%fluid_config_ad_cta_text%%',
                    adCTATextPosition: 'bottom right',
                    vastTimeout: %%fluid_config_vast_timeout%%,
                    maxAllowedVastTagRedirects: 1,
                    vastAdvanced: {
                        vastLoadedCallback:       (function() {}),
                        noVastVideoCallback:      (function() {}),
                        vastVideoSkippedCallback: (function() {}),
                        vastVideoEndedCallback:   (function() {})
                    }
                }
            }
        );
};

(function defer() {
    if (typeof(fluidPlayer) != 'undefined') {
        fluidPlayerPlugin0();
    } else {
        setTimeout(defer, 50);
    }
})();

</script>
```

**Comment by golikov** [comment]
From what I understand the intention is to play ONLY the ad from VAST tag in loop.
So no actual non-ad video content is there. This is not a standard fluid-player use case.
The problem is that ads do not get repeated because of loop attribute (not supported) and that alternatively there is no way provided to destroy and recreate the player instance to be able to play over.

Something like this would work:
            <video id='fp-video-0' autoplay="true" muted="true" controls loop>
                <source type='video/mp4' title="">
            </video>

            <script type="text/javascript">
                var playerId = 'fp-video-0';
                var options = {
                    layoutControls: {
                        fillToContainer: true,
                         //posterImage: '%%fluid_config_poster_image%%',
                         autoPlay: true,
                         playButtonShowing: true,
                         playPauseAnimation: true,
                         mute: true,
                         playbackRateEnabled: false,
                          controlBar: {
                              autoHide: false,
                              autoHideTimeout: 3,
                              animated: true
                          }
                    },
                    vastOptions: {
                        // To implement ads see http://docs.fluidplayer.com/ad_configuration/
                        adList: [
                            {
                                roll: 'preRoll',
                                vastTag: '%%fluid_file_vast%%',
                                adClickable: false // Default true
                            }
                        ],
                            adText: '%%fluid_config_ad_text%%',
                            adTextPosition: 'top left',
                            adCTAText: '%%fluid_config_ad_cta_text%%',
                            adCTATextPosition: 'bottom right',
                            //vastTimeout: %%fluid_config_vast_timeout%%,
                            maxAllowedVastTagRedirects: 1,
                            vastAdvanced: {
                            vastLoadedCallback: (function () {
                            }),
                            noVastVideoCallback: (function () {
                            }),
                            vastVideoSkippedCallback: (function () {
                                setTimeout(function() {fpDestroy(playerId); fluidPlayerPlugin0();}, 1000);
                            }),
                            vastVideoEndedCallback: (function () {
                                setTimeout(function() {fpDestroy(playerId); fluidPlayerPlugin0 ();}, 1000);
                            })
                        }
                    }
                };

                var fpDestroy = function(idVideoPlayer) {
                    for (var i = 0; i < fluidPlayerClass.instances.length; i++) {
                        if (fluidPlayerClass.instances[i].videoPlayerId === idVideoPlayer) {
                            var videoWrapper = document.getElementById('fluid_video_wrapper_' + idVideoPlayer);
                            var oldPlayer = document.getElementById(idVideoPlayer);
                            var newPlayer = oldPlayer.cloneNode(true);
                            videoWrapper.innerHTML = '';
                            newPlayer.removeAttribute('src');
                            videoWrapper.parentNode.replaceChild(newPlayer, videoWrapper);
                            videoWrapper = null;
                            oldPlayer = null;

                            //Kill instance
                            fluidPlayerClass.instances[i] = {videoPlayerId: '83748374hjkehwkfjrweqh8724983278983k'};

                            break;
                        }
                    }
                };

                var fluidPlayerPlugin0 = function() {
                     var myFP = fluidPlayer(
                        playerId,
                        options
                     );
                };

                (function defer() {
                    if (typeof(fluidPlayer) != 'undefined') {
                        fluidPlayerPlugin0();
                    } else {
                        setTimeout(defer, 50);
                    }
                })();


            </script>


We will look into implementing the detroy/re-init capabilities properly in the upcoming releases

**Comment by pixprod** [comment]
@cradonn : thanks for your snippet!!! I'll will try your workaround, to get a more solid best practise.

Maybe these little quick&dirty solution will help another?!

vastAdvanced: {
                        vastLoadedCallback:       (function() {
                            // puffer video source
                            videoVAST = jQuery('#fp-video-0').attr('src');
                        }),
                        noVastVideoCallback:      (function() {
                            //console.log('noVastVideoCallback');
                        }),
                        vastVideoSkippedCallback: (function() {
                            //console.log('vastVideoSkippedCallback');
                        }),
                        vastVideoEndedCallback:   (function() {
                            // set video source to player
                            jQuery('#fp-video-0').attr('src', videoVAST);
                            // avoid autoplay > DOM ready
                            setTimeout(function(){
                                jQuery('#fp-video-0').trigger('pause');
                            },1000);
                            
                        })
                    }

**Comment by Paultelper** [comment]
> From what I understand the intention is to play ONLY the ad from VAST tag in loop. So no actual non-ad video content is there. This is not a standard fluid-player use case. The problem is that ads do not get repeated because of loop attribute (not supported) and that alternatively there is no way provided to destroy and recreate the player instance to be able to play over.

> We will look into implementing the detroy/re-init capabilities properly in the upcoming releases

Hey there, it this feature included at the moment? I have the same issue, would like to add just looping VAST ad to the player
