### ISSUE TITLE
Only one player per site.

### ISSUE THREAD

**Issue by GoldenHandyMan** [fluid-player/fluid-player#296]
I want to add more than one video running in Fluid Player. I'm giving them same id in <video> tag but only first one is playing in fluid. Any idea how to help with it?

**Comment by bharath-exads** [comment]
Hi,

Fluidplayer supports adding more than one player on the same page
Giving the same ID for more than one element is not recommended, please provide a unique id for each of player

Please find the sample code, hope this will help
https://codepen.io/bharath-exads/pen/zVLzyM
