### ISSUE TITLE
Loading Circle After Vast Video?

### ISSUE THREAD

**Issue by isjunked** [fluid-player/fluid-player#297]
Hello,

Is there any way to have the loading circle running after in-video preroll VAST? Video need time to load after VAST but there is no loading circle, so some of my viewers think the video is not working so they bounce away.

**Comment by det66** [comment]
This is a good idea. I am having the same problem.

**Comment by det66** [comment]
Even when there is no VAST pre-roll in-stream it should be shown...

**Comment by isjunked** [comment]
Yes I think we should add a loading indicator when press playing button and after vast.

**Comment by HariPriyaKuberSingh** [comment]
@isjunked  - Hi . Can you please confirm if the issue still persist ? Or can I go ahead and close the ticket

**Comment by HariPriyaKuberSingh** [comment]
@isjunked  - Can you please confirm if the issues still persist ?

**Comment by HariPriyaKuberSingh** [comment]
Since there is no confirmation from the reporter regarding the issue, we are closing the ticket
