### ISSUE TITLE
Adding "Endcard" option

### ISSUE THREAD

**Issue by sevildevil1990** [fluid-player/fluid-player#299]
Hi,
for an upcoming project I needed a way to add an endcard to certain videos. 

Since it's basically "just the pause screen, but at the end of the video", I already did some tinkering around in the code and implemented it like this:
```
        player.displayOptions = {
[...]
                htmlOnCompleteBlock: {
                    html:                     null,
                    height:                   null,
                    width:                    null
                },
[...]
        }
```

If approved by the staff, I would like to make a pull request, however there is still one issue I would like to have resolved before the changes hit the production code:
If you are on the endscreen and seek right back into the video, the screen won't switch back to a regular pause screen.

So somehow there would need to be a check, whether after a seek event the player is still paused and which of the two overlays is currently displayed. If somebody could point me to the right position in the code, that would be awesome.

For reference, the changed files:
* https://github.com/sevildevil1990/fluid-player/blob/master/fluidplayer.js
* https://github.com/sevildevil1990/fluid-player/blob/master/fluidplayer.css

On a sidenote: There is also a weird quirk, that interferes with the endcard, that is in the base player right now:
If a Post-Roll is played, the video-player skips back to the first position in the video, thus never reaching the point of triggering the end screen.

**Comment by trinidadr** [comment]
Just what I'm looking to do :)  Great suggestion. Now if we could get some traction here...

**Comment by HariPriyaKuberSingh** [comment]
@sevildevil1990 -  Can you please confirm if the issue still persist ? Or can I go ahead and close the ticket

**Comment by HariPriyaKuberSingh** [comment]
@sevildevil1990 - Can you please confirm if the issue still persist ?

**Comment by HariPriyaKuberSingh** [comment]
Since there is no confirmation from the reporter regarding the issue, we are closing the ticket
