### ISSUE TITLE
VAST not playing before video

### ISSUE THREAD

**Issue by cristcdl** [fluid-player/fluid-player#301]
I have fluid player setup and everything is working except the vast code and ad.  Here is my code, did xml vailidation for the xml file and everything was able to play the ad except fluid player.

<script><br>
    var myFP = fluidPlayer(<br>
        'engine-compartment',<br>
        {<br>
            layoutControls: {<br>
		fillToContainer: false,<br>
		primaryColor: "#EE0000",<br>
		posterImage: false,<br>
		autoPlay: false,<br>
		keyboardControl: false,<br>
		playButtonShowing: true,<br>
		playPauseAnimation: true,<br>
		mute: false,<br>
		logo: {<br>
			imageUrl: null,<br>
			position: 'top left',<br>
			clickUrl: null,<br>
			opacity: 1,<br>
			mouseOverImageUrl: null,<br>
			imageMargin: '2px',<br>
			hideWithControls: false,<br>
			showOverAds: false<br>
		},<br>
		htmlOnPauseBlock: {<br>
			html: null,<br>
			height: null,<br>
			width: null<br>
		},<br>
		allowDownload: false,<br>
		allowTheatre: false,<br>
		playbackRateEnabled: false,<br>
		controlBar: {<br>
			autoHide: true,<br>
			autoHideTimeout: 3,<br>
			animated: true<br>
		},<br>
            },<br>
            vastOptions: {<br>
		    showProgressbarMarkers: 'true',<br>
	            adList: [<br>
        	        {<br>
               	        roll: 'preRoll',<br>
                    	vastTag: 'https://secure.adnxs.com/ptv?id=14775181&vmaxduration=10&vskippable=1&vplaybackmethod=3&vwidth=320&vheight=240&vcontext=1&vframeworks=1,2&vv=2&referrer=cristcdl.com'<br>
                	}<br>
		    ]<br>
            }<br>
        }<br>

    );<br>

</script><br><br>

Please help.

**Comment by bharath-exads** [comment]
Hi,

your Vast URL 'https://secure.adnxs.com/ptv?id=14775181&vmaxduration=10&vskippable=1&vplaybackmethod=3&vwidth=320&vheight=240&vcontext=1&vframeworks=1,2&vv=2&referrer=cristcdl.com' is empty
