### ISSUE TITLE
How to use Fluid Player for interstitial ads

### ISSUE THREAD

**Issue by maxlanders** [fluid-player/fluid-player#307]
Basically it would involve not to have a source tag for the video tag.
Another option might be using some javascript to edit the source url but then the video would play a second time? Not sure what is best.

**Comment by Addvilz** [comment]
Can you provide more details regarding the issue you are facing specifically? What do you mean by "it would involve not to have a source tag for the video tag"?

**Comment by maxlanders** [comment]
Hello,
It was 1 year ago and to be honest I don't remember exactly what was the issue. However, we don't have any problem regarding this topic so I'm closing it. Thanks
