### ISSUE TITLE
Pre-roll in-stream video ads are not skippable at all in UC browser (mobile)

### ISSUE THREAD

**Issue by det66** [fluid-player/fluid-player#308]
pre-roll in-stream video ad that is not skippable at all in UC browser

:warning: NSFW screenshot:
https://user-images.githubusercontent.com/37077443/52162056-9a93b280-26ce-11e9-985c-716ab6b9898c.jpg

**Comment by det66** [comment]
Advertisement text is also not shown

**Comment by pinker13** [comment]
https://github.com/fluid-player/fluid-player/issues/308#issuecomment-459947584

**Comment by Addvilz** [comment]
Please, do not embed NSFW screenshots on GitHub issue tracker. Either reproduce SFW content, or link external screenshot with appropriate warning.

**Comment by Addvilz** [comment]
Please upgrade to V3 and see if that helps. If not, reopen this issue.
