### ISSUE TITLE
Video won't play after video quality is changed [202]

### ISSUE THREAD

**Issue by tariktuzlakovic** [fluid-player/fluid-player#309]
Hi there, I'm so far getting my feature in order with your video player, but I'm stuck on changing the video quality. 

**Problem**

When I change the quality of the (running and working!) video, my source for video (as I inspected HTML) updates to an ugly URL which is combined of my localhost URL + my component (as I'm using **Vue** in this whole process) + `function%20String()%20%7B%20[native%20code]%20%7D` this chunk of code. Additionally, as I click on the 'Play' button I get `[Error] (202): Failed to play video.`

**Expected behavior**

I'm expecting as I change the video quality, let's say from 720p to 360p, to load my video again, adding a source of my 360p video, to my video element which I specified. 

**Question**

Is there a hook exposed which triggers as I change the video quality so I can track what actually happens as soon as I change the video quality? Or better yet: is there a clear solution for this so I don't go running through hooks and "manually" changing the video source?

**Comment by bharath-exads** [comment]
Hi,

Is it possible to share the link where u are experiencing this

**Comment by Addvilz** [comment]
Can not reproduce with local vue setup. Please reopen if you can produce reproduce code.
