### ISSUE TITLE
VAST and HLS Stopped working

### ISSUE THREAD

**Issue by ggalloway1205** [fluid-player/fluid-player#310]
Everything was working fine and then one day none of it was working anymore.

Here is the player code I'm using.

`<link rel="stylesheet" href="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.css" type="text/css"/>
<script src="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js"></script>

<video id='video-id'>
	<source src='https://player.vimeo.com/external/19507195.m3u8?s=2c9ef647d3da2d8125d6f3fa55da00c3e2d8b8de' type='video/mp4' />
</video>

<script>
    var myFP = fluidPlayer(
        'video-id',
        {
            layoutControls: {
		fillToContainer: true,
		primaryColor: false,
		posterImage: false,
		autoPlay: true,
		playButtonShowing: true,
		playPauseAnimation: true,
		mute: false,
		logo: {
			imageUrl: 'https://2-gtv.com/wp-content/uploads/2018/09/2-gtv-400x90-Logo.png',
			position: 'top left',
			clickUrl: null,
			opacity: 0.6,
			mouseOverImageUrl: null,
			imageMargin: '2px',
			hideWithControls: false,
			showOverAds: false
		},
		htmlOnPauseBlock: {
			html: null,
			height: null,
			width: null
		},
		allowDownload: false,
		allowTheatre: false,
		playbackRateEnabled: true,
		controlBar: {
			autoHide: true,
			autoHideTimeout: 3,
			animated: true
		},
            },

		vastOptions: {
            adList: [
                {
                    roll: 'preRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    adText: 'Advertisement'
                },
                {
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 300,
					adText: 'Advertisement'
                },
				{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 600,
					adText: 'Advertisement',
                },
                {
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 600,
					adText: 'Advertisement',
                    adClickable: false // Default true
                },
			{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 900,
				adText: 'Advertisement'
                },
				{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 1200,
					adText: 'Advertisement'
                },
                {
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 1500,
					adText: 'Advertisement',
                    adClickable: false // Default true
                },
			{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 1800,
					adText: 'Advertisement'
                },
				{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 2100,
					adText: 'Advertisement'
                },
                {
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 2400,
					adText: 'Advertisement',
                    adClickable: false // Default true
                },
			{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 2700,
					adText: 'Advertisement'
                },
				{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 3000,
					adText: 'Advertisement'
                },
                {
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 3300,
					adText: 'Advertisement',
                    adClickable: false // Default true
                },
			{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 3600,
					adText: 'Advertisement'
                },
				{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 3900,
					adText: 'Advertisement'
                },
                {
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 4200,
					adText: 'Advertisement',
                    adClickable: false // Default true
                },
			{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 4500,
					adText: 'Advertisement'
                },
				{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 4800,
					adText: 'Advertisement'
                },
			{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 5100,
					adText: 'Advertisement'
                },
				{
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 5400,
					adText: 'Advertisement'
                },
                {
                    roll: 'midRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    timer: 5700,
					adText: 'Advertisement',
                    adClickable: false // Default true
                },
                {
                    roll: 'postRoll',
                    vastTag: 'http://shadow01.yumenetworks.com/dynamic_preroll_playlist.vast2xml?domain=1552hCkaKYjg',
                    adText: 'Thanks for watching',
                    adTextPosition: 'top right'
                }
            ]
        }
    }
);
</script>	`

**Comment by bharath-exads** [comment]
Hi,

there are inline comment **" // Default true"**  which is causing error in ur JSON.
