### ISSUE TITLE
Vertical Video Issue

### ISSUE THREAD

**Issue by ZiggyMaster** [fluid-player/fluid-player#312]
MY ALL VIDEOS ARE  width 320, height 568 (VERTICAL)

I want to Set all videos to expand to 100% of their containers. Enabling this will ignore any other width settings and set the width of the video to the width of the container it's in.
Default Width: 
640
 Height: 
360

I want to Constrain Vertical videos to default aspect ratio. 

But I can't do. Please, somebody help me do this.

Create a sample code via: 

[fluid-player-extended
    vast_file="vast.xml"
    layout="default"

    auto-play="true"
    allow-download="true"
    playback-speed-control="true"
    poster-image="https://www.fluidplayer.com/images/valerian-thumbnail.jpg"

    logo="https://www.fluidplayer.com/images/yourlogo.png"
    logo-position="top right"
    logo-opacity=".8"
    logo-hyperlink="https://www.fluidplayer.com/"

    ad-text="adText"
    ad-cta-text="adCTAText"

    html-on-pause-block-width="100"
    html-on-pause-block-height="100"

    responsive="true"]

    [fluid-player-multi-res-video]
        [
            {"label": "720", "url": "https://cdn.fluidplayer.com/videos/valerian-720p.mkv"},
            {"label": "480", "url": "https://cdn.fluidplayer.com/videos/valerian-480p.mkv"}
        ]
    [/fluid-player-multi-res-video]

    [fluid-player-html-block]
        <div>
            <img src="https://www.fluidplayer.com/images/sample-banner.png" />
        </div>
    [/fluid-player-html-block]

[/fluid-player-extended]

How can I add Vertical Videos into this Code?
How can Constrain Vertical videos to default aspect ratio?
Because when I add a 568x320 video, it opens on a page 3 times the size of the Video Player.

HELP ME!

**Comment by bharath-exads** [comment]
Hi,

You can pass CSS property **object-fit: fill** to the player, then the **video view will occupy full height and width of player**

have created an example in codepen 'https://codepen.io/bharath-exads/pen/Bgdjer' please check and let me know if this helps
