### ISSUE TITLE
You can change that picture into a serrated

### ISSUE THREAD

**Issue by CHADISTIL** [fluid-player/fluid-player#313]
![screenshot 83](https://user-images.githubusercontent.com/45186528/53305058-f2ac7780-387c-11e9-88ae-48e9e1837b4c.png)
@cradonn

**Comment by golikov** [comment]
If you want to customize the look and feel you can add your own custom css.
How to do it was outlined in the documentation: https://docs.fluidplayer.com/layout_configuration/#custom-icons-style
