### ISSUE TITLE
DOM element

### ISSUE THREAD

**Issue by doublex** [fluid-player/fluid-player#314]
Could you support init the player from a dom-node? This would help us integrate fluid-player in a UI library.

E.g. this pseudo code:
```javascript
document.querySelectorAll( '[data-video]' ).forEach( function( video )
{
    fluidPlayer( video, ... );
})
```

Possible fix:
```javascript
var videoPlayer = typeof(idVideoPlayer) == 'string' ? document.getElementById(idVideoPlayer) : idVideoPlayer;
```

**Comment by Addvilz** [comment]
Will be fixed in V3

**Comment by doublex** [comment]
Great news

**Comment by doublex** [comment]
Do you have a v3 demo somewhere online?

**Comment by Addvilz** [comment]
@doublex we are in process of release. The docs will be updated very soon!

**Comment by doublex** [comment]
What's great on fluid-player: It is lightweight
