### ISSUE TITLE
Pause function not working (API) right after video is started

### ISSUE THREAD

**Issue by det66** [fluid-player/fluid-player#315]
Pause function is not working when video is loading/buffering.
I am trying the following:

myVideo.on('play', function() {
				if(playfromad == false){
					myVideo.pause();
					$("#body_overlay").remove(); .... etc.

The video doesn't pause after Play button is pressed.

**Comment by Addvilz** [comment]
I am sorry but there are not enough details to work on here. Browsers have rules about programatic control of the video. You can't just play/pause it as you wish. This is most likely what is happening here.
