### ISSUE TITLE
Firefox onplay / onpause "select all" on page

### ISSUE THREAD

**Issue by trinidadr** [fluid-player/fluid-player#318]
I'm having an issue on where on Firefox, click on play or pause while slightly moving the mouse (or just after moving the mouse) the whole page gets selected. Tested on multiple FF installs, same result. Tested on other browsers and it works fine. 
Not sure if related, but on mobile, scrolling through video also triggers play/pause. Something about that "play" / "pause" is causing this odd behavior.

**Comment by trinidadr** [comment]
This also happens on your main site:
https://www.fluidplayer.com/

**Comment by Addvilz** [comment]
I am sorry, but I can't reproduce this - I am doing most of development and testing of the player of Firefox, and have never observed this behavior. Can you re-test and tell me if it is still happening?

**Comment by Addvilz** [comment]
Tried some more to reproduce and was not able to. Feel free to add more details if this is still an issue and you can provide more details on how to reproduce the issue.
