### ISSUE TITLE
The player has stopped working completely, please reform

### ISSUE THREAD

**Issue by CHADISTIL** [fluid-player/fluid-player#321]

**Comment by bharath-exads** [comment]
Hi,

Can u please share more info or link where u are experiencing this

**Comment by CHADISTIL** [comment]
It happened from time ago, and it was only temporary, thank you for your
efforts

‫في الثلاثاء، 23 يوليو 2019 في 11:40 ص تمت كتابة ما يلي بواسطة ‪bharath‬‏ <‪
notifications@github.com‬‏>:‬
