### ISSUE TITLE
How to prevent the player from downloading the source file.

### ISSUE THREAD

**Issue by esmondgh** [fluid-player/fluid-player#322]
I have five players in one page and when I open the page, all five players start downloading the source files. Is there a way I can prevent the player from downloading the source file till I click the play button?.

**Comment by rmilyushkevich** [comment]
Try to add controlsList="nodownload"

```
<video width="512" height="380" controls controlsList="nodownload">
    <source data-src="mov_bbb.ogg" type="video/mp4">
</video>
```

**Comment by rmilyushkevich** [comment]
All options of the controlsList attr here: https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist

**Comment by bharath-exads** [comment]
@esmondgh 

Let us know if this solution worked.
