### ISSUE TITLE
Need hls quality switcher and language

### ISSUE THREAD

**Issue by atmovies** [fluid-player/fluid-player#327]
hello there,
i can not switch my videos in other quality if the video is in hls or m3u8 format and also add language switch button .
my test link of fluid player-- https://bhmovies.in/fluidhls.html

**Comment by rmilyushkevich** [comment]
Hi

Can you try to add sources for each quality

Like this:

`<source src="playlist1080.m3u8" title="1080p" type="application/x-mpegURL">
<source src="playlist720.m3u8" title="720p" type="application/x-mpegURL">
<source src="playlist480.m3u8" title="480p" type="application/x-mpegURL">`

**Comment by bhmtech** [comment]
hello why we have to use  like this it makes code more harder 

<source src="playlist1080.m3u8" title="1080p" type="application/x-mpegURL">
<source src="playlist720.m3u8" title="720p" type="application/x-mpegURL">
<source src="playlist480.m3u8" title="480p" type="application/x-mpegURL">
