### ISSUE TITLE
Fluid player

### ISSUE THREAD

**Issue by gdulli111** [fluid-player/fluid-player#328]
HI i recently came across the fluid player and start using on my website, is there option for overlay banner ads while video is player and lastly is there option to display live video status on the control when playing a life stream 

thanks

**Comment by lain0** [comment]
do you use banners from VAST ?

**Comment by bharath-exads** [comment]
HI,

To display the banner on the video player, please check our sample
https://docs.fluidplayer.com/ad_configuration/
