### ISSUE TITLE
Pause other videos while playing one, on page with multiple videos

### ISSUE THREAD

**Issue by durgeshksh1** [fluid-player/fluid-player#329]
Hello,
First I want to thank you for such a simple and effective player.

I am having an issue while playing video on a page where multiple videos are embedded. All videos can play at a time, which is not desirable. If one video is playing and I click play on other one, both are playing simultaneously.
I tried to control it by API, it is working but with one issue, the play button keep blinking infinitely.

the full code is as below:

`<!doctype html>
<html lang="en">
   <head>
      <title>Fluid Player</title>
      <link rel="stylesheet" href="http://localhost/fluid_player/fluidplayer.min.css" type="text/css"/>
   </head>

   <body><br> <hr>
      <video id='my-video1' controls style="width: 400px; height: 200px;">
         <source src='http://localhost/vid/intro/planet_360.m3u8' title='360p' type='application/x-mpegURL' />
         <source src='http://localhost/vid/intro/planet_480.m3u8' title='480p' type='application/x-mpegURL' />
         <source data-fluid-hd src='http://localhost/vid/intro/planet_720.m3u8' title='720p' type='application/x-mpegURL' />
         <source data-fluid-hd src='http://localhost/vid/intro/planet_1080.m3u8' title='1080p' type='application/x-mpegURL' />
      </video> <br> <hr>

      <video id='my-video2' controls style="width: 400px; height: 200px;">
         <source src='http://localhost/vid/panasonic/Panasonic_360.m3u8' title='360p' type='application/x-mpegURL' />
         <source src='http://localhost/vid/panasonic/Panasonic_360.m3u8' title='480p' type='application/x-mpegURL' />
         <source data-fluid-hd src='http://localhost/vid/panasonic/Panasonic_360.m3u8' title='720p' type='application/x-mpegURL' />
         <source data-fluid-hd src='http://localhost/vid/panasonic/Panasonic_360.m3u8' title='1080p' type='application/x-mpegURL' />
      </video> <br> <hr>

      <video id='my-video3' controls style="width: 400px; height: 200px;">
         <source src='http://localhost/vid/test/bigBuck_480.m3u8' title='360p' type='application/x-mpegURL' />
      </video><br> <hr>
      
      
      <script src="http://localhost/fluid_player/fluidplayer.js"></script>

      <script type="text/javascript">
      var myFluidPlayer1 = fluidPlayer('my-video1',
            {
               layoutControls: {
                  primaryColor: "#28B8ED",
                  playbackRateEnabled: true,
               }
            }
         );

         var myFluidPlayer2 = fluidPlayer('my-video2',
            {
               layoutControls: {
                  primaryColor: "#28B8ED",
                  playbackRateEnabled: true,
               }
            }
         );

         var myFluidPlayer3 = fluidPlayer('my-video3',
            {
               layoutControls: {
                  primaryColor: "#28B8ED",
                  playbackRateEnabled: true,
               }
            }
         );

         myFluidPlayer1.on('play', function(){
            console.log('Video 1 is playing');
            myFluidPlayer2.pause();
            console.log('Video 2 is paused');
            myFluidPlayer3.pause();
            console.log('Video 3 is paused');
         });

         myFluidPlayer2.on('play', function(){
            console.log('Video 2 is playing');
            myFluidPlayer1.pause();
            console.log('Video 1 is paused');
            myFluidPlayer3.pause();
            console.log('Video 3 is paused');
         });

         myFluidPlayer3.on('play', function(){
            console.log('Video 3 is playing');
            myFluidPlayer1.pause();
            console.log('Video 1 is paused');
            myFluidPlayer2.pause();
            console.log('Video 2 is paused');
         });
      </script>
   </body>
</html>`.

I do not have any live page to demonstrate the issue. Kindly help

**Comment by durgeshksh1** [comment]
@rmilyushkevich 
I feel your fix did not solve the issue, still multiple videos are playing.
I fixed this issue by adding following lines of code.

`            var vid1 = document.getElementById('my-video1');
            var vid2 = document.getElementById('my-video2');
            var vid3 = document.getElementById('my-video3');

            var plyng1 = false;
            var plyng2 = false;
            var plyng3 = false;

            vid1.addEventListener("playing", function(){
               plyng1 = true;
            });
            vid1.addEventListener("pause", function(){
               plyng1 = false;
               // console.log('Video 1 is paused', plyng1);
            });

            vid2.addEventListener("playing", function(){
               plyng2 = true;
            });
            vid2.addEventListener("pause", function(){
               plyng2 = false;
               // console.log('Video 2 is paused', plyng2);
            });

            vid3.addEventListener("playing", function(){
               plyng3 = true;
            });
            vid3.addEventListener("pause", function(){
               plyng3 = false;
               // console.log('Video 3 is paused', plyng3);
            });

         vid1.onplay=function(){
            // console.log(plyng2, plyng3);
            // console.log('Video 1 is playing');
            if(plyng2 == true){
               // console.log('Video 2 is playing');
               vid2.pause();
               // console.log('Video 2 is paused');
               plyng2 = false;
            }

            if(plyng3 == true){
               // console.log('Video 3 is playing');
               vid3.pause();
               // console.log('Video 3 is paused');
               plyng3 = false;
            }
            // console.log(plyng2, plyng3);            
         };

         vid2.onplay=function(){
            // console.log(plyng1, plyng3);
            // console.log('Video 2 is playing');
            if(plyng1 == true){
               // console.log('Video 1 is playing');
               vid1.pause();
               // console.log('Video 1 is paused');
               plyng1 = false;
            }

            if(plyng3 == true){
               // console.log('Video 3 is playing');
               vid3.pause();
               // console.log('Video 3 is paused');
               plyng3 = false;
            }
            // console.log(plyng1, plyng3);            
         };

         vid3.onplay=function(){
            // console.log(plyng1, plyng2);
            // console.log('Video 3 is playing');
            if(plyng1 == true){
               // console.log('Video 1 is playing');
               vid1.pause();
               // console.log('Video 1 is paused');
               plyng1 = false;
            }

            if(plyng2 == true){
               // console.log('Video 2 is playing');
               vid2.pause();
               // console.log('Video 2 is paused');
               plyng2 = false;
            }
            // console.log(plyng1, plyng2);            
         };`

**Comment by bharath-exads** [comment]
Hi,

We have added **playing** event callback https://docs.fluidplayer.com/api/#on-playing-function

Have created sample example for your use case https://codepen.io/bharath-exads/pen/QeMJaQ
Please check
