### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by akudryav** [fluid-player/fluid-player#33]
Is it possible to use playlist (multiple video files) within fluidplayer?
Or switch to another video during playback by clicking a link or somehow?

**Comment by cian-exads** [comment]
Hi @akudryav, at the moment these features are not available. I have passed on your message and both of these features will be considered in future development. Thank you very much for your feedback and stay tuned for upcoming releases.

**Comment by tariktuzlakovic** [comment]
Hi, is this feature implemented? If so, could you share some information and advice regarding this issue? 
Thanks!

**Comment by durgeshksh1** [comment]
Hi, is it implemented?. Kindly reply

I could make a playlist with the help of js and css like shown bwlow.

![fluid_player_playlist](https://user-images.githubusercontent.com/26226832/57980570-b4bd8a80-7a4a-11e9-9996-8531b4617651.png)

html
`<div class="vid-player">
--
  | <div class="player" id="player">
  | <video id='vidPlayer' controls style="width: 100%;">
  | <source data-fluid-hd src="http://localhost/files/me/thermodynamics/intro/toystory_720.m3u8" title='720p' type='application/x-mpegURL' />
  | <source src="http://localhost/files/me/thermodynamics/intro/toystory_480.m3u8" title='480p' type='application/x-mpegURL' />
  | <source src="http://localhost/files/me/thermodynamics/intro/toystory_360.m3u8" title='360p' type='application/x-mpegURL' />
  | </video>
  | </div>
  |  
  | <div class="playlist">
  | <ol id="playlist">
  | <li class='activVid'><a href="#" att="http://localhost/files/me/thermodynamics/intro/toystory"> <img src="http://localhost/files/images/thumbnail/videoTmb/studymaterial.jpg" alt="" srcset=""> Toy Story </a></li>
  | <li class=''><a href="#" att="http://localhost/files/me/fluidmechanics/intro/planet"> <img src="http://localhost/files/images/thumbnail/videoTmb/GS.jpg" alt="" srcset=""> Planet Earth </a></li>
  | <li class=''><a href="#" att="http://localhost/files/me/thermodynamics/textmotion/TextInMotion"> <img src="http://localhost/files/images/thumbnail/videoTmb/liveclass.jpg" alt="" srcset=""> Text in Motion </a></li>
  | <li class=''><a href="#" att="http://localhost/files/me/thermodynamics/tab/jellyfish"> <img src="http://localhost/files/images/thumbnail/videoTmb/testseries.jpg" alt="" srcset=""> Jelly Fish </a></li>
  | </ol>
  | </div>
  | </div>
`
JS

`var grabPlayer = document.getElementById('vidPlayer');
var myFluidPlayer = fluidPlayer('vidPlayer',
{
layoutControls: {
    primaryColor: "#28B8ED",
    playbackRateEnabled: true,
    fillToContainer: true,
}
});

// Grab the playlist items and apply onclick function for changing the video.
var playlist = document.querySelectorAll('#playlist a');

for(var i=0; i<playlist.length; i++){
playlist[i].onclick = clickFunct;
}

// Function for click event on playlist item.
function clickFunct(event){
event.preventDefault();

// Change the background colur of active video. 
var playlistItems = document.querySelectorAll('#playlist li')
for(var i=0; i<playlistItems.length; i++){
    playlistItems[i].classList.remove("activVid");
    // console.log(playlistItems[i])
}
var parent= this.parentNode;
parent.classList.add("activVid");
// console.log(parent)

// create a new video element with source in javascript.           
var newVid = document.createElement("video");

var a1 = document.createAttribute("id");     
a1.value = "vidPlayer";
newVid.setAttributeNode(a1);

var a2 = document.createAttribute("controls");
newVid.setAttributeNode(a2);

var a3 = document.createAttribute("style");     
a3.value = "width: 100%";
newVid.setAttributeNode(a3);

// Grab the file name with path and create the source list.
var file = this.getAttribute('att');

var newSource1 = document.createElement("source");

var hd = document.createAttribute("data-fluid-hd");
newSource1.setAttributeNode(hd);

var a4 = document.createAttribute("src");     
a4.value = file + '_720.m3u8';
newSource1.setAttributeNode(a4);
var title1 = document.createAttribute("title");
title1.value = '720p';
newSource1.setAttributeNode(title1);
var a7 = document.createAttribute("type");     
a7.value = "application/x-mpegURL";
newSource1.setAttributeNode(a7);

var newSource2 = document.createElement("source");
var a5 = document.createAttribute("src");     
a5.value = file + '_480.m3u8';
newSource2.setAttributeNode(a5);
var title2 = document.createAttribute("title");
title2.value = '480p';
newSource2.setAttributeNode(title2);
var a8 = document.createAttribute("type");     
a8.value = "application/x-mpegURL";
newSource2.setAttributeNode(a8);

var newSource3 = document.createElement("source");
var a6 = document.createAttribute("src");     
a6.value = file + '_360.m3u8';
newSource3.setAttributeNode(a6);
var title3 = document.createAttribute("title");
title3.value = '360p';
newSource3.setAttributeNode(title3);
var a9 = document.createAttribute("type");     
a9.value = "application/x-mpegURL";
newSource3.setAttributeNode(a9);			

newVid.appendChild(newSource1);
newVid.appendChild(newSource2);
newVid.appendChild(newSource3);

// Grab the player div element, remove old fluid player wrapper div from it and append new video element with new source.
var player = document.getElementById('player');
var wrapperDiv = player.children[0];
// var OldVideo = wrapperDiv.children;

player.removeChild(wrapperDiv);
player.appendChild(newVid);

// Create fluid player element on new video element.
var myFluidPlayer = fluidPlayer('vidPlayer',
    {
        layoutControls: {
            primaryColor: "#28B8ED",
            playbackRateEnabled: true,
            fillToContainer: true,
        }
    }
);

// Play the new video.
myFluidPlayer.play();
}`

Everything working fine except controls. The duration displayed is of first video only, and seek is not working properly. Play, pause, quality selection etc are fine.

Help in fixing the issue will be appreciated.

**Comment by Addvilz** [comment]
I don't think this is in scope of the player itself. This should really be done on case by case basis. If this is something that you often need, consider spawning a project that uses NPM Fluid Player and is reusable.
