### ISSUE TITLE
Use fluid-player for outstream VAST?

### ISSUE THREAD

**Issue by dianomi-mjs** [fluid-player/fluid-player#338]
Is it possible to use Fluid Player for "outstream" VAST video?

If not, would it be possible to sponsor this as an enhancement?

Thanks

**Comment by NelsonClout** [comment]
Would also like to know this.

**Comment by jlybbert** [comment]
bump

**Comment by agammathur** [comment]
I will like to use the fluid-player for implementing out-stream renderer for Prebid. Any help regarding this will be helpful.

**Comment by Addvilz** [comment]
Outstream would be quite tricky to support in Fluid Player as it is specifically designed to work with Instream. Both concepts are quite different and Instream, and Outstream players have entirely different lifecycle too.

Perhaps we could create a "module" specifically for Outstream independent from the Instream player itself. This needs further investigation and prioritization from our side however.

**Comment by HariPriyaKuberSingh** [comment]
@dianomi-mjs -  Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@dianomi-mjs - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Since there is no confirmation from the reporter regarding the issue, we are closing the ticket
