### ISSUE TITLE
Double Tap to Seek Feature

### ISSUE THREAD

**Issue by nissiu** [fluid-player/fluid-player#343]
I am posting this issue as a feature request that I think would help user experience on mobile.

What I would like to see implemented into Fluid Player is the "double tap to seek" that the YouTube player has. When the user double taps on the right side of the video, the player forwards it by 10 seconds and vice versa for the left side. Even two simple buttons that trigger these actions, instead of the double tap, would be great.

Considering that the majority of traffic is on mobile, another feature that would be a huge improvement in usability on these devices would be to have the player only show the control bar and a pause button in the middle, without pausing the video, when a user taps in the middle of the player. Just like Chrome's native HTML5 player. 

I find the fact that the player pauses the video on tap on mobile to be pretty annoying.

**Comment by HariPriyaKuberSingh** [comment]
@nissiu - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@nissiu - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Closing the ticket since there is no response from the reporter
