### ISSUE TITLE
Float on scroll option

### ISSUE THREAD

**Issue by tkoopa** [fluid-player/fluid-player#347]
A nice to have option would be for the player to automatically float in a corner of the browser whilst the video is playing but the user has scrolled it out of the display

**Comment by HariPriyaKuberSingh** [comment]
@tkoopa - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@dianomi-mjs - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@tkoopa -  Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Closing this ticket since there is no confirmation from the reporter regarding the issue
