### ISSUE TITLE
VAST preroll audio+banner

### ISSUE THREAD

**Issue by lain0** [fluid-player/fluid-player#349]
I want to use VAST preroll  audio + Banner, but how to show banner natively from player?
Audio or video preroll from VAST plays ok.

How to show from this vast jpg while audio preroll:
https://x.instreamatic.com/v4/vast/777?preview=11

```
<Companion width="640" height="640">
<StaticResource creativeType="image/jpg">
<![CDATA[
https://unisound.cdnvideo.ru/static/creative/images/CC/E00DA3.jpg
]]>
</StaticResource>
```

**Comment by Addvilz** [comment]
Sorry, I do not understand what you are asking here. Please, provide more details.
