### ISSUE TITLE
adCTAText is not work

### ISSUE THREAD

**Issue by zijian85** [fluid-player/fluid-player#350]
Hi, I have tested the VAST function, but the adCTAText is not work. The ship button can show, but the adCTAText didn't show.

Demo link: http://api.localau.com/fluidplayer.html

MAC Pro with chrome.

By the way , can I use other languages to set adCTAText? Such as Chinese. I tested Chinese in adsText, but it shows garbled characters.

**Comment by bharath-exads** [comment]
Hi,

To show ctaButton overlay on the player, your vast xml should contain 'IconClicks' and its children tags

**Comment by zijian85** [comment]
> Hi,
> 
> To show ctaButton overlay on the player, your vast xml should contain 'IconClicks' and its children tags

It work, thanks so much.
