### ISSUE TITLE
Bad user satisfaction when using a playlist with autoplay next in full screen

### ISSUE THREAD

**Issue by anthonisx** [fluid-player/fluid-player#352]
if you set some videos in a playlist and then set the autoplay in fluid player when you are in full screen and the video ends when auto go to the next video automatically it is out from the full screen drastically and it is very annoying to be entering the full screen and again, etc.

 the expected behavior is:

loading animation reproduces and stay in full screen mode while preparing the jump to the next video to be played without having to intervene again and again in each video. thank you alot.

**Comment by Addvilz** [comment]
Can you clarify? There is no playlist feature in Fluid Player.

**Comment by Addvilz** [comment]
Closing as inactive.
