### ISSUE TITLE
How to set video source through options?

### ISSUE THREAD

**Issue by ghost** [fluid-player/fluid-player#357]
Hi, I have read all your documents. But unfortunately, I cannot find a way to dynamically set the video source of fluidplayer by javascript. 

It appears your docs just show how to apply fluidplayer to a static website.
Your way is :
"<video id="video-id">"
    <source src="video.mp4" type="video/mp4"/>
</video>

But my preferred way is : 
   layoutControls : {
                        posterImage : ret.poster,
                        autoPlay    : 'false',
                        videosrc     : ret.video,
                        type        : 'video/mp4'
     
  fluidPlayer("mvideo", options);

How can I work around the problem and apply fluidplayer to a practical video website?

**Comment by harrykc** [comment]
i also need this function, like jwplayer

**Comment by xulj** [comment]
> i also need this function, like jwplayer

but why don't just use jwplayer instead? because it's non-free?

**Comment by Addvilz** [comment]
You can simply generate video tag with all it's contents using JavaScript and attach Fluid Player to that generated element.

**Comment by virangaj** [comment]
`var video = document.getElementById('fluid-player-e2e-case');

            // Step 2: Create a new source element
            var source = document.createElement('source');

            // Step 3: Set attributes for the source element
            source.setAttribute('src', data.src);
            source.setAttribute('type', 'application/x-mpegURL');

            // Step 4: Append the new source to the video element
            video.appendChild(source);

            // Optionally, you can load the video if it's not set to autoplay
            video.load();
`
