### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by tonykor** [fluid-player/fluid-player#36]
Hello,

thanks for pause roll html, and for quality switcher. Could you also make middle roll html, to show ads while video playing on top or bottom. And also call to action html on the end of the video. 

Thanks.

**Comment by cian-exads** [comment]
Hi @tonykor, thank you very much for the feedback, we're happy to hear you like the new features. I will pass your requests on to the main development team and they will be considered in future planning. Stay tuned for future updates.

**Comment by Bluecozza** [comment]
This is Awesome.
My question (or maybe a 'next feature'):
a. How to set default volume to 0%
b. How to add image as Poster/background picture.
This is great Project

**Comment by cian-exads** [comment]
Hi @Bluecozza, we're delighted to hear you're enjoying Fluid Player. 

**a. How to set default volume to 0%** - this is not currently possible. However we have discussed this and it will be considered for future planning. 

**b. How to add image as Poster/background picture.** - There is currently functionality to add logos and images to the player. This was covered in another issue [which can be seen here].(https://github.com/fluid-player/fluid-player/issues/37)

**Comment by kristijanexads** [comment]
@Bluecozza , regarding question **a)** volume can be set to 0 by using ```mute: true``` parameter. 
We hope that feedback on your **b)** question from the previous answer helped you, if not feel free to get back to us.



@tonykor  middle role has been supported now in v1.2.0. as shown in the example below
```
<script type="text/javascript">
    var testVideo = fluidPlayer(
        'test-video',
        null,
        {
            timelinePreview: {
                file: 'thumbnails.vtt',
                type: 'VTT'
            },
            adList: {
                preRoll: {
                    'vastTag': 'vastPreRoll.xml'
                },
                midRoll: {
                    'vastTag': 'vastMidRoll.xml',
                    'timer': "50%" // or 12  --in seconds
                },
                postRoll: {
                    'vastTag': 'vastPostRoll.xml'
                }
            }
        }
    );
</script>
```
All features from this issue should now be addressed so I'm closing this one.

**Comment by ShpendBerisha** [comment]
Would be better to add also cookie support for the player volume, if you turn it off when you refresh the page its still on.

**Comment by cian-exads** [comment]
Yes @ShpendBerisha, this is a feature we hope to have in the next Fluid Player release.
