### ISSUE TITLE
Subtitles not show in mobile fullscreen

### ISSUE THREAD

**Issue by phansheng89** [fluid-player/fluid-player#368]
I followed instruction at https://docs.fluidplayer.com/subtitles/, the subtitles show up just fine but on mobile, when enter full-screen mode the sub disappear.

Is there a fix for it?

Thanks.

**Comment by bharath-exads** [comment]
Hi,

Can u please share details of your mobile device like OS, Mobile Model, Browser where experienced this issue.

**Comment by phansheng89** [comment]
Hi,

It's iPhone iOS 12.3.2 Safari browser. When use fullscreen mode the subtitle no longer works.

Thanks.

**Comment by bharath-exads** [comment]
Hi,

Unfortunately, iPhone browsers don't allow to overlap Html elements to overlap a video player in fullscreen mode

But there are some workaround u can try
1. Remove fullscreen icon from the player
2. Make the player to take full height and width of the page

This fix requires you to make alterations only for **iPhone browsers**.


Please share if you found alternative solutions.

**Comment by Yitzchok** [comment]
Adding a duplicate track tag with kind="subtitles" kind of works
