### ISSUE TITLE
How add image in embed videos? and how add logo in video? fluid-player

### ISSUE THREAD

**Issue by LeoLuanElezi** [fluid-player/fluid-player#37]
some one can help me?

**Comment by LeoLuanElezi** [comment]
<link rel="stylesheet" href="https://cdn.fluidplayer.com/current/fluidplayer.min.css" type="text/css"/>
<script src="https://cdn.fluidplayer.com/current/fluidplayer.min.js"></script>

<video id='my-video' controls style="width: 640px; height: 360px;">
	<source src='myvideo mp4' type='video/mp4' />
</video>

<script type="text/javascript">
	var testVideo = fluidPlayer('my-video');
</script>



in my phone HUAWEI, Does not open in full screen!?

**Comment by LeoLuanElezi** [comment]
some one can help me?

**Comment by cian-exads** [comment]
Hi @LeoLuanElezi, the **logo** and **logoPosition** can be set in the Fluid Player **options** parameter. See below for an example on how to set this:

```javascript
<script type="text/javascript">
    var testVideo = fluidPlayer(
        'my-video',
        'http://example.com/vast.xml',
        {
            logo: 'exampleImage.jpg',
            logoPosition: 'top right'
        }
    );
</script>
```
Note that the default **logoPosition** will be _top left_, and so it is not required to set this property. 

The full list of the optional Fluid Player parameters can be found at the following - https://github.com/fluid-player/fluid-player#parameters

I hope this information helps, and if you have any further questions do not hesitate to ask. Thank you very much.

**Comment by LeoLuanElezi** [comment]
Thanks 👍
