### ISSUE TITLE
Skip ad button on VAST preroll opening a new blank tab.

### ISSUE THREAD

**Issue by uaker1488** [fluid-player/fluid-player#372]
I think it happens when <head> have <base target="_blank"> tag.

**Comment by uaker1488** [comment]
http://joxi.ru/5mdBBbYc3lvGkA
this tag

**Comment by kristijanexads** [comment]
@uaker1488 sorry for the inconvenience, this should be now fixed with yesterdays release

**Comment by uaker1488** [comment]
Still bad... 
Did new release go to
https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js
?
