### ISSUE TITLE
adding custom buttons in player

### ISSUE THREAD

**Issue by raka31** [fluid-player/fluid-player#378]
can anyone tell me how to add custom buttons with custom icon.
i am not able to add any extra buttons in player i tried through its css.
Also i tried To customize the Control bar to add button.

**Comment by bharath-exads** [comment]
Hi,

You can currently change icons of existing buttons by overriding CSS

For adding your own buttons, you can edit **generateCustomControlTags** function in js file

**Comment by raka31** [comment]
thank you @bharath-exads  for helping me out.
