### ISSUE TITLE
hls.min.js.map Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by doratown** [fluid-player/fluid-player#379]
Hi,

The player was working fine with HLS.

But on the console it's show the error although everything works well

Failed to load resource: the server responded with a status of 404 ()
https://cdn.fluidplayer.com/v2/current//scripts/hls.min.js.map

**Comment by bharath-exads** [comment]
Hi,

Can u please provide the URL where the player is hosted
it will help us in debugging

**Comment by doratown** [comment]
Hi it's over here: https://taiwanno1.xyz/star-movie/

**Comment by bharath-exads** [comment]
Hi,

I am able to play content just fine
https://ibb.co/2n3ZN49

not able to see debugger, app is navigating to 404

can u please provide more info on which browser and version u are facing this issue.

**Comment by doratown** [comment]
Hi,

I had disable the code blocking debugger.

Yes the player is working fine as mentioned my first post, just wonder why this error prompt.

I'm using Safari 13.0（15608.2.5)
