### ISSUE TITLE
Single tap to video leads to pause and to click "onPauseRoll" promo

### ISSUE THREAD

**Issue by demybus** [fluid-player/fluid-player#380]
The issue appears on mobile devices.  Single tap to video leads to pause and to click banner also if you have installed "onPauseRoll" promo

**Comment by bharath-exads** [comment]
Hi,

We tried on roll ads in the mobile device (Android)
It worked fine

Can u please provide URL where u are experiencing this, also device info.

**Comment by demybus** [comment]
Thank you for the reply.
I've checked once again right now and the issue appears every time for me. Example URL:
https://vqporn.com/videos/21385/180413-5-the-daybreak-a-no-watermark/
Android + chrome, samsung browser. For desktop it works correct even with mobile emulator

**Comment by bharath-exads** [comment]
#381

**Comment by Addvilz** [comment]
Should be fixed with v3.
