### ISSUE TITLE
cdn.fluidplayer.com

### ISSUE THREAD

**Issue by SKY3AU** [fluid-player/fluid-player#382]
Certificate on this site has just expired and has caused the player to brake on all sites using its code.

<link rel="stylesheet" href="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.css" type="text/css"/>
<script src="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js"></script>

IT guys, you need to renew your certs..

**Comment by bharath-exads** [comment]
Hi,

We can see our player is able to load and the certificate is just fine.

Can u please provide me Link where u are experiencing this issue

**Comment by golikov** [comment]
The certificate was renewed on August 29 and is valid till November 27.
@SKY3AU could you please provide the IP address(es) that cdn.fluidplayer.com resolves as for you?
Maybe you are hitting some CDN nodes that haven't updated the certificate for some reason.

**Comment by SKY3AU** [comment]
I think you're right. I just checked and it resolves a per below.
cdn.fluidplayer.com is an alias for cdn.fluidplayer.com.i.belugacdn.com.
cdn.fluidplayer.com.i.belugacdn.com has address 199.167.65.37
cdn.fluidplayer.com.i.belugacdn.com has IPv6 address 2610:1c8:8::25

**Comment by SKY3AU** [comment]
Hi,

Can’t connect to https://cdn.fluidplayer.com

cdn.fluidplayer.com is an alias for cdn.fluidplayer.com.i.belugacdn.com.
cdn.fluidplayer.com.i.belugacdn.com has address 199.167.65.37
cdn.fluidplayer.com.i.belugacdn.com has IPv6 address 2610:1c8:8::25

Thanks

**Comment by golikov** [comment]
There are some issues with one of our CDN providers. We are communicating with them to resolve.

**Comment by SKY3AU** [comment]
Good to know. Thanks.

**Comment by golikov** [comment]
The CDN provider says they have fixed the issue. Are you still experiencing problems with CDN?

**Comment by SKY3AU** [comment]
All good now.
Thanks!
