### ISSUE TITLE
Lazy load for videos

### ISSUE THREAD

**Issue by protechnology** [fluid-player/fluid-player#384]
Hi,
Is there any way to "lazy load" the videos. I mean like a preload of the first 10sec of the video and then wait with further loading until the user clicks on play?
In my case the videos on the website are all loaded at the beginning which slows down the website.
BR, George

**Comment by Addvilz** [comment]
For VOD, Fluid Player uses preload. See https://docs.fluidplayer.com/docs/configuration/layout/#preload
