### ISSUE TITLE
VMAP support

### ISSUE THREAD

**Issue by throne1986** [fluid-player/fluid-player#387]
I have vast.4 version Tags already configured , now I want to play ads in fluidplayer

Here is my vast4.xml file which contains `preRoll, MidRoll and PostRoll`

    <vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
    <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
    <vmap:AdSource id="preroll-ad-1" allowMultipleAds="false" followRedirects="true">
    <vmap:AdTagURI templateType="vast4"></vmap:AdTagURI>
    </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak timeOffset="00:00:15.000" breakType="linear" breakId="midroll-1">
    <vmap:AdSource id="midroll-1-ad-1" allowMultipleAds="false" followRedirects="true">
    <vmap:AdTagURI templateType="vast4"></vmap:AdTagURI>
    </vmap:AdSource>
    </vmap:AdBreak>
    <vmap:AdBreak timeOffset="end" breakType="linear" breakId="postroll">
    <vmap:AdSource id="postroll-ad-1" allowMultipleAds="false" followRedirects="true">
    <vmap:AdTagURI templateType="vast4"></vmap:AdTagURI>
    </vmap:AdSource>
    </vmap:AdBreak>
    </vmap:VMAP>

Here is ad config js

    $(document).ready(function () {
        console.log('Init started');
        fluidPlayer(
            'my-video', {
                layoutControls: {
                    primaryColor: false,
                    playButtonShowing: true,
                    playPauseAnimation: true,
                    fillToContainer: false,
                    autoPlay: false,
                    preload: false,
                    mute: true,
                    doubleclickFullscreen: true,
                    subtitlesEnabled: false,
                    keyboardControl: true,
                    layout: 'default',
                    allowDownload: false,
                    playbackRateEnabled: false,
                    allowTheatre: true,
                    title: false,
                    logo: {
                        imageUrl: null,
                        position: 'top left',
                        clickUrl: null,
                        opacity: 1
                    },
                    controlBar: {
                        autoHide: true,
                        autoHideTimeout: 3,
                        animated: true
                    },
                    timelinePreview: {},
                    htmlOnPauseBlock: {
                        html: null,
                        height: null,
                        width: null
                    },
                    playerInitCallback: (function () {})
                },
                vastOptions: {
                    adList: [{
                        roll: 'preRoll',
                        vastTag: 'https://royaladvastplayer.videomill.pl/vastvideoplayer/vasts/vast4.xml',
                        adText: 'Advertising supports us directly'
                    }]
                }
            }
        );
    })

Now when I click Play button no ads is loaded , what is wrong with my code?

**Comment by EhsanCh** [comment]
I think VMAP is not supported yet. you can insert multiple vastTag to adList. Please see [documents](https://docs.fluidplayer.com/ad_configuration/).

**Comment by HariPriyaKuberSingh** [comment]
@throne1986 - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@throne1986 - can you please confirm if the issue still exists ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
