### ISSUE TITLE
preload "false" ignored

### ISSUE THREAD

**Issue by truedaedalus** [fluid-player/fluid-player#388]
The issue is that player ignores any preload parameters. 
layoutControls: {
             autoPlay: false,
             preload: false
}
«preload=none» and «preload: false» are not working. Player gets the url of video source before the play button is clicked. Also if you hover the mouse under the timeline it will show the duration of the video. It seems the player loads the metadata atleast. 

How to get player work as the native html5 video player (video tag) - to not access the video url before the user clicks on play button?

**Comment by hitmanex** [comment]
https://github.com/fluid-player/fluid-player/issues/360#issuecomment-534924778

**Comment by Addvilz** [comment]
See #360
