### ISSUE TITLE
How to add from gdrive video?

### ISSUE THREAD

**Issue by Pulpfaption** [fluid-player/fluid-player#390]
Sorry Im newbie

**Comment by hitmanex** [comment]
gdrive video has ip checking protection when you play the actual video (at least on its core domain). You cannot just fetch the page server side and expect it to play..

this also goes outside the realms of the player as the player just plays the files provided to it. its your own place to provide those files (in the case of gdrive video, fetch and provide)

**Comment by Addvilz** [comment]
To the best of my knowledge, Google Drive videos can not be streamed or embedded by 3rd party video players. They use Youtube-like video player internally with unknown sourcing tech behind it.
