### ISSUE TITLE
Stretch posterImage to playerwindow

### ISSUE THREAD

**Issue by det66** [fluid-player/fluid-player#391]
Hi,

I remember there was already an option to stretch the posterImage to fit the player window.
I can't find that in the documentation.
Can somebody help please?

**Comment by det66** [comment]
Thank you all for your help  :-/
I finally found it here:
https://github.com/fluid-player/fluid-player/compare/478594776a507d073557dcde8266e7276a93d6e2..66a2e333506ef3c98490a1fce6ed5c310530eb15

Somebody should add this to the docs....

**Comment by leroybm** [comment]
Moved this ticket forward in the internal issues, it should be fixed in the following weeks.

**Comment by sergiomcsousa** [comment]
@det66 This went live around 4 months ago. Can this ticket be closed? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
