### ISSUE TITLE
Can't focus on player to activate shortcuts

### ISSUE THREAD

**Issue by papee** [fluid-player/fluid-player#392]
I would like to set focus on the player once the page is loaded to enable the shortcuts (play/pause, FF...) without having to clic on the player.

using $('#video-player').focus(); did not the trick where it works with my old JWPlayer.

Thanks!

**Comment by Addvilz** [comment]
This is not something we will officially support. That being said, the keyboard events are bound to wrapper, not the player. Look for element prefixed `fluid_video_wrapper_` in the DOM.
