### ISSUE TITLE
Configuration for LIVE broadcasting

### ISSUE THREAD

**Issue by daursdg** [fluid-player/fluid-player#394]
How to configure the player for online broadcasting (live broadcasting) so that the seekbar does not appear and there is an LIVE caption? Thanks!

**Comment by 1TekPro** [comment]
Old issue but you can just do this with css

**Comment by HariPriyaKuberSingh** [comment]
@daursdg - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@daursdg - Can you please confirm if the issue resolved or does it still exist ?

**Comment by Rog62** [comment]
STOP

**Comment by HariPriyaKuberSingh** [comment]
Closing the ticket since there is no confirmation from the reporter
