### ISSUE TITLE
VAST AD once per visitor

### ISSUE THREAD

**Issue by killown** [fluid-player/fluid-player#397]
is there some way to display a VAST AD only once per visitor every X time?
The issue is, every new video the AD will display again for the same visitor

**Comment by EhsanCh** [comment]
This should be implemented in your Ad server or elsewhere... it is not related to player.
For a fast solution, you can set a cookie for user on first visit and don't add vast-tag to player for later page loads.

**Comment by Addvilz** [comment]
As mentioned above, not something that should be done in the player. You ad server should handle this case.
