### ISSUE TITLE
Help with wordpress integration

### ISSUE THREAD

**Issue by jinyus** [fluid-player/fluid-player#40]
`I know that there is a plugin but it does not have a feature that is important to me...html block on pause.

I think I did everything correctly. The css and js are in the header and I made  a page and put the <video> tag and javascript in the body, but when I visit the page, the video is playing in the default chrome player and not fluid player. 

link to the page: http://sprintkings.com/fluid-player-test/

However, everything works fine when I when I use raw html

link to working version: http://sprintkings.com/fluidtest.html

They are basically the same thing, but I can't get it to work in my blog. Could someone tell me what I am doing wrong?

**Comment by cian-exads** [comment]
Hi @jinyus, from checking your **fluid-player-test** page we can see in the console that there is an error -
```*Uncaught SyntaxError: Unexpected token <*```

This is occurring due to a `<p>` tag within the javascript. The below code is the snippet where the error can be found. 
```javascript
 var testVideo = fluidPlayer(
'my-video',
        '',
        {
            htmlOnPauseBlock: '<img src="http://sprintking.cf/test.png">',
        }
);</p>
```
Please remove this tag and see if the issue is resolved.
