### ISSUE TITLE
Add custom link to the download button

### ISSUE THREAD

**Issue by ferminq989** [fluid-player/fluid-player#400]
Hello, I would like to be able to add for the next version that the logo may be at the bottom, where the full screen icon is.

and I would also like for the next version that the download icon can have a custom link.

For example, if the video is played as an embed, I would like people to reach my website through the download button and not to the direct mp4.

or if someone knows how to do it?

Thank you

**Comment by Addvilz** [comment]
For the logo, this is not something we are looking to change. You can still modify DOM after player loads using JavaScript to your liking, including this behavior.

Custom link to download makes sense however.

**Comment by HariPriyaKuberSingh** [comment]
@ferminq989 - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@ferminq989 - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Closing the ticket since there is no confirmation from the reporter
