### ISSUE TITLE
How to add Vast Tag in Fluid player in WordPress? 

### ISSUE THREAD

**Issue by DangerGo** [fluid-player/fluid-player#401]
I don't know more about coding so I don't know why vast tag is not working.
This is the code which I have used every this is fine but vast is not playing? 

[fluid-player
    video="https://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_480_1_5MG.mp4"
vast_file="https://www.movcpm.com/watch.xml?key=af5222c12af4829eb69dfc25d313b9b8"
poster-image="https://upload.wikimedia.org/wikipedia/en/6/6e/Dream_Girl.png"
    layout="default"
    responsive="true"
]

**Comment by Addvilz** [comment]
Current wordpress plugin is not maintained. We plan to take ownership of it at some point, and have it properly configurable, but this is not in the scope of Fluid Player itself.
