### ISSUE TITLE
The player showing minutes for the long videos e.x 2 hours is showing as 139:00

### ISSUE THREAD

**Issue by gximm** [fluid-player/fluid-player#403]
Hi , 
Do you guys know how to change the duration of the video from minutes to the hours for e.x 2:14:35

The fluid player right now is showing duration as 139:00

**Comment by HariPriyaKuberSingh** [comment]
@gximm - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@gximm - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@gximm  Closing the ticket since there is no confirmation from the reporter
