### ISSUE TITLE
Lighthouse says: Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by Lestadt** [fluid-player/fluid-player#404]
Hello, apparently everything works fine with the player, however when auditing my site with the Lighthouse tool it shows me this error or suggestion:

  Does not use passive listeners to improve scrolling performance
https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js

I am trying to optimize my site, basically to accelerate the load on mobile devices and this error is something that I must solve, I don't know if you should update the fluidplayer.min.js file or if there is something that I can do on my own to Solve this, I would appreciate any suggestions.

**Comment by HariPriyaKuberSingh** [comment]
@Lestadt - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@Lestadt - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Closing the ticket since there is no confirmation from the reporter

**Comment by biguz** [comment]
Still not resolved https://pagespeed.web.dev/analysis/https-www-fluidplayer-com/c6eg5xjgg6?hl=en&form_factor=mobile

**Comment by leroybm** [comment]
Reopening, adding the passive flag should fix this.

**Comment by leroybm** [comment]
@biguz @Lestadt The fix for this was just released. Can any of you confirm that this is fixed so I can close the issue?

**Comment by leroybm** [comment]
@biguz @Lestadt Can you close this if it's ok?

**Comment by leroybm** [comment]
Closing this ticket since the issue is resolved
