### ISSUE TITLE
adCTAText/ctaButton not shown when no IconClickThrough exist

### ISSUE THREAD

**Issue by EhsanCh** [fluid-player/fluid-player#406]
When IconClickThrough is empty in vast tag, no ctaButton/ctaText shown.
We need clickthroughUrl to be shown in player as a link/button.

i fixed it by removing
`this.displayOptions.vastOptions.adCTAText = false;`
in getIconClickThroughFromLinear function
and change addCTAButton function:
```
        if (landingPage)
            link.innerHTML += "<br/><span class=\"add_icon_clickthrough\">" + landingPage + "</span>";
```
Please fix it in next release.
Regards.

**Comment by HariPriyaKuberSingh** [comment]
@EhsanCh - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@EhsanCh - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
