### ISSUE TITLE
Some issues & fixes

### ISSUE THREAD

**Issue by EhsanCh** [fluid-player/fluid-player#410]
I found and fixed some bugs , I will post here for developers to review and fix it in code.

- In **setCurrentTimeAndPlay** function, _player.controlPlayPauseToggle_ will hide initial play button if it called before initial play. i fixed it by removing it.

- in **resolveVastTag** i changed _handleXmlHttpReq_ so it handle errors correctly.

```        var handleXmlHttpReq = function () {
            var xmlHttpReq = this;
            if (xmlHttpReq.readyState >= 2 && xmlHttpReq.status >= 400) {
                callBack(false);
                return;
            }

            if (xmlHttpReq.readyState === 4 && xmlHttpReq.status === 0) {
                callBack(false); //Most likely that Ad Blocker exists
                return;
            }

            if ((xmlHttpReq.readyState === 4) && (xmlHttpReq.status !== 200)) {
                callBack(false);
                return;
            }

            if (!((xmlHttpReq.readyState === 4) && (xmlHttpReq.status === 200))) {
                return;
            }
```

- in **switchToMainVideo** function
```
        videoPlayerTag.src = player.originalSrc;
        player.toggleLoader(true);
```
and in **setVideoSource**
```
            videoPlayerTag.src = url;
            player.toggleLoader(true); //namayesh

```
to show loader when switching source after vast load/fail.

- in initialPlay function:
```
        videoPlayerTag.addEventListener('timeupdate', function () {
            // some places we are manually displaying toggleLoader
            // user experience toggleLoader being displayed even when content is playing in background
            if (videoPlayerTag.readyState > 1 || (videoPlayerTag.readyState > 0 && videoPlayerTag.paused))  
                player.toggleLoader(false);
        });
        videoPlayerTag.addEventListener('pause', function () {
            player.toggleLoader(false);
        });
```
first will prevent hide loader when video is not ready and second wil hide loader when player paused.

- in **setLayout** function change:
`        var listenTo = 'click';
`
to prevent unwanted play/pause when finger touched screen on mobile devices. _click_ event work in mobile devices and _touchend_ is not good option for this function.

**Comment by EhsanCh** [comment]
in initialPlay function changed :
```
        if (!player.firstPlayLaunched) {
            player.playPauseToggle(videoPlayerTag);
        }
        //move out from above if block
        videoPlayerTag.removeEventListener('play', player.initialPlay);
```
to always remove initialPlay event after first run.
And In setCustomControls removed:
```
            if (!player.firstPlayLaunched) {
                videoPlayerTag.removeEventListener('play', player.initialPlay);
            }
```

**Comment by EhsanCh** [comment]
event.srcElement is non-standard and should not be used , so replace all instance of it with event.target .
Also innerText should be replaced with textContent if possible.

**Comment by Addvilz** [comment]
We appreciate the fixes, but you should really submit a pull request with these instead of posting them in a ticket. V3 is out and I am not sure all of these are even valid still. Please consider upgrading and submit a pull request if you find some issues there. Thanks!
