### ISSUE TITLE
on timeupdate not work

### ISSUE THREAD

**Issue by hawkiq** [fluid-player/fluid-player#411]
I setup my player like this 

```
<script>
var myFluidPlayer = fluidPlayer("video",
    {
        layoutControls: {
            subtitlesEnabled: true,
            autoPlay: true,
        }
    });

    myFluidPlayer.on('timeupdate', function(currentTime, duration, isCurrentlyPlayingAd){
        console.log(currentTime);
        console.log(duration);
});
</script>
```

I get in console log

`[FP_ERROR] Event not recognised`

I forget to tell I want to get current time and duration fro  video using API, Ive managed to use on Playing event but still cant get current time and duration.

**Comment by EhsanCh** [comment]
Use like this : 
```
        var videoPlayerTag = document.getElementById(myFluidPlayer.videoPlayerId);
        videoPlayerTag.addEventListener('timeupdate', function () {
                console.log(this.currentTime);
        });
```

**Comment by Addvilz** [comment]
Fluid Player instance does not emit `timeupdate` - this is something that comes directly from HTMLMediaElement itself (e.g. video). We should probably "forward" this event to the API.

**Comment by Addvilz** [comment]
Will be fixed with v3.
