### ISSUE TITLE
Subtitle in Safari Iphone

### ISSUE THREAD

**Issue by marcofbb** [fluid-player/fluid-player#412]
Hi,
I want to report that the subtitles are not displayed in full screen in the safari iphone XR latest version.

regards

**Comment by marcofbb** [comment]
I just read that it was already published at https://github.com/fluid-player/fluid-player/issues/368

Some solutions that occur to me, without knowing if they can be carried out, are:
1- Copy the jwplayer solution
2- In case you are using m3u8, make the subtitle known in m3u8 directly

**Comment by Addvilz** [comment]
This is not something we can address, see #368
