### ISSUE TITLE
How to set it to 16:10

### ISSUE THREAD

**Issue by gorgolo** [fluid-player/fluid-player#413]
hi
Is there a 16:10 setting, I don't know how to set it to a fixed ratio of 16:10
thank you

**Comment by Addvilz** [comment]
If I understand your issue correctly, you can use `fillToContainer` option as documented here. https://docs.fluidplayer.com/layout_configuration/#filltocontainer. After, you can resize the container to match whatever aspect ratio you need.

Please, feel free to re-open the issue if you need anything else.
