### ISSUE TITLE
video ended event doesn't fire on v2.4.10

### ISSUE THREAD

**Issue by netizen-ais** [fluid-player/fluid-player#414]
player.on("ended") never fires for me in this version, instead I get a pause event

**Comment by Addvilz** [comment]
Can you provide a reproduce code for that?

**Comment by netizen-ais** [comment]
This snippet works on 2.4.9, but video_ended is never called n 2.4.10
`
document.getElementById("video").addEventListener("ended", video_ended);
`

**Comment by klloveall** [comment]
I Can confirm this continues to be an issue in version 3.0.0 as well. Exact same code on 2.4.9 works as intended.
