### ISSUE TITLE
Не могу отключить кнопку с субтитрами

### ISSUE THREAD

**Issue by L1TWIN** [fluid-player/fluid-player#416]
Всем привет!
Не могу убрать субтитры https://prnt.sc/qq1d6a
Уже даже в настройках прописал, все равно не убирается иконка http://prntscr.com/qq1ddt
Скачал последнюю версию. Подскажите пожалуйста, как их убрать?

ENG:

Hi everyone,
I am not able to remve subtitles https://prnt.sc/qq1d6a
I did update the configuration, but the button remains nevertheless http://prntscr.com/qq1ddt
Using the latest version. Any ideas how to remove?

**Comment by Addvilz** [comment]
Will be fixed with v3
