### ISSUE TITLE
Avoid invisible text while the font is loading [request]

### ISSUE THREAD

**Issue by killown** [fluid-player/fluid-player#417]
Hi there, wondering if you could set font-display: swap; in fluidplayer css to avoid showing invisible text while custom fonts load.

Example:

@font-face {
  font-family: 'Pacifico';
  font-style: normal;
  font-weight: 400;
  src: local('Pacifico Regular'), local('Pacifico-Regular'), url(https://fonts.gstatic.com/s/pacifico/v12/FwZY7-Qmy14u9lezJ-6H6MmBp0u-.woff2) format('woff2');
  font-display: swap;
}

source: https://web.dev/font-display/

**Comment by Addvilz** [comment]
Kind of a duplicate to #251. Most likely, we will replace the import with system font chain, as part of #251.
