### ISSUE TITLE
How to set cookies for vast?

### ISSUE THREAD

**Issue by killown** [fluid-player/fluid-player#419]
how do we use cookies to disable Ads for 5 minutes if it was skipped

    fluidPlayer(
       'my-video',
        {
        vastOptions: {
            vastAdvanced: {
    
                vastLoadedCallback:       (

                    function getCookie() {
                        var name = cname + "=";
                         var decodedCookie = decodeURIComponent(document.cookie);
                         var ca = decodedCookie.split(';');
                         for(var i = 0; i <ca.length; i++) {
                             var c = ca[i];
                             while (c.charAt(0) == ' ') {
                                 c = c.substring(1);
                              }
                              if (get the cookie value, if it's "1") {
                              **### how to disable the ad for 5 minutes if document.cookie vast = 1**                                                     
                               }
                          }
                          return "";
                          }
                         ),

                vastVideoSkippedCallback: (function() { document.cookie = "vast=1" }),
            }
        }
    }
    );

**Comment by razor1907** [comment]
Hi. This does not seem to work for some reason. Any update 2.5 year later maybe?
