### ISSUE TITLE
VAST Ads not looping with video

### ISSUE THREAD

**Issue by stdangerous** [fluid-player/fluid-player#420]
Firstly, thanks for an awesome free player!

I'd like to have my VAST ads loop along with the actual video.

Right now the preRoll ad plays correctly the first time the video plays, but if I use the 'loop : true' option, then the video keeps looping, but not the Ad.

https://codepen.io/websm/pen/xxbormq

In the above PEN, I'm calling a 1 second blank video for the actual video so the testing process goes faster. You'll see it start looping after the first ad shows.

How can I get the  VAST ad tag to loop along with the video?

Thanks in advance

**Comment by Addvilz** [comment]
I am not entirely sure they are supposed to. Any reference in IAB VAST specifications related to this?

**Comment by Addvilz** [comment]
After scanning VAST specification I can not find anything related to how VAST should behave on looping videos, and I can't say it makes much sense to play a preRoll once a video loops. I will close this task now, but feel free to add more details, especially if you have a reference to VAST spec that describes how this should work.
