### ISSUE TITLE
Google test ad wont work with fluid player

### ISSUE THREAD

**Issue by bajro17** [fluid-player/fluid-player#421]
I try google test vast tag and this is my response can someone help please.
Script from “some url” was blocked because of a disallowed MIME type (“video/webm”).

**Comment by Addvilz** [comment]
Can you please provide more details here? What test ad was used (URL?), exact console output, what network requests were made?

**Comment by Addvilz** [comment]
No update, closing. Please submit a ticket if this is still an issue.
