### ISSUE TITLE
VPAID play failed

### ISSUE THREAD

**Issue by bajro17** [fluid-player/fluid-player#422]
Vpaid won't play I use this tag https://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=is&c=23&pl=VAST&pli=14432293&PluID=0&pos=8834&ord=%5Btimestamp%5D&cim=1
In firefox I get this error TypeError: document.body is null VPAIDAPI.js:84:365 and in chrome I get this error Uncaught TypeError: Cannot read property 'appendChild' of null

**Comment by Addvilz** [comment]
This issue seems to be related to DOM of the page, not Fluid Player. Can you provide more details to reproduce the issue, ex. codepen?
