### ISSUE TITLE
Will that be a Vue.js version ?

### ISSUE THREAD

**Issue by altezza04** [fluid-player/fluid-player#424]
Will that be a Vue.js version ? Or a tutorial on how to integrate it ?

**Comment by Addvilz** [comment]
There are several things that need to be done before we can have "proper" Vue support - #430 has to be released for you to be able to unbind Fluid Player when components are destroyed/recreated. Besides that, there is currently no NPM package, and no support for WebPack. Once #430 is public, you should be able to use CDN version with your Vue components, just make sure to call `destroy` whenever your component gets destroyed (`beforeDestroy` lifecycle event in Vue).
