### ISSUE TITLE
Fluid player 2.4.10 Track events not working in vast3.0 xml.

### ISSUE THREAD

**Issue by manikandanjmk** [fluid-player/fluid-player#425]
Here example for vast 3.0 xml with track events.

http://182.72.85.22/revivephp7/forkmediafinal/www/admin/plugins/Outstream/xml_response/vast3xml.php?zoneid=4&campaignid=1&bannerid=3&loc=http://182.72.85.22

Please fix the issue asap...

**Comment by BehringBOB** [comment]
This bug report is rude and not very detailed. :/

**Comment by manikandanjmk** [comment]
In vast 3.0 the xml have tracking events like

**<TrackingEvents>
	<Tracking event="start">
		<![CDATA[
		http://182.72.85.22/revivephp7/forkmediafinal/fc.php?script=rmvideoAds:rmvastEvent&bannerid=3&zoneid=4&event=start
		]]>
	</Tracking>
</TrackingEvents>**

Tracking events list :
firstQuartile, midpoint, thirdQuartile, complete, pause, unmute, fullscreen, skip, progress & exitFullscreen.

The above listed events doesn't call the url mentioned in xml...

**Comment by HariPriyaKuberSingh** [comment]
@manikandanjmk - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@manikandanjmk - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
