### ISSUE TITLE
Rewind video

### ISSUE THREAD

**Issue by babaSveta** [fluid-player/fluid-player#426]
Hello! Interested in 2 questions:
1. How do I rewind a video to the left or right for 10 seconds by double-clicking on the left or right side of the video?
2.  When you click on a video, it pauses, how do I make sure that when you click on it, it doesn't stop/play?
I didn't find answers to these questions in the documentation.

**Comment by BehringBOB** [comment]
@2.
you could just add a div to your video container (easiest would be with css's before/after) as an overlay. It would prevent any interaction with the video.

**Comment by Addvilz** [comment]
This will be addressed in #471 but with buttons in the control bar not on the player overlay. We can't reliably do this as you ask because the feature would interfere with ad display.
