### ISSUE TITLE
Malicious Software

### ISSUE THREAD

**Issue by aphroditus** [fluid-player/fluid-player#427]
Sites using Fluidplayer are being flagged by Google Ads as containing malicious or unwanted software. I ran a scanner across my site which comes up clean.

Any ideas on what could be raising a flag?

**Comment by Addvilz** [comment]
Could it be a coincidence - instead of sites being flagged because of Fluid Player - could they be flagged because of some other reason? Can you provide some more details about the sites, maybe some URLs we can check, scan reports?

**Comment by aphroditus** [comment]
They were flagging the css and js files on the cdn.

https://cdn.fluidplayer.com/v2/current/fluidplayer.min.css
https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js

The site is https://rp.gy

As I said the scans came up clean so I didn't save them. I'm using an older version of Fluidplayer on another site which passes their reviews. I've emailed them in hopes of getting more info on why they're flagged.

**Comment by Addvilz** [comment]
There are a few possibilities here that I see as plausible: CDN got a "tainted" IP (unlikely?) or something wrong with Google Ads compliance scanner. Google Safe Browsing returns no issue with cdn.fluidplayer.com

**Comment by aphroditus** [comment]
So I've resubmitted for review. I've swapped out the CDN links for locally served files I took from one of my other sites which didn't raise any flags. I'll add another update once I hear back.

New files: https://rp.gy/js/fluidplayer.min.js and https://rp.gy/js/fluidplayer.min.css

I don't know if there is a version difference with the CDN ones?

**Comment by Addvilz** [comment]
Yes, the files seem to be different between yours and CDN version. You can see that using any diff tool - ex. Meld (de-minimize the code first).

**Comment by Addvilz** [comment]
@aphroditus do you have any updates related to this ticket?

**Comment by aphroditus** [comment]
After switching out to a self hosted (older?) version, my site was listed as clean. I don't know what the cause was.

**Comment by Addvilz** [comment]
Closing for now. Not enough information to act on this. Please, reopen if you stumble upon something that might point us in the right direction. Thanks!
