### ISSUE TITLE
cdn.fluidplayer.com lacks IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [fluid-player/fluid-player#428]
cdn.fluidplayer.com lacks IPv6 addresses and thus resources (JavaScript) from it can't be received using IPv6.

Since the CDN seems to be served by Stackpath, which has great IPv6 support, it should hopefully be a simple fix by asking Stackpath support to enable IPv6.

Thank you.

**Comment by Addvilz** [comment]
We will request IPv6 be enabled.

**Comment by Addvilz** [comment]
IPv6 is enabled now.
