### ISSUE TITLE
 fluid player can't play in mobile

### ISSUE THREAD

**Issue by tranthanhtuan269** [fluid-player/fluid-player#431]
My site use fluid player but it can't run in mobile.

It displays an error as "[Error] (204): Timeout error. Failed to play video."

**Comment by Addvilz** [comment]
Hi, as mentioned before, please include more details - what mobile device you are using, OS, browser and version, as well as test code to reproduce the issue.

**Comment by tranthanhtuan269** [comment]
I played it in my iphone. This is info of my phone. 
Version 12.2, iphone 6 plus. I tested on iphone X too. It can't play too. 
My site is https://xemphimhot.net

**Comment by Addvilz** [comment]
I do not have this iOS/iPhone combo available. Do you see any other console output in web inspector maybe? Any errors in network tab?

**Comment by tranthanhtuan269** [comment]
On my PC, it doesn't have any errors. On iOS, I don't know the debugging with web inspector. I can send videos to let you know how it works on all the iPhones I test. I have just tested on the iPhone 5s and it has the same error.

**Comment by Addvilz** [comment]
Is it just some videos or all videos? Can you try to access mobile Safari web inspector and get some console output?

**Comment by tranthanhtuan269** [comment]
Chrome has the same error.

**Comment by sanchezzzhak** [comment]
ios debug https://github.com/google/ios-webkit-debug-proxy
linux work correct;
for win10 it is worth suffering;

**Comment by Addvilz** [comment]
@tranthanhtuan269 Chrome on iOS? iOS safari and iOS Chrome both use the same rendering and JavaScript engine, so if Safari does not work, likely the issue affects both Chrome and Safari.

Is it all videos or some specific one? 

I am sorry I need more details to narrow down the issue.

**Comment by Addvilz** [comment]
@tranthanhtuan269 can you clarify - is the **content** video not loading OR is the **advert** you have not loading?

**Comment by tranthanhtuan269** [comment]
The content video not loading. I tried to delete all ads but my video was not playable

**Comment by tranthanhtuan269** [comment]
> ios debug https://github.com/google/ios-webkit-debug-proxy
> linux work correct;
> for win10 it is worth suffering;

tks @sanchezzzhak

**Comment by sanchezzzhak** [comment]
https://developers.google.com/interactive-media-ads/docs/sdks/html5/autoplay#autoplay_on_iphone

**Comment by tranthanhtuan269** [comment]
I will delete all the ads on my site, please fix it for me!

**Comment by tranthanhtuan269** [comment]
It can play videos but it takes a long time to load!

**Comment by Addvilz** [comment]
Our best guess is that the error you see and loading time has unlikely anything to do with each other. From our tests it seems like "[Error] (204): Timeout error. Failed to play video." relates to that there is no VAST video to play and it is not actually related to the content. It just means there is no VAST to serve.

> It can play videos but it takes a long time to load!

That is an entirely different issue, and can be caused by anything, ex. your site specifics and where the content is loaded from, to the WebKit internals of iOS itself (e.g. how it preloads and buffers content). 

We will investigate further, but so far it seems like this issue might not even be related with fluid-player itself.

**Comment by tranthanhtuan269** [comment]
Thanks for reply!
I hope you can fix it soon!

**Comment by Addvilz** [comment]
Related to #225
