### ISSUE TITLE
Fullscreen Control Bar State

### ISSUE THREAD

**Issue by johpin** [fluid-player/fluid-player#433]
Thanks for a clean player.

Just a couple of suggestions:

1. In full screen mode, the control bar doesn't disappear. Have tried different combinations of the available customization options. Happening on WIndows 10.

2. Is it possible to add a buffering gif image while the player is downloading enough video data to resume playing.

Thank you.

**Comment by Addvilz** [comment]
The control bar is constrolled with an option available in configuration - https://docs.fluidplayer.com/docs/configuration/layout/#controlbar

The buffering image should be shown. If it is not, please open a bug report about it.
