### ISSUE TITLE
File .MOV, file cannot be read

### ISSUE THREAD

**Issue by genocide87** [fluid-player/fluid-player#434]
Hello,

on sngine i have your player as default and I got some trouble when people try to upload directly from iPhone.

If they export the file on a pc and upload it, i receive a mp4 file clean, so the player can read it.
When they upload a video from iPhone, it's a .mov file and the player crash.

There's a way to fix it?

![filemov](https://user-images.githubusercontent.com/40593235/79313843-3f2f9800-7f01-11ea-87ec-20a6a7cefeee.jpg)
![playerstack](https://user-images.githubusercontent.com/40593235/79313844-3fc82e80-7f01-11ea-8c2c-a67740635682.jpg)

**Comment by Addvilz** [comment]
Not related to fluid player. You need to convert the uploaded .mov files to something else - MP4/WEBM. Fluid player is just a player. It wont convert video types for you.
