### ISSUE TITLE
Subtitle list closing before being able to select anything

### ISSUE THREAD

**Issue by keepersmith** [fluid-player/fluid-player#436]
* Sporadically, was unable to select a subtitle language because the subtitle list would "hide" before I could select anything.
* Chrome (Win10).
* Happening on demo site: https://docs.fluidplayer.com/subtitles/ as well as my own development environment.

I fixed this myself like so:
        if (subtitleChangeList.style.display == 'none') {
            subtitleChangeList.style.display = 'block';
            var mouseOut = function (event) {
                //sourceChangeListContainer.removeEventListener('mouseleave', mouseOut);
                subtitleChangeList.removeEventListener('mouseleave', mouseOut);
                subtitleChangeList.style.display = 'none';
            };
            //sourceChangeListContainer.addEventListener('mouseleave', mouseOut);
            subtitleChangeList.addEventListener('mouseleave', mouseOut);
        } else {
            subtitleChangeList.style.display = 'none';
        }

Now behaves as expected.

**Comment by keepersmith** [comment]
FYI-
I also encountered this with the HD list component.
Solved using the same approach.

**Comment by Addvilz** [comment]
Thank you for reporting this. I noticed this as well, the fix will be present in next major release.
