### ISSUE TITLE
HLS Quality Switcher

### ISSUE THREAD

**Issue by Barahten** [fluid-player/fluid-player#437]
Will the ability to HLS switch quality be added?

Is there any temporary solution to this problem today?
Thanks

**Comment by Addvilz** [comment]
As far as I am aware, hls.js handles quality switching automatically. I do not see any obvious way to force the quality of HLS stream at this time.

**Comment by Barahten** [comment]
@Addvilz I  meant manual switching

**Comment by Addvilz** [comment]
@Barahten yes, I understood. I am just saying that with current implementation of fluid-player I don't see a way for you to force the quality manually.

I will tag this as a potential improvement for future.

**Comment by Barahten** [comment]
@Addvilz You use hls.js, and in it, as far as I know, there are functions for parsing m3u8 playlists

**Comment by EhsanCh** [comment]
> As far as I am aware, hls.js handles quality switching automatically. I do not see any obvious way to force the quality of HLS stream at this time.

Sometimes users need to switch to lower quality for bandwidth saving, or higher quality when hls.js didn't select high quality for any reason. 
This is the reason for manual quality selection.

**Comment by Addvilz** [comment]
I understand the reasoning behind this need. Consider that workarounds do exist - using multiple playlists - you can have master m3u8 file with all available chunks labeled "Auto" quality, and several fixed m3u8 files with fixed quality, handling quality preference outside the player and such, the same way you would do with for example, plain mkv files.

**Comment by Barahten** [comment]
Hi guys! I see, they released a new version, they did not add it to the quality switch for HLS. Will it be in the future?

**Comment by supersh86** [comment]
Hi hls switching is pretty easy.
```
hls.loadLevel = 0;
hls.currentLevel=0;
```

**Comment by supersh86** [comment]
I am our temporary solution for myself.
./src/modules/streaming.js
add playerInstance in onAfterInitHls event
`playerInstance.displayOptions.modules.onAfterInitHls(hls,playerInstance);`

Build yourself a version.
Further when setting up the player.

` onAfterInitHls: (hls, playerInstant) => {

                        hls.on(Hls.Events.MANIFEST_LOADED, function() {

                            const sources = [];
                            const sourcesList = hls.levels;
                            sourcesList.forEach(function(sourceId, index) {
///You can name your streams whatever you like.
                                    sources.push({
                                        'title': (sourceId.height > 700) ? "HD" : "SD",
                                        'url': index,
                                        'isHD': (sourceId.height > 700) ? true : false,
                                    });
                                
                            });
                            playerInstant.videoSources = sources;

                            const sourceChangeButton = document.getElementById(playerInstant.videoPlayerId + '_fluid_control_video_source');
                            sourceChangeButton.style.display = 'inline-block';

                            let appendSourceChange = false;

                            const sourceChangeList = document.createElement('div');
                            sourceChangeList.id = playerInstant.videoPlayerId + '_fluid_control_video_source_list';
                            sourceChangeList.className = 'fluid_video_sources_list';
                            sourceChangeList.style.display = 'none';
                            console.log(hls.firstLevel);
                            let firstSource = true;
                            console.log("PREFOR",playerInstant.videoSources);
                            for (const source of playerInstant.videoSources) {
                                console.log("FOR",source);
                                const getTheType = "hls";
                                const sourceSelected = (source.url == hls.firstLevel) ? "source_selected" : "";
                                const hdElement = (source.isHD) ? '<sup style="color:' + playerInstant.displayOptions.layoutControls.primaryColor + '" class="fp_hd_source"></sup>' : '';
                                firstSource = false;
                                const sourceChangeDiv = document.createElement('div');
                                sourceChangeDiv.id = 'source_' + playerInstant.videoPlayerId + '_' + source.title;
                                sourceChangeDiv.className = 'fluid_video_source_list_item';
                                sourceChangeDiv.innerHTML = '<span class="source_button_icon ' + sourceSelected + '"></span>' + source.title + hdElement;

                                sourceChangeDiv.addEventListener('click', function(event) {
                                    event.stopPropagation();
                                    // While changing source the player size can flash, we want to set the pixel dimensions then back to 100% afterwards
                                    playerInstant.domRef.player.style.width = playerInstant.domRef.player.clientWidth + 'px';
                                    playerInstant.domRef.player.style.height = playerInstant.domRef.player.clientHeight + 'px';

                                    const videoChangedTo = this;
                                    const sourceIcons = document.getElementsByClassName('source_button_icon');
                                    for (let i = 0; i < sourceIcons.length; i++) {
                                        sourceIcons[i].className = sourceIcons[i].className.replace('source_selected', '');
                                    }
                                    videoChangedTo.firstChild.className += ' source_selected';
                                    playerInstant.videoSources.forEach(source => {
                                        if (source.title === videoChangedTo.innerText.replace(/(\r\n\t|\n|\r\t)/gm, '')) {
                                            if (source.isHD) {
                                                sourceChangeButton.style.opacity = '100%';
                                            } else {
                                                sourceChangeButton.style.opacity = '50%';
                                            }
                                            playerInstant.setBuffering();
                                            hls.loadLevel = source.url;
                                            hls.currentLevel = source.url;
                                            //hls.startLoad();
                                            playerInstant.play();
                                            console.log(playerInstant);
                                            playerInstant.fluidStorage.fluidQuality = source.title;
                                        }
                                    });

                                    playerInstant.openCloseVideoSourceSwitch();
                                });
                                //Hls.Events.LEVEL_SWITCHING
                                
                                sourceChangeList.appendChild(sourceChangeDiv);
                                appendSourceChange = true;
                                
                            }

                            if (appendSourceChange) {
                                sourceChangeButton.appendChild(sourceChangeList);
                                sourceChangeButton.addEventListener('click', () => {
                                    playerInstant.openCloseVideoSourceSwitch();
                                });
                            } else {
                                // Didn't give any source options
                                document.getElementById(playerInstant.videoPlayerId + '_fluid_control_video_source').style.display = 'none';
                            }
                        });
                    hls.on(Hls.Events.MANIFEST_LOADED, function(level) {
                       /// if auto levels switch
                    })
                    }
                },`

**Comment by obumnwabude** [comment]
Thanks very much @supersh86 for this, it guided me on using fluidplayer with [Angular](https://angular.io), while off course making the quality switcher show. I should post the code here. 

#### Note:
I made the few following changes:
* I used 'video' as id on the video element, and in the Typescript code, got rid of the `playerInstant.videoPlayerId` to get the video element' id and hardcoded 'video' instead. (It's like in this v3 of fluidplayer, a lot was removed from the player instance.
* I used [Angular's Renderer](https://angular.io/api/core/Renderer2) for dynamically creating HTML elements. I created the Renderer using the RendererFactory, because of [this problem](https://github.com/angular/angular/issues/17824#issuecomment-351961146).
* I had to create a new `openCloseVideoSourceSwitch` method on the fluidPlayer instance given that it was not present in v3 of fluidPlayer.
* I also shortened the code where possible.
* To pass `ng lint` errors, I included function declaration signatures in Typsecript and used `forEach` instead of normal for loop.

#### Code:
In `app.component.html`:
```
  <video #video id="video">
    <source src="/assets/hls/test-video.m3u8" type="application/x-mpegURL">
  </video>
```
In `app.component.ts`:
```
import {
  AfterViewInit,
  Component,
  ElementRef,
  Renderer2,
  RendererFactory2,
  ViewChild
} from '@angular/core';
import fluidPlayer from 'fluid-player';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewInit {
  private renderer: Renderer2;
  @ViewChild('video') videoElement: ElementRef;
  fluidPlayer: any;

  constructor(private rendererFactory: RendererFactory2) {
    this.renderer = this.rendererFactory.createRenderer(null, null);
  }

  ngAfterViewInit(): void {
    const video = this.videoElement.nativeElement;
    this.fluidPlayer = fluidPlayer(video, {
      modules: {
        onAfterInitHls: (hls) => {
          const playerInstant = this.fluidPlayer;
          hls.on('hlsManifestLoaded', (): void => {
            playerInstant.videoSources = hls.levels.map((source, index) => {
              return {
                title: `${source.height}p`,
                url: index,
                isHD: source.height >= 720 ? true : false,
              };
            });
            playerInstant.videoSources.reverse();

            const sourceChangeButton = video.parentElement.querySelector(
              `#video_fluid_control_video_source`
            );
            sourceChangeButton.style.display = 'inline-block';

            let appendSourceChange = false;
            const sourceChangeList = this.renderer.createElement('div');
            sourceChangeList.id = 'video_fluid_control_video_source_list';
            sourceChangeList.classList.add('fluid_video_sources_list');
            sourceChangeList.style.display = 'none';

            let firstSource = true;
            playerInstant.videoSources.forEach((source) => {
              const sourceSelected =
                source.url === hls.firstLevel ? 'source_selected' : '';
              const hdElement = source.isHD
                ? '<sup style="color:#A9061C" class="fp_hd_source"></sup>'
                : '';
              firstSource = false;
              const sourceChangeDiv = this.renderer.createElement('div');
              sourceChangeDiv.id = 'source_video_' + source.title;
              sourceChangeDiv.classList.add('fluid_video_source_list_item');
              sourceChangeDiv.innerHTML =
                '<span class="source_button_icon ' +
                sourceSelected +
                '"></span>' +
                source.title +
                hdElement;

              sourceChangeDiv.addEventListener('click', (event): void => {
                event.stopPropagation();

                const sourceIcons = video.parentElement.querySelectorAll(
                  '.source_button_icon'
                );
                sourceIcons.forEach((sourceIcon) => sourceIcon.classList.remove('source_selected'));
                event.target.firstChild.classList.add('source_selected');
                playerInstant.videoSources.forEach((videoSource) => {
                  if (
                    videoSource.title ===
                    event.target.innerText.replace(/(\r\n\t|\n|\r\t)/gm, '')
                  ) {
                    hls.loadLevel = source.url;
                    hls.currentLevel = source.url;
                  }
                });

                playerInstant.openCloseVideoSourceSwitch();
              });

              sourceChangeList.appendChild(sourceChangeDiv);
              appendSourceChange = true;

              if (appendSourceChange) {
                sourceChangeButton.appendChild(sourceChangeList);
                sourceChangeButton.addEventListener('click', () => {
                  playerInstant.openCloseVideoSourceSwitch();
                });
              } else {
                video.parentElement.querySelector(
                  '#video_fluid_control_video_source'
                ).style.display = 'none';
              }
            });
          });
        },
      },
    });

    this.fluidPlayer.openCloseVideoSourceSwitch = (): void => {
      const list = video.parentElement.querySelector(
        '#video_fluid_control_video_source_list'
      );
      if (list) {
        if (list.style.display === 'none') {
          list.style.display = 'block';
        } else {
          list.style.display = 'none';
        }
      }
    };
  }
}
```

**Comment by obumnwabude** [comment]
@Addvilz please its worth considering to add this as a feature in any next versions you deploy on fluidplayer. And preferably, add an `auto` option in the quality switcher, to switch to available qualitites (higher or lower) based on bandwidth, either in hls, dash, or plain video sources. Thank you

**Comment by HariPriyaKuberSingh** [comment]
@Barahten - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@Barahten - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .

**Comment by farmanalichanna** [comment]
this this issue resolved for HLS auto and quality selection menu when putting m3u8 file which support different quality with other paid players like JW but not with this player?

**Comment by leroybm** [comment]
Hello @farmanalichanna, unfortunately Fluid Player still doesn't have the quality switcher out of the box. You can add it as a custom feature like what was done in this comment https://github.com/fluid-player/fluid-player/issues/437#issuecomment-728925762

**Comment by HariPriyaKuberSingh** [comment]
@farmanalichanna  - Can you please confirm if the suggestion proposed by @leroybm helped in resolving the issue ?

**Comment by CodMark** [comment]
allowQualityMenu not showing in mobile how to fix
