### ISSUE TITLE
how off all ControlBar?

### ISSUE THREAD

**Issue by videositefree** [fluid-player/fluid-player#438]
Hi,
How to turn off the whole control panel? I want to display the poster and turn off the control panel because I want the mouse to start playing the video

<source src='1.mp4' type='video/mp4'>
                          </video>

                          <script>
                            myFluidPlayer.toggleControlBar(false);
                              var myFP = fluidPlayer(
                                  'video-id',
                                  {
                                    
                                      layoutControls: {
                                        toggleControlBar: false,
                              fillToContainer: true,
                              primaryColor: false,
                              posterImage: false,
                              autoPlay: false,
                              playButtonShowing: false,
                              playPauseAnimation: true,
                              control: false,
                              mute: false,
                              logo: {
                                imageUrl: null,
                                position: 'top left',
                                clickUrl: null,
                                opacity: 1,
                                mouseOverImageUrl: null,
                                imageMargin: '2px',
                                hideWithControls: false,
                                showOverAds: false
                              },
                              htmlOnPauseBlock: {
                                html: '', // Możliwość dodania strony która będzie wyświetlana podczas zatrzymania filmu
                                height: 100,
                                width: 200
                              },
                              allowDownload: false,
                              allowTheatre: true,
                              playbackRateEnabled: true,
                              controlBar: {
                                autoHide: false,
                                autoHideTimeout: 0,
                                animated: false
                              },
                                      },
                                      vastOptions: {
                                        adList: [
   
                                      ]
                                      }
                                  }
                              );

**Comment by Addvilz** [comment]
See documentation for `toggleControlBar` API method.  https://docs.fluidplayer.com/api/#togglecontrolbar

You can also use CSS method like 

```css
div.fluid_controls_container {
    display: none !important;
}
```
