### ISSUE TITLE
Ads events

### ISSUE THREAD

**Issue by Barahten** [fluid-player/fluid-player#439]
Are there any ways to get advertising events, at least the beginning of advertising and the end of advertising, regardless of what type is used by WAST or VPAID

**Comment by Addvilz** [comment]
Not from the current API, no. This is something we are planning for after 3.0 release.

**Comment by HariPriyaKuberSingh** [comment]
@bharath-exads - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Closing the ticket since there is no response from the reporter
