### ISSUE TITLE
Installation of the new version

### ISSUE THREAD

**Issue by machonatural** [fluid-player/fluid-player#44]
In wordpress repository  i find the version 1.1.0 but id like to install the last one via zipped github file,but the wordpress dont accept the zip file. ..so i set the folder via ftp into plugin but it ignores dont appear at plugin list. What happens?

**Comment by exoclick-florin-tudor** [comment]
Hello @machonatural,

The wordpress plugin for Fluid Player is up to date now, feel free to update your instance and use the new features it comes with.

**Comment by cian-exads** [comment]
Closing this issue as the plugin is on the latest version
