### ISSUE TITLE
Player size incorrect when on mobile screens.

### ISSUE THREAD

**Issue by Undefined-Variables** [fluid-player/fluid-player#442]
Hey guys, I love this player and have been using it for about 4 months now and until a couple of weeks ago it was working perfectly and would resize itself when opened on Android or iPhone mobile browsers. 

Then about 2 weeks ago we started seeing support tickets explaining the player was only showing 50% of the video width on mobile devices , nothing has been changed at all by our development team and old video's that once played and resized are now overflowing the small mobile screen and there is no way to adjust it from the users perspective. 

We have had to revert to an older HTML5 player which doesn't support vast to enable users to be able to view them but we have now lost our advertising income completely. Can anybody shine any light on what is going on here? My team for the first time are clueless! 

Thank you!

**Comment by Addvilz** [comment]
@Undefined-Variables we haven't had any releases since 2 months ago and even that one was not related to anything that could possibly cause this. Are you able to reproduce the issue somehow? Are you absolutely certain there was no changes in website layout, player container, some CSS maybe? Perhaps any specific device pattern to the user reports?

**Comment by Undefined-Variables** [comment]
@Addvilz Thank you for the reply. I thought this was the case but running out of ideas as to the course. 

I will have a proper in depth look this weekend but nothing has been changed at least as far as I know. Just strange as it was working lovely. 

Thanks again.

**Comment by Addvilz** [comment]
If you are able to reproduce it somehow, that would be helpful. Without the URL, I was not able to reproduce the issue.

**Comment by Addvilz** [comment]
@Undefined-Variables any update here? Did you identify the issue?

**Comment by Undefined-Variables** [comment]
Hey, sorry the problem is a bug my code, I have spent to long trying to debug so started coding the Controller and Model again. Only so much time you can spend on things. It will be much faster this way. Thank you for the reply and keep up the amazing work :)
