### ISSUE TITLE
How can i use ABR in fluidplayer

### ISSUE THREAD

**Issue by Nisarbabu** [fluid-player/fluid-player#443]
Hello team,

How can I use ABR in HLS & Dash with a resolution switcher?

**Comment by Addvilz** [comment]
Can you explain in more detail what are you trying to achieve? HLS & DASH streaming option does not support quality switching or quality preference at this time, except for using different playlists, which beats the purpose of ABR.

**Comment by Addvilz** [comment]
If I understand correctly, you want to switch quality dynamically using quality switcher button.

Related #437

**Comment by obumnwabude** [comment]
Yes @Addvilz switching quality with quality switcher button when video source is Hls or DASH will really be of great help

**Comment by HariPriyaKuberSingh** [comment]
@Nisarbabu - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Since there is no confirmation regarding the issue, we are currently closing the ticket.
