### ISSUE TITLE
Question about  - rel="noopener noreferrer" on mp4

### ISSUE THREAD

**Issue by crnidario** [fluid-player/fluid-player#446]
Where is the right place to put rel="noopener noreferrer" in fluidplayer code in order not to leave referrer on mp4 url, in this case - https://example.com/vid.mp4 ?
I tried 2 combination, take a look a screenshots:
![flid1](https://user-images.githubusercontent.com/40899639/82153298-e38d5d00-9866-11ea-8ebe-12006d23ad74.jpg)
![flid2](https://user-images.githubusercontent.com/40899639/82153302-e7b97a80-9866-11ea-8673-026f48a63787.jpg)
, but in both cases leaves referrer from domain A to domain B in this case (https://example.com/vid.mp4).
This is important for me  and I need your help.

**Comment by Addvilz** [comment]
This is really outside of scope of Fluid Player itself. Nevertheless.

To the best of my knowledge, HTML `rel` attribute only works for few select HTML elements, for example `a`, `form` and `link`. HTML5 video and related tags does not seem to support `rel` attributes, therefore doing what you want is not possible from video element itself.

It could be possible to use global `<meta name="referrer" content="origin">` tag in the page `<head>` itself to achieve what you want however I have not personally tested this and can not guarantee it works on all browser or works at all. You could also attempt to set `referrerpolicy="origin"` on `video` and/or `source` tags, as an alternative.

Consider however that this is relatively new feature and not all of your visitors might be using browsers with support for the referrer policy.

Relevant documentation:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
- https://html.spec.whatwg.org/multipage/urls-and-fetching.html#referrer-policy-attribute

**Comment by crnidario** [comment]
Thanks Addvilz for extensive answer.
 I solved problem on that way I putted in header:
header("Referrer-Policy: no-referrer")
Best regards
