### ISSUE TITLE
Fluid player controls don't autohide

### ISSUE THREAD

**Issue by StupidBacon** [fluid-player/fluid-player#45]
In pc the fluid player controls dont autohide when the mouse in in frame. This is especially annoying on mobile fullscreen when they cover 1/5th of the screen. Is there any way to fix this?

**Comment by cian-exads** [comment]
Hi @StupidBacon, thank you for bringing this to our attention. We are now reviewing this behavior on different browsers & devices and will hope to have improvements for this in one of our future releases.

**Comment by StupidBacon** [comment]
oh ok. Thank you. BTW I tested in chrome. On PC and android. both the control bar doesnt hide.

**Comment by kristijanexads** [comment]
@StupidBacon controls hiding issue is now sorted and available in Fluid Player version [v1.2.0](https://github.com/fluid-player/fluid-player/releases/tag/v1.2.0)

**Comment by EQuick78** [comment]
Same issue mouse cursor does not disappear and controls do not hide.

**Comment by cian-exads** [comment]
@EQuick78 can you provide me with a link to a test page I can see this happen?
