### ISSUE TITLE
Keeping theatre mode

### ISSUE THREAD

**Issue by vicetias** [fluid-player/fluid-player#451]
The theatre mode is actually nice but when you tap in any place on a page it gets easily disabled. Any way to keep the player fixed all the time without taps/clicks interrumptions? I mean, like YouTube's app... Also, is there a way to put theatre mode by default?

**Comment by Addvilz** [comment]
There is currently no way to do that with default theatre mode. You can use advanced mode to do this - https://docs.fluidplayer.com/docs/configuration/layout/#theatreadvanced
