### ISSUE TITLE
vast ads wont show

### ISSUE THREAD

**Issue by nochill99** [fluid-player/fluid-player#453]
hei, i was woundering if you guys could help me??. I have use a lot of cods but still my vast file wont work. do you guys have one that work with the new fluid player with auto player, banner html and vast link/vast fil??

**Comment by Addvilz** [comment]
All the working demo code is available in `/test/` folder of this repository. This is the same code we use in development to test the features of the player. 

Try see the console output in your browser for any hints and errors.
