### ISSUE TITLE
The ad skip button does not display properly.

### ISSUE THREAD

**Issue by hsex-tv** [fluid-player/fluid-player#454]
**Describe the bug**
The ad skip button does not display properly.

**To Reproduce**
**REDACTED**

**Expected behavior**
The ad skip button is hidden. Normally, you can click Skip after 5 seconds.

**Affected version**
For example, v3.0.0

**Comment by Addvilz** [comment]
Please provide a safe-for work reproduce code. Use JSFiddle or similar. 

Most likely it is because preRoll has no skip timer. Provide us with the VAST XML to reproduce the problem.

**Comment by hsex-tv** [comment]
发送自 Windows 10 版邮件应用

发件人: Matīss
发送时间: 2020年5月26日 15:00
收件人: fluid-player/fluid-player
抄送: hsex-tv; Author
主题: Re: [fluid-player/fluid-player] The ad skip button does not displayproperly. (#454)

Please provide a safe-for work reproduce code. Use JSFiddle or similar.
Most likely it is because preRoll has no skip timer. Provide us with the VAST XML to reproduce the problem.

**Comment by biguz** [comment]
I confirm this issue, skip button is hidden, vast file was transformed for test from real advertising network. Skip offset is present, skip button has display="none" attribute
Example with player and vast here
https://biguzplayer.com/30.html
https://biguzplayer.com/vast.xml

**Comment by Addvilz** [comment]
The only difference between this and the test XML we use is the offset format - `00:00:05.000` in your XML versus the `00:00:03` format we use. I suspect it might not be supported by the VAST parser despite being defined in VAST specification.

Either way, I will look into the XML and see why the skip is not showing up properly.

**Comment by biguz** [comment]
tried to use 00:00:03 format, button still hidden
https://biguzplayer.com/31.html
https://biguzplayer.com/vast1.xml

**Comment by Addvilz** [comment]
Thanks. I'll do some debugging.

**Comment by Addvilz** [comment]
This should now be fixed with the latest release.
