### ISSUE TITLE
Modifying displayOptions in React Integration

### ISSUE THREAD

**Issue by vishnupriyavr** [fluid-player/fluid-player#455]
Hi,
 
I want to change displayOptions (for example: allowTheatre)  in the player for react integration. I already went through the documentation but the react part doesn't talk about the options part..can someone please help and guide the steps to do this?
Thanks.

**Comment by Addvilz** [comment]
You can not change the options once the player has been initiated, same as any other non-reactive API - reactivity in React does not extend to Fluid Player. You need to keep options as a separate object in the React component and redraw the player to change the options.
