### ISSUE TITLE
why ads not showing?? here is the html code i used 

### ISSUE THREAD

**Issue by nochill99** [fluid-player/fluid-player#456]
why ads not showing?? here is the html code i used 

<video controls="" id="my-video" style="height: 360px; width: 640px;">
<source src="https://video.wixstatic.com/video/3a796d_898fb10868214981b911db142ca22883/360p/mp4/file.mp4" type="video/mp4"></source>
</video>

<script type="application/javascript">
var testVideo = fluidPlayer(
"my-video",
{
vastOptions: {
            allowVPAID: true, // Default false.
            adList: [
                {
                    roll: 'preRoll',
                    vastTag: '//script.yomeno.xyz/vpaid-fluid-patch/downloads/latest/vpaid-fluid-patch.min.js'
                },
                {
                    roll: 'midRoll',
                    vastTag: '//script.yomeno.xyz/vpaid-fluid-patch/downloads/latest/vpaid-fluid-patch.min.js',
                    timer: 5
                },
            ]
        }
    }
);
</script>

**Comment by biguz** [comment]
You should use xml vast, now you tried to use js script

**Comment by nochill99** [comment]
is there a way where i can use vast link

**Comment by Addvilz** [comment]
@biguz is indeed right - `vastTag` expects valid VAST XML URL. You have provided some kind of JavaScript. This would never work.
