### ISSUE TITLE
Responsive player

### ISSUE THREAD

**Issue by doublex** [fluid-player/fluid-player#460]
The player set `width` and `height` to `.fluid_video_wrapper` during init.
How can I make the player responsive (`width: 100%`)?
If I change the container later, e.g. by resizing the browser-window, the player should adapt.

**Comment by Addvilz** [comment]
See https://docs.fluidplayer.com/docs/configuration/layout/#filltocontainer

**Comment by doublex** [comment]
It does not create a responsive video-player.
If I resize the container **after creation** the video-player does not resize.

A solution could be a property  `fillToContainer: 16.0/9.0` which:
* sets `width: 100%`
* and `height: 9.0/16.0 of width`

**Comment by Addvilz** [comment]
Then that is a bug and you should submit a bug report. :)
