### ISSUE TITLE
Video not playing anymore. Timeout error.

### ISSUE THREAD

**Issue by drcluster** [fluid-player/fluid-player#462]
All the websites with FluidPlayer started to output in console:
[Error] (204): Timeout error. Failed to play video.

mp4 link provided to source is working good

Examples:
REMOVED

**Comment by Addvilz** [comment]
:warning: DO NOT link NSFW content in GitHub issues!

I checked the links and the videos load just fine for me on Firefox and Chrome. The timeout error is misleading - it just means the media playback was not started within allocated time period - usually because of buffering or other reasons.

**Comment by Addvilz** [comment]
You also seem to be using Fluid Player 2.4.11. v2 is end of support - you need to upgrade to v3.
