### ISSUE TITLE
How can I configure xhrSetup withCredentials property of hls.js?

### ISSUE THREAD

**Issue by Bogatinovski** [fluid-player/fluid-player#464]
How can I configure the `xhr` object of HLS.js to send cookies?

**Additional context**
I have `.m3u8 file` hosted with AWS Cloudfront and when playing the video I need to send my signed cookies to the cloudfront url so that I can access the private `.m3u8` file.
Hls.js provides the option to [customize the xhr request](https://github.com/video-dev/hls.js/blob/master/docs/API.md#xhrsetup) that will load the video files by using the `xhrSetup` property in the configuration. 
How can I access this configuration property from Fluid player ?

**Comment by Addvilz** [comment]
This looks like something that needs to be done before source is attached and immediately after HLS is created.

Currently there is no way to do this, but this is something we probably need to implement in form of callback to customize HLS once HLS is created but before attaching source or anything else. 

I see we could add a callback to root config object of Fluid Player for both DASH and HLS, with signature say something like `configureHLS(function(instance) {})`

PR is welcome if you feel like doing above.

**Comment by Bogatinovski** [comment]
I looked into the source code of the player and found out that there is a way to configure the hlsjs object, even though that is not documented in the documentation. Here is a working example of how to do it:
` fluidPlayer(this.$refs.myVideoPlayer, {
            layoutControls: {
            },
            hlsjsConfig: {
              xhrSetup: function(xhr) {
                xhr.withCredentials = true
              }
            }
          })`

**Comment by Addvilz** [comment]
Whoa, nice find! :partying_face: However, I would not rely on this forever - as far as I was able to tell from history, this is/was supposed to be internal configuration and not meant for use outside the player. I suspect that is why it was not documented. There seems to be plenty of this kind of stuff in the source base.

I will keep this ticket open because this feature will need some redesign - foreign libraries should be configurable nicely using some callback API and be properly documented.

**Comment by Bogatinovski** [comment]
Understood, thanks for the heads up! I will keep using it like this for now while in development but hopefully it will be fixed by the time we go to production with our software.

**Comment by Addvilz** [comment]
@Bogatinovski here's what you are looking for - https://docs.fluidplayer.com/docs/configuration/advanced/ , specifically `configureHls` callback.
