### ISSUE TITLE
[fluid-player-extended] shortcodes

### ISSUE THREAD

**Issue by hotvr** [fluid-player/fluid-player#47]
Good day,

I am pretty new to coding so I use shortcodes for now.
I installed the fluid player plugin on wordpress, so far the player is running and also working.
My only issue is, I want my video to be played in different quality.
I can't get the shortcodes working for multiple resolution.
so far this is the code i am using:

[fluid-player video=”xxx.mp4″ vast_file=”xxx.xml” layout=”default”]

Can someone please tell me the codes to include the different resolution change?

Thank you.

**Comment by cradonn** [comment]
@exoclick-florin-tudor should be able to help here.

**Comment by exoclick-florin-tudor** [comment]
@hotvr 
To use the multiple resolutions feature you need to use the extended shortcode version, have a look at the installation instructions, the nested "[fluid-player-multi-res-video]" shortcode does the trick:
 
https://wordpress.org/plugins/fluid-player/#installation

**Comment by hotvr** [comment]
thanks for the reply, I tried this extended code but it is not working for me. Could you give an example of an extended code if you don't mind?

Thank you and every help is appreciated.

**Comment by exoclick-florin-tudor** [comment]
Hello @hotvr, here's an example that works for me (took it from the Install instructions minus a typo), let me know if it works for you.

[fluid-player-extended
layout="funky"
auto-play="autoPlay"
logo="https://www.fluidplayer.com/images/yourlogo.png"
logo-position="top right"
logo-opacity=".8"
ad-text="adText"
ad-cta-text="adCTAText"
html-on-pause-block-width="100"
html-on-pause-block-height="100"
responsive="responsive"]

[fluid-player-multi-res-video]
    [
        {"label": "720", "url": "http://cdn.fluidplayer.com/current/examples/video.mp4"},
        {"label": "360", "url": "http://cdn.fluidplayer.com/current/examples/video360.mp4"}
    ]
[/fluid-player-multi-res-video]

[fluid-player-html-block]
    <div>
        <img src="https://www.fluidplayer.com/images/yourbanner.png"
    </div>
[/fluid-player-html-block]
[/fluid-player-extended]

**Comment by hotvr** [comment]
wow you sir are a beast, thank you very much, it works. Another question, do you know where I can put the vast code from exoclick for preroll ads?

Thank you.

**Comment by hotvr** [comment]
thank you very much, you guys are amazing. Big kiss

**Comment by Danny15** [comment]
All mentioned questions / support have been provided for this issue. Closing issue.
