### ISSUE TITLE
How to turn an external video link into a blob URL?

### ISSUE THREAD

**Issue by rthkdb** [fluid-player/fluid-player#475]
Impressive Video Player, Well Done!

But when I checked the docs, I got one question: how did you turn an external video link (like, the https://dash.akamaized.net/dash264/TestCases/1a/sony/DASH_vodvideo_Track1.m4v, which is one of the video sources of https://docs.fluidplayer.com/docs/streaming/dash) into a blob URL (blob:https://docs.fluidplayer.com/93ec9c4b-4e1e-4e7c-9035-8195aef8818b, when I checked the HTML Source) ?

I wonder how could I achieve this like you did?

**Comment by Addvilz** [comment]
Hi! Thank you! 

10.000ft overview would be, this is not done by player itself, it's done by the DASH streamer. In essence, what happens is that there are multiple videos available at different qualities with the playlist used to initialize the player. DASH streamer will try to show you the best quality video and it's done by reading and passing the video parts into the player by continuously reading them and passing the contents to video buffer.

The actual file passed to that player instance you linked to is this - https://dash.akamaized.net/dash264/TestCases/1a/sony/SNE_DASH_SD_CASE1A_REVISED.mpd

You can read more about DASH streaming here https://developer.mozilla.org/en-US/docs/Web/HTML/DASH_Adaptive_Streaming_for_HTML_5_Video
