### ISSUE TITLE
Any plans to support Google Ad Manager/ IMA SDK?

### ISSUE THREAD

**Issue by rgreen3400** [fluid-player/fluid-player#476]
Hi,
We love Fluidplayer but would like to use with Google ADX/ Google Ad Manager. Any plans to support this?
https://support.google.com/admanager/answer/186110?hl=en

Thanks...

**Comment by jianfai** [comment]
Just want to second that feature request.

**Comment by HariPriyaKuberSingh** [comment]
@rgreen3400  @jianfai  - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
@rgreen3400 @jianfai - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Closing this issue since there is no confirmation regarding the issue being reproducible

**Comment by FarisYaseen** [comment]
hello is this issue has been resolved ? is there a plug in can we use it ?
