### ISSUE TITLE
 cannot find fluidplayer.min.js

### ISSUE THREAD

**Issue by gorgolo** [fluid-player/fluid-player#477]
I downloaded the file but I cannot find fluidplayer.min.js
please help

**Comment by Addvilz** [comment]
Fluid Player is no longer distributed minified inside the repository.

**Comment by gorgolo** [comment]
Can only use official cdn?
<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
thank you so much

**Comment by Addvilz** [comment]
You can use official CDN or create your own build from sources using Webpack or something else. Fluid Player is now available in NPM as well - https://www.npmjs.com/package/fluid-player

**Comment by Addvilz** [comment]
Just a side note - do not download fluidplayer.min.js from the CDN and serve it from local. It will not work.
