### ISSUE TITLE
why is vast/ads not showing??

### ISSUE THREAD

**Issue by nochill99** [fluid-player/fluid-player#479]
why is vast/ads not showing??

<video id='my-video' controls style="width: 640px; height: 360px;">
    <source src='https://video.wixstatic.com/video/3a796d_865420335d1f499784ae015c5db38aae/1080p/mp4/file.mp4' type='video/mp4' />
</video>

<script>
 var myFP = fluidPlayer(
  'video-id',
  {
    vastOptions: {
     "adList" : [
   {
   "roll" : "preRoll",
   "vastTag" : "https://vast.yomeno.xyz/?tcid=1124&source=520195398&cap=15&promo=25894&cat_id=743"
   }
     ]
    }
  }
 );
</script>

<video id='my-video' controls style="width: 640px; height: 360px;">
    <source data-fluid-hd src='https://video.wixstatic.com/video/3a796d_865420335d1f499784ae015c5db38aae/1080p/mp4/file.mp4' title='1080p' type='video/mp4' />
    <source data-fluid-hd src='https://video.wixstatic.com/video/3a796d_865420335d1f499784ae015c5db38aae/1080p/mp4/file.mp4' title='720p' type='video/mp4' />
    <source src='vid_480p.mp4' title='https://video.wixstatic.com/video/3a796d_865420335d1f499784ae015c5db38aae/1080p/mp4/file.mp4' type='video/mp4' />
</video>

<script>
 var myFP = fluidPlayer(
  'video-id',
  {
    vastOptions: {
     "adList" : [
   {
   "roll" : "preRoll",
   "vastTag" : "https://vast.yomeno.xyz/?tcid=1124&source=520195398&cap=15&promo=25894&cat_id=743"
   }
     ]
    }
  }
 );
</script>

**Comment by Addvilz** [comment]
You did not enable VPAID.

```js
fluidPlayer('video-id', {
  vastOptions: {
    allowVPAID: true,
    adList: [{
      roll: "preRoll",
      vastTag: "https://vast.yomeno.xyz/?tcid=1124&source=520195398&cap=15&promo=25894&cat_id=743"
    }]
  }
});
```
