### ISSUE TITLE
Corrections to be applied on

### ISSUE THREAD

**Issue by machonatural** [fluid-player/fluid-player#48]
Hi guys, and specially Fiorin the developer

After the recent update the player started to work finally in my template but there is a few issues that remain yet:
in the desktop the video container becomes gray with the banner in the upleft corner. No way to close it. After update the page once or twice the video finallly appears.
This behavior happens in the mobile too, with the banner big ocuppying almost all the video area. The only way to play is to click ouside the banner.

when the video is playing in mobile the fullscreen button is placed over the timeline so its not possible to enlarge it.
When i post a video in the body of the post it , like an article it works perfectly with the banner appearing in center, in pause, etc. as meant to.

_**By the way this is a brand new installed template, there is no any kind of hack,**_

**Comment by exoclick-florin-tudor** [comment]
Hell @machonatural,
Could you provide us a link where we can test the issues you're experiencing?

**Comment by machonatural** [comment]
Right, heres a link
http://machosaonatural.com.br/dentista-taradao-faz-a-festa-com-paciente/

Update it twice or three to see the error

**Comment by exoclick-florin-tudor** [comment]
Hello @machonatural,
I checked the sample page, it doesn't seem  to be a FluidPlayer related issue. Doing a quick check noticed that the theme styling is conflicting with the way the banner is set, **.flex-video iframe** in foundation.min.css could be a starting point to debug your problem.

Hope it helps.

**Comment by machonatural** [comment]
Have no idea how to fix it. Thats the point. Wouldn´t you do it for a fee for example?
btw how can i set the video size in post body. Sometimes it goes very large and others it fits.

**Comment by cian-exads** [comment]
@machonatural are you still having the same issues regarding the plugin and player behaviour?

**Comment by Addvilz** [comment]
This seems out of date, closing. Please, reopen if this is still relevant.
