### ISSUE TITLE
Support for Companion creatives

### ISSUE THREAD

**Issue by Addvilz** [fluid-player/fluid-player#481]
Fluid Player currently does not support Companion ads. Fluid Player currently supports only 1 creative served, and it needs to be either linear or non-linear creative.

Companion creative support seems to be required by VAST 3.0 - TBD if it can/should be supported in Fluid Player.

Originally mentioned #480

**Comment by HariPriyaKuberSingh** [comment]
@Addvilz - Can you please confirm if the issues still persist ?

**Comment by HariPriyaKuberSingh** [comment]
@Addvilz - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment]
Since there is no response from the reporter , we are closing the ticket.
