### ISSUE TITLE
Fluid Player won't handle wrapper without <Creatives> section

### ISSUE THREAD

**Issue by Addvilz** [fluid-player/fluid-player#482]
We've made more tests and found that fluid won't handle wrapper without <Creatives> section fe

Working example

http://homafromptz.com/site_backups/vast_demo/working/
```
<VAST version="3.0">
    <Ad id="602833">
        <Wrapper>
            <AdSystem>Telemetry</AdSystem>
            <VASTAdTagURI>/vast.xml</VASTAdTagURI>
			<Creatives>
				<Creative></Creative>
			</Creatives>
        </Wrapper>
    </Ad>
</VAST>
```
Not working example

http://homafromptz.com/site_backups/vast_demo/notworking/
```
<VAST version="3.0">
    <Ad id="602833">
        <Wrapper>
            <AdSystem>Telemetry</AdSystem>
            <VASTAdTagURI>/vast.xml</VASTAdTagURI>
        </Wrapper>
    </Ad>
</VAST>
```

_Originally posted by @fedeveloperi81 in https://github.com/fluid-player/fluid-player/issues/480#issuecomment-649607227_

**Comment by HariPriyaKuberSingh** [comment]
@Addvilz  - can you please confirm if the issues still persist ?

**Comment by Addvilz** [comment]
@HariPriyaKuberSingh unless you have fixed it, it probably does

**Comment by leroybm** [comment]
Just tested this and it's not an issue anymore. Closing the issue.
