### ISSUE TITLE
Custom logo does not hide with the controls despite using hideWithControls: true

### ISSUE THREAD

**Issue by Addvilz** [fluid-player/fluid-player#485]
When we set the custom logo it does not hide with the controls despite using  hideWithControls: true, works perfectly fine for desktop but not for mobile(android with same specification above).

_Originally posted by @jessica-bc in https://github.com/fluid-player/fluid-player/issues/459#issuecomment-650808596_

**Comment by Addvilz** [comment]
Unable to reproduce - works as expected on mobile as well as on the desktop.

```
    var instance = fluidPlayer('fluid-player-e2e-case',{
        layoutControls: {
            controlBar: {
                autoHide:           true,
                autoHideTimeout:    3,
                animated:           true
            },
            logo: {
                imageUrl: 'https://picsum.photos/300/80', // Default null
                position: 'top right',
                hideWithControls: true
            }
        }
    });
```


https://ibb.co/gdbVqwP
https://ibb.co/JRYc22Z

**Comment by jessica-bc** [comment]
Hey, I forgot to recheck this and update, Im sorry but it is still not working, and on desktop as well in full screen only. I dont know why it is happening. I have reproduced this in the link below:
https://8maple.su/video/87757

Check this URL Please!
