### ISSUE TITLE
In video banner close button 'x' not closing the banner when clicked

### ISSUE THREAD

**Issue by jmendoza-es** [fluid-player/fluid-player#486]
**Describe the bug**
Once the banner appears, and gives you the option of closing it, it won't close when pressing the [x] button.

**To Reproduce**
Configuring VAST as follows:
```
"vastOptions": {
         "adList" : [{
         "valign" : "bottom", //only for In-Video
          "roll" : "preRoll",
          "vastTag" : "https://syndication.exoclick.com/splash.php?idzone=2933940",
          "nonlinearDuration" : "5",
           "timer" : "5"
    }]
}
```

**Expected behavior**
It should close the banner normally.

**Desktop (please complete the following information if relevant):**
 - OS: Mac Os
 - Browser Chrome, Firefox
 - Version -

**Affected version**
v3.0

**Comment by Linux534** [comment]
> **Describe the bug**
> Once the banner appears, and gives you the option of closing it, it won't close when pressing the [x] button.
> 
> **To Reproduce**
> Configuring VAST as follows:
> ```
> "vastOptions": {
>          "adList" : [{
>          "valign" : "bottom", //only for In-Video
>           "roll" : "preRoll",
>           "vastTag" : "https://syndication.exoclick.com/splash.php?idzone=2933940",
>           "nonlinearDuration" : "5",
>            "timer" : "5"
>     }]
> }
> ```
> 
> **Expected behavior**
> It should close the banner normally.
> 
> **Desktop (please complete the following information if relevant):**
>  - OS: Mac Os
>  - Browser Chrome, Firefox
>  - Version -
> 
> **Affected version**
> v3.0
>
