### ISSUE TITLE
Sef-host player

### ISSUE THREAD

**Issue by phansheng89** [fluid-player/fluid-player#487]
How to set up self-host version of the player please? There is no 'fluidplayer.min.js' file in the downloaded file.

Thank you.

**Comment by Addvilz** [comment]
We do not at this time distribute a minified version of Fluid Player. You either need to use CDN or use the NPM package with a bundler.

See #477 and my comment here https://github.com/fluid-player/fluid-player/issues/463#issuecomment-638137698

**Comment by phansheng89** [comment]
So, if I download the script, how to set up the player please?

I notice that using CND, fluid-player is blocked by Adblocker and it sometime fail loading too!

Thanks.

**Comment by Addvilz** [comment]
You need to build the player using a bundler/packager as part of your website deployment - ex. WebPack. 

As a sidenote, adblockers should not be blocking FluidPlayer itself. If you see it blocked by an adblocker, you should open an issue about it so we can investigate.

**Comment by phansheng89** [comment]
I’m using Wordpress, how to build it please? The Wordpress plugin is
outdated and function is really limited.

**Comment by Addvilz** [comment]
I am sorry, I can't help you with that. You should consult Wordpress directly on how to integrate 3rd party javascript from sources.
