### ISSUE TITLE
Fluid player shortcode not working in my wordpress dooplay theme 2.4.1

### ISSUE THREAD

**Issue by Adityaa2909** [fluid-player/fluid-player#488]
Hi please help me..
This is my website https://www.newwebseries.com/movies/wrong-turn/

I am putting short code of Fluid Player in my theme but it is not able to come on full screen. I have seen the responsive option both as true / responsive but it is not working. Now I have kept the responsive false. 

Please tell me how can I set the height and weight of the player in shortcode?

**Comment by Addvilz** [comment]
`div.pframe` is not properly sized, hence the player height can't be caclulated and it does not appear.

1. Set player to be responsive in config.
2. Do something like this https://github.com/fluid-player/fluid-player/blob/master/test/html/vod_reponsive.tpl.html

**Comment by Adityaa2909** [comment]
Please show me full details, I'm not master..

**Comment by Addvilz** [comment]
I am sorry, I am not able to help you further than I already have.

**Comment by Adityaa2909** [comment]
Please help me..  😟

**Comment by Addvilz** [comment]
I am sorry but we are not able to provide support and answers for questions unrelated to the project itself, namely your site and it's specifics.
