### ISSUE TITLE
360 equirectangular video, VR feature does not work as expected

### ISSUE THREAD

**Issue by marlin-dev** [fluid-player/fluid-player#490]
The initial play of video starts on muted mode when showCardBoardView is set to true. Secondly not able to move around in video, only possible with joysticks on the left-up side. the video keeps replaying after it finishes. Could you please give me some hints on this, I am trying to achieve this:

https://fluidplayer-exads.firebaseapp.com/html/vr.html

Thanks a lot!

**Comment by Addvilz** [comment]
You are using Fluid Player version 2 - it is no longer supported. Please, try with version 3 - if you are still facing the same issues, please submit another ticket. Please also fill *all the required sections in the bug report template* - including your browser, environment details and potentially screenshots illustrating the problem.
