### ISSUE TITLE
Play button showing after the initial play

### ISSUE THREAD

**Issue by skallet** [fluid-player/fluid-player#494]
**Describe the bug**
If you apply the setting for `playButtonShowing` to `true` I expect that after pausing the video play button will reappear.

**To Reproduce**
1. Apply setting [`layoutControls.playButtonShowing`](https://docs.fluidplayer.com/docs/configuration/layout/#playbuttonshowing).
2. Click play.
3. Click pause.
4. The play button should reappear.

**Expected behavior**
Every time the video is paused play button should be shown if set.

**Affected version**
v3.0.0

**Additional context**
Not sure about arguments that play button is hidden after initial play, but to me, it seems this case should be configurable at least with another setting value if not the same. I have prepared PR if this will be resolved as a bug.

**Comment by HariPriyaKuberSingh** [comment]
@skallet - Can you please confirm if the issues persist or is resolved?

**Comment by HariPriyaKuberSingh** [comment]
@skallet - Can you please confirm if the issues persist or is resolved?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
