### ISSUE TITLE
Public API to change video source

### ISSUE THREAD

**Issue by skallet** [fluid-player/fluid-player#495]
**Is your feature request related to a problem? Please describe.**
In version 2 it was possible to control the currently selected video source for changing quality. It could be used by page application to switch into lower QT when browser connectivity changed. Or mounting other elements on the webpage to control quality options.

**Describe the solution you'd like**

1. List available video sources `player.getSources();`
2. Check currently played video source `player.getActiveSource(); // => [{isHD: true, url: "http://.."}]`
3. Switch source (should switch only if a new source is part of available source) `player.setActiveSource(source);`
4. An event called when the source is changed (currently there is no way to show HD/nonHD icon) `player.on('sourceChange', ...);`

**Describe alternatives you've considered**
After hiding private variables of the player there is no way to control sources.

**Comment by HariPriyaKuberSingh** [comment]
@skallet - Can you please confirm if the issues persist or is resolved

**Comment by HariPriyaKuberSingh** [comment]
@skallet - Can you please confirm if the issues persist or is resolved

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
