### ISSUE TITLE
Timeline previews on phone

### ISSUE THREAD

**Issue by skallet** [fluid-player/fluid-player#496]
On mobile devices when viewing previews you can't prevent video skipping (rewinding). I am expecting that if thumbnails are available only after `touch end` video will rewind into the desired position, it will save users bandwidth. Is this a bug, or should be considered as an enhancement?

**Comment by skallet** [comment]
@Addvilz can I make PR or someone else have been working on this?

**Comment by Addvilz** [comment]
@skallet nobody is working on this yet, PR is welcome!

**Comment by HariPriyaKuberSingh** [comment]
@skallet - Can you please confirm if this issue is addressed ?

**Comment by HariPriyaKuberSingh** [comment]
@skallet - Can you please confirm if this issue is addressed ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
