### ISSUE TITLE
Add time display for vtt preview.

### ISSUE THREAD

**Issue by andyzhou** [fluid-player/fluid-player#498]
**Is your feature request related to a problem? Please describe.**
About the vtt preview, when i review the frame, can't know the time line of  each frame image. I want like youtube, display time under frame image.

**Describe the solution you'd like**
I want add the frame time line can display under frame image, time format like "03:12".

**Describe alternatives you've considered**
I have a idea is add time info per sprite frame image.

**Comment by HariPriyaKuberSingh** [comment]
@andyzhou - can you please confirm if the issue is resolved ?

**Comment by HariPriyaKuberSingh** [comment]
@andyzhou - can you please confirm if the issue is resolved ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
