### ISSUE TITLE
HLS / M3u8 + Vast and Logo Question

### ISSUE THREAD

**Issue by 30amedia** [fluid-player/fluid-player#499]
HI all 
We have been using the player with good success for our streaming RTMP server which outputs m3u8 streams 
The player is robust and stable 
however, we have not had success using the wordpress plugin or fluidplayer extended commands for 
A) Logo display ( ideally lower third  
B) VAST xml or advert display 
Again this question is about HLS streaming 
Can anyone advise / suggest next steps ?

**Comment by Addvilz** [comment]
I am sorry, I do not follow - what exactly are you asking?

The logo display is documented at https://docs.fluidplayer.com/docs/configuration/layout/#logo
HLS documentation is available at https://docs.fluidplayer.com/docs/streaming/hls/
And VAST integration guide is available at https://docs.fluidplayer.com/docs/configuration/ads/

About WordPress plugin - the currently published version of it is not supported. We are currently working on rebuilding this plugin from scratch.

**Comment by 30amedia** [comment]
Thanks for the reply
I am familiar with the documentation
however the question is:
In hls player -- ability to add logo -- extension coding  does not seem to work in live streaming player

**Comment by Addvilz** [comment]
Okay, if I understand correctly, you mean the logo does not appear when player is reproducing live streams?

FYI the live streaming capability has not been really all that well tested, especially together with VAST. Although technically supported, I would not say it's stable at this point.

**Comment by 30amedia** [comment]
Thanks for the reply and info. Please in future developments we would love to help 
We have had good success and stability with hls pure stream RTMP broadcast 
thus having logo and or vast would be great options. Glad to supply test accounts for use in development
Thanks again

**Comment by HariPriyaKuberSingh** [comment]
@30amedia - Can you please confirm if the issues are addressed ?

**Comment by 30amedia** [comment]
HI -- we had to move on to other projects. Let us know if you have VAST advert tag insertion option (live stream rtmp or HLS)

**Comment by fgfff12345** [comment]
everything is just ELITE VIDEO PLAYER example  demo [http://easy-chocolate.gifca1.ru/2021/05/14/ru-tv/](url) only 5 dollars  write  f9fff12345@yandex.ru

**Comment by 30amedia** [comment]
> everything is just ELITE VIDEO example demo easy-chocolate.gifca1.ru/2021/05/14/ru-tv/ video player plugin wordpress only 5 dollars write [f9fff12345@yandex.ru](mailto:f9fff12345@yandex.ru)

Show me english url please

**Comment by fgfff12345** [comment]
olegasan204@gmail.com

**Comment by fgfff12345** [comment]
> > все просто ЭЛИТНОЕ ВИДЕО пример демо easy-chocolate.gifca1.ru/2021/05/14/ru-tv/ плагин видеоплеера wordpress всего 5 долларов пишите [f9fff12345@yandex.ru ](mailto:f9fff12345@yandex.ru)
> 
> Покажи мне английский URL, пожалуйста

olegasan204@gmail.com

**Comment by fgfff12345** [comment]
> > > все просто ЭЛИТНОЕ ВИДЕО пример демо easy-chocolate.gifca1.ru/2021/05/14/ru-tv/ плагин видеоплеера wordpress всего 5 долларов пишите  [f9fff12345@yandex.ru  ](mailto:f9fff12345@yandex.ru)
> > 
> > 
> > Покажи мне английский URL, пожалуйста
> 
> [olegasan204@gmail.com ](mailto:olegasan204@gmail.com)

http://code.gifca1.ru/%d0%b7%d0%be%d1%8f-feat-%d1%81%d0%b5%d1%80%d0%b3%d0%b5%d0%b9-%d1%88%d0%bd%d1%83%d1%80%d0%be%d0%b2-%d0%bc%d0%b0%d0%bd%d0%b8%d1%84%d0%b5%d1%81%d1%82/  player work
