### ISSUE TITLE
Have an error Refused to execute script from 'https://dsp-test.decenterads.com/static/video.mp4' because its MIME type ('video/mp4') is not executable.

### ISSUE THREAD

**Issue by vlaktion** [fluid-player/fluid-player#504]
<VAST
 
version
="
2.0
"
>
<Ad
 
id
="
V
"
>
<InLine
>
<AdSystem
>
SR
</AdSystem
>
<AdTitle
>
V
</AdTitle
>
<Impression
>
https://supply.decenterads.com/?c=v&m=i&h=abccef36feababd3c3d19ad25e17af25
</Impression
>
<Impression
>
http://dsp-test.decenterads.com/?c=rtb&m=b&key=8460bfd810c295bfdeeef7b6a57b9776&cp=1.3938481783246515
</Impression
>
<Creatives
>
<Creative
 
sequence
="
1
"
>
<Linear
 
skipoffset
="
00:00:05
"
>
<TrackingEvents
>
<Tracking
 
event
="
creativeView
"
>
https://supply.decenterads.com/?c=v&m=e&t=creativeView&h=abccef36feababd3c3d19ad25e17af25
</Tracking
>
<Tracking
 
event
="
start
"
>
https://supply.decenterads.com/?c=v&m=e&t=start&h=abccef36feababd3c3d19ad25e17af25
</Tracking
>
<Tracking
 
event
="
midpoint
"
>
https://supply.decenterads.com/?c=v&m=e&t=midpoint&h=abccef36feababd3c3d19ad25e17af25
</Tracking
>
<Tracking
 
event
="
firstQuartile
"
>
https://supply.decenterads.com/?c=v&m=e&t=firstQuartile&h=abccef36feababd3c3d19ad25e17af25
</Tracking
>
<Tracking
 
event
="
thirdQuartile
"
>
https://supply.decenterads.com/?c=v&m=e&t=thirdQuartile&h=abccef36feababd3c3d19ad25e17af25
</Tracking
>
<Tracking
 
event
="
complete
"
>
https://supply.decenterads.com/?c=v&m=e&t=complete&h=abccef36feababd3c3d19ad25e17af25
</Tracking
>
<Tracking
 
event
="
skip
"
>
https://supply.decenterads.com/?c=v&m=e&t=skip&h=abccef36feababd3c3d19ad25e17af25
</Tracking
>
<Tracking
 
event
="
start
"
>
http://dsp-test.decenterads.com/?w=i&p=1.8265012271310659&uq=cf3aa800e3cdae0f5038089d1c48f281&t=v
</Tracking
>
<Tracking
 
event
="
start
"
>
http://dsp-test.decenterads.com/?w=i&p=2.811&uq=0d6c409cf9956f929df79ec06da620a3&t=v
</Tracking
>
<Tracking
 
event
="
start
"
>
https://dsp-test.decenterads.com/i?clid=vls&paid=sh&dvid=v&avid=Stream_IA_%241.5_11.06_Vpaid_5ee2303e56cb0a0001cd1fdb_asis_dup&caid=14348&plid=14348|0&publisherId=303&siteId=a9M6CaTvK18AJxF6R&priceBid=3&pricePaid=1&lineItemId=[LI_ID]&kv1=320x480&kv2=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.launcher.smart.android&kv3=7933f0775bc65af5c08c3d7c0d1a55f6b8b43d3533be8430b76e971b5ec0ac80&kv4=69.140.194.241&kv7=16467&kv11=8bd9ce99af590755dec2a344b2123189&kv12=1594711643&kv15=USA&kv16=39.1564&kv17=-75.4955&kv18=com.launcher.smart.android&kv19=430f553d-5989-4d6b-b6a6-21e68b5d9eea&kv23=Comcast Cable&kv28=Samsung SM-G928T&kv25=com.launcher.smart.android&kv26=android&kv27=Mozilla%2F5.0 (Linux%3B Android 7.0%3B SM-G928T Build%2FNRD90M) AppleWebKit%2F537.36 (KHTML%2C like Gecko) Version%2F4.0 Chrome%2F76.0.3809.111 Mobile Safari%2F537.36&kv9=[C_LENGTH]&kv10=Comcast Cable&kv13=14348|0&kv14=[MRAID_V]&kv29=[ERRORCODE]&kv30=[CONTENTPLAYHEAD]_[ADPLAYHEAD]&kv33=[ASSETURI]&kv34=[VASTVERSIONS]&kv35=[IFATYPE]&kv36=430f553d-5989-4d6b-b6a6-21e68b5d9eea&kv37=[CLIENTUA]&kv38=[SERVERUA]&kv39=[DEVICEUA]&kv40=[DEVICEIP]&kv41=[LATLONG]&kv42=none&kv43=[PAGEURL]&kv44=[VIDEO_TYPE]&kv45=[PLAYERSIZE]&kv46=[REGULATIONS]&kv47=[ADTYPE]&kv48=[TRANSACTIONID]&kv49=[BREAKPOSITION]&kv50=[APPNAME]&kv51=[PLACEMENTTYPE]&kv52=0&kv24=MobileInApp_Video
</Tracking
>
</TrackingEvents>
<Duration
>
00:00:25
</Duration
>
<MediaFiles
>
<MediaFile
 
delivery
="
progressive
"
 
width
="
480
"
 
height
="
360
"
 
bitrate
="
10
"
 
type
="
video/mp4
"
>
https://dsp-test.decenterads.com/static/video.mp4
</MediaFile
>
</MediaFiles>
<AdParameters
>
{"m":"e9f_6b6","h":"ip-172-31-92-188","w":{"t":[{"t":1,"a":[{"i":"5f0c252cc152e50001a68985","u":"https://dsp-test.decenterads.com/advast?p=22336512&w=4&h=3&ifa=[IFA]&ua=Mozilla%2F5.0 (Linux%3B Android 7.0%3B SM-G928T Build%2FNRD90M) AppleWebKit%2F537.36 (KHTML%2C like Gecko) Version%2F4.0 Chrome%2F76.0.3809.111 Mobile Safari%2F537.36&bundle=[BUNDLE_ID]&lat=[USER_LAT]&long=[USER_LON]&lmt=[DO_NOT_TRACK]&minduration=1&maxduration=60&referrer=[APP_STORE_URL]&vast_version=3&vpaid_version=2&video_format_type=instream&GDPR=[USER_CONSENT]&player_width=[WIDTH]&player_height=[HEIGHT]&schain=&us_privacy=[US_PRIVACY]","e":1,"t":[{"event":"AdImpression","type":"img","url":"https://dsp-test.decenterads.com/i?clid=vls&paid=sr&dvid=v&avid=Specto_IA_%242.5_Star_13.07_%243.44_22336512&caid=5f0c252cc152e50001a68985&lineItemId=5ee2303e56cb0a0001cd1fdb&kv7=Smart_IA_%241.5_11.06_Vpaid_5ee2303e56cb0a0001cd1fdb&kv1=300x250&kv2=[PAGE_URL]&kv4=69.140.194.241&publisherId=5eb808368cac9100019971b6&kv11=[IMPRESSION_ID]&kv12=[PLACEMENT_ID]&kv16=39.1564&kv17=-75.4955&kv18=com.launcher.smart.android&kv19=430f553d-5989-4d6b-b6a6-21e68b5d9eea&kv27=Mozilla%2F5.0 (Linux%3B Android 7.0%3B SM-G928T Build%2FNRD90M) AppleWebKit%2F537.36 (KHTML%2C like Gecko) Version%2F4.0 Chrome%2F76.0.3809.111 Mobile Safari%2F537.36&kv24=Mobile_InApp_Video","sample":100,"env":"mobile_app"}],"r":"N3L0Uw","c":"NHL0Uw","b":"com.launcher.smart.android","dr":"2.50"}]}],"r":"p"},"qs":{"app_category":"IAB1,IAB3,IAB9","app_name":"com.launcher.smart.android","app_store_url":"https://play.google.com/store/apps/details?id=com.launcher.smart.android","br":"chrome mobile webview","brv":"76","bundle_id":"com.launcher.smart.android","cb":"1594711645452568129","cc":"UA8","dt":"mobile","env":"ma","gdpr":"0","height":"250","ifa":"430f553d-5989-4d6b-b6a6-21e68b5d9eea","ip":"69.140.194.241","ns":"0","org":"571726dabc28330002000007","os":"android","osv":"7.0","sid":"gqv2qMjCt3yP9c2y1QE","sjs":"2050","sta":"MD","tc":"5ee2303e56cb0a0001cd1fdb","tcc":"NHL0Uw","ua":"Mozilla/5.0 (Linux; Android 7.0; SM-G928T Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/76.0.3809.111 Mobile Safari/537.36","uc":"0","user_lat":"39.1564","user_lon":"-75.4955","width":"300"},"c":{"bl":"991","sid":"gqv2qMjCt3yP9c2y1QE","b":"ai","do":{"e":"https://dsp-test.decenterads.com/s2","c":"https://dsp-test.decenterads.com/x","s":"sdk.wolseri.com","f":"ff.streamrail.net","fm":"ffcdn.streamrail.net"}},"z":{"ac":"1","aw":1,"blf":"3020","la":"7","r1":"5b6fc747f9d6349c32d8186588142397","rs":"3299","rw":"320","ts":"zrn0UA"}}
</AdParameters
>
</Linear>
</Creative>
</Creatives>
</InLine>
</Ad>
</VAST>

**Comment by Addvilz** [comment]
??? Please, reformat your question and submit another issue.
