### ISSUE TITLE
Fast/Forward element too close together

### ISSUE THREAD

**Issue by phansheng89** [fluid-player/fluid-player#505]
When enabled controlForwardBackward, the element is too close together and really hard to use even on desktop, it seems impossible to click correctly on mobile screen!

**Expected behavior**
The iPhone way for example is more userfriendly.

https://imgur.com/xYTHwwG

**Affected version**
v3.0.0

**Comment by HariPriyaKuberSingh** [comment]
@phansheng89 - Can you please confirm if the issues persist ?

**Comment by HariPriyaKuberSingh** [comment]
@phansheng89 - Can you please confirm if the issues persist ?

**Comment by HariPriyaKuberSingh** [comment]
@phansheng89 - Can you please confirm if the issues persist ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
