### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by vixeven** [fluid-player/fluid-player#506]

**Comment by Addvilz** [comment]
What are you requesting here? SSR as in server side rendering?

**Comment by vixeven** [comment]
Yes, **S**erver **S**ide **R**endering Support.


Here is [an attempt](https://github.com/vercel/next.js/discussions/15957) to integrate it with Next.js (SSR React Framework):
https://codesandbox.io/s/fervent-montalcini-i690v?file=/pages/index.tsx

**Comment by Addvilz** [comment]
Specific framework integration is out of scope for this issue tracker. You should reffer to the documentation of the specific framework you are using.

That being said, Fluid Player is a video media player - it is not meant to be server-side rendered - it simply will not work in principle. You need to expose the FluidPlayer code to the frontend and it needs access to the browser to work.
