### ISSUE TITLE
VTT problem with Access-Control-Allow-Credentials expecting True

### ISSUE THREAD

**Issue by Kuuzou-cl** [fluid-player/fluid-player#507]
I can't manage to make VTTs work, I was reading other issues like this one #58 .
This is the console error that I'm getting

`Reason: expected ‘true’ in CORS header ‘Access-Control-Allow-Credentials’`

I already change my Access-Control-Allow-Origin from * to my domain but i don't know how to fix this error, Is there any way to change this header to optional, if so, how? I'm not sure but is this [XHR Config](https://docs.fluidplayer.com/docs/configuration/advanced/#xhr-configuration) related to my problem? I appreciated any advice.

**Comment by Addvilz** [comment]
The error message explains it all - you want to send value `true` in `Access-Control-Allow-Credentials` along with `Access-Control-Allow-Origin` header - by the way, value `*` will not work with credentials permitted.

By default Fluid Player will send credentials along with the XHR requests. If this is not something you want, you can disable that in `onBeforeXMLHttpRequest`, setting `request.withCredentials` to false for URLs that you don't need them sent to.
