### ISSUE TITLE
Video types [wmv,flv,avi and 3gp] are not rendering in fluid player

### ISSUE THREAD

**Issue by deepak-sahu-pubmatic** [fluid-player/fluid-player#508]
wmv,flv,avi and 3gp video types are not getting rendered in fluid version.

We are passing a VAST with one of the above media type but ad is not rendering and getting below error. Please refer attached VAST for reference.

Ad error: AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.

**Expected behavior**
wmv,flv,avi and 3gp video types should also be played/supported.

**Affected version**
3.0.0

Please Note : Player is playing mp4,mov and mkv video formats.
[vast_MediaTypeAVI.txt](https://github.com/fluid-player/fluid-player/files/5090483/vast_MediaTypeAVI.txt)

**Comment by Addvilz** [comment]
Media content support is **browser dependent**, it has little to nothing to do with Fluid Player itself.

As a sidenote, none of the formats you listed are advisable to be used for web consumption. 

WMV is Windows-specific video format that could ever only be reproduced inside IE using proprietary media player embedding, FLV is Flash Video - pretty much a dead format at this point, AVI can't contain H264 or any other sane codec without hacks, and 3gp is obsolete format as far as modern web is concerned.
