### ISSUE TITLE
my fluid player is not showing ads

### ISSUE THREAD

**Issue by vmgroup27** [fluid-player/fluid-player#509]
`<!DOCTYPE html>
<html>
<head>
  <title>hello</title>
 <script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<style>
  fluidPlayer(
   'my-video',
    {
        layoutControls: {
            primaryColor:           false,
            playButtonShowing:      true,
            playPauseAnimation:     true,
            fillToContainer:        false,
            autoPlay:               true,
            preload:                false,
            mute:                   false,
            doubleclickFullscreen:  true,
            subtitlesEnabled:       false,
            keyboardControl:        true,
            layout:                 'default',
            allowDownload:          true,
            playbackRateEnabled:    false,
            allowTheatre:           true,
            title:                  true,
            loop:                   false,
            logo: {
                imageUrl:           null,
                position:           'top left',
                clickUrl:           null,
                opacity:            1
            },
            controlBar: {
                autoHide:           true,
                autoHideTimeout:    3,
                animated:           true
            },
            timelinePreview:        {},
            htmlOnPauseBlock: {
                html:               null,
                height:             null,
                width:              null
            },
            playerInitCallback:     (function() {})
        }
    }
);
</style>

<style type="text/css">
 fluidPlayer(
    'video-vpaid-ads',
    {
        vastOptions: {
            allowVPAID: true,
            adList: [
                {
                    roll: 'preRoll',
                    vastTag: 'https://www.videosprofit.com/watch.xml?key=c74f8480708ec604ee2965da12e7de5c'
                },
                {
                    roll: 'midRoll',
                    vastTag: 'https://www.videosprofit.com/watch.xml?key=c74f8480708ec604ee2965da12e7de5c',
                    timer: 5
                },
            ]
        }
    }
);
</style>
</head>
<body>

<div>
<video id='my-video' controls style="width: 640px; height: 360px;">
    <source src="https://www.dropbox.com/s/0bz68uvqt7z5sjs/Nissan-Terrano.MP4?raw=1" type="video/mp4"/>
</video>
</div>
<script type="text/javascript">
var player = fluidPlayer(
   'my-video',
    {
        layoutControls: {
            // Parameters to customise the look and feel of the player
        },
        vastOptions: {
            // Parameters to customise how the ads are displayed & behave
        }
    }
);
</script>

<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<script>
  <script>
    // fluidPlayer method is global when CDN distribution is used.
    var player = fluidPlayer('my-video');
</script>
</body>
</html>`

**Comment by Addvilz** [comment]
See console output for potential errors.
