### ISSUE TITLE
Is there any way to disable fluid player logging in console?

### ISSUE THREAD

**Issue by deepak-sahu-pubmatic** [fluid-player/fluid-player#510]
We are using fluid player 3.0.4 through npm build. There are logging by fluid player in browser console, is there any way we can disable/enable the logging.

Below are the steps we following to use fluid player :
npm install fluid-player@^3.0.0
import fluidPlayer from 'fluid-player';
@import "~fluid-player/src/css/fluidplayer.css";
var player = fluidPlayer(target , options);

**Comment by Addvilz** [comment]
Define logging? You mean development log? In theory, it should pick up your build settings automatically - webpack build for prod will not produce debug output.

If that does not work for some reason, use DefinePlugin - see 

https://github.com/fluid-player/fluid-player/blob/master/webpack.config.js

Something like this:

```
           FP_BUILD_VERSION: '3', // Anything you want
           FP_HOMEPAGE: 'https://fluidplayer.com', //Anything you want
           FP_ENV: 'production',
           FP_DEBUG: 'false',
```
