### ISSUE TITLE
[iOS-14 Safari iPhone 11] In full screen mode forward and rewind buttons and enabled and functioning. 

### ISSUE THREAD

**Issue by deepak-sahu-pubmatic** [fluid-player/fluid-player#515]
**Describe the bug**
We are testing vast in iOS-14 Safari iPhone 11 while testing we observed :
1> Maximize button in enabled while ad is playing. In other players (as mentioned below, maximize button is not enabled in iPhone safari)
2> In maximized mode, forward and rewind buttons are enabled and functioning. User is able to forward and rewind the video ad. It should not happen. 

**Affected version**
v3.0.4

**Additional context**
Other players where maximize button is not visible in iPhone 11-iOS-14 Safari browser. It is further avoiding to display of forward and rewind button.

https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector

https://flowplayer.com/developers/tools/ad-tester

PFA
![ActiveForwardAndRewindButtons](https://user-images.githubusercontent.com/66722481/91292078-a44ea080-e7b3-11ea-98d5-d2d4bfe8a257.png)

**Comment by Addvilz** [comment]
> Maximize button in enabled while ad is playing. In other players (as mentioned below, maximize button is not enabled in iPhone safari)

Works as designed - ad might start playback after a time delay, in the middle of video and when the video is already fullscreen.

> In maximized mode, forward and rewind buttons are enabled and functioning. User is able to forward and rewind the video ad. It should not happen.

These are controls are provided by iOS, not Fluid Player. Fluid Player on iOS does not use false-fullscreen to avoid issues with user interactions while in fullscreen. Therefore, iOS UX is used in fullscreen and Apple does not allow for scrubbing to be disabled.

**Comment by deepak-sahu-pubmatic** [comment]
> These are controls are provided by iOS, not Fluid Player. Fluid Player on iOS does not use false-fullscreen to avoid issues with user interactions while in fullscreen. Therefore, iOS UX is used in fullscreen and Apple does not allow for scrubbing to be disabled.

Hi @Addvilz ,
Is there anyway to disable forward and rewind button during ad playback? 
The reason is these controls are being used by the users to forward the ad and this it affecting the ad view-ability.
If not now then could we please look at it's feasibility in future.

Thank you.

**Comment by Addvilz** [comment]
These controls are controlled by **iOS** - there is no way for us to do anything about it.

**Comment by deepak-sahu-pubmatic** [comment]
> These controls are controlled by **iOS** - there is no way for us to do anything about it.

Okay.
Thank you @Addvilz for your quick reply.
