### ISSUE TITLE
State of buffer

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [fluid-player/fluid-player#52]
Hi, Thanks for this awesome player.
I need a feature.  Other players have a line that show, how much of video downloaded and buffered, I think its good idea to add this feature to Fluid player.
Thanks
![screenshot from 2017-10-23 02-34-37](https://user-images.githubusercontent.com/17345129/31867364-fdc49f30-b79a-11e7-8872-0292097920a3.png)

**Comment by cian-exads** [comment]
Hi @AmirHosseinKarimi, we're happy to hear you're enjoying Fluid Player. We appreciate your feedback and will be considering your mentioned feature, thank you. Stay tuned for upcoming improvements!

**Comment by AmirHosseinKarimi** [comment]
Thanks. I'll work on it if i can and if i got free time.

**Comment by golikov** [comment]
Available since v2.0.0
