### ISSUE TITLE
Two taps required on mobile unless playButtonShowing: false

### ISSUE THREAD

**Issue by donwilson** [fluid-player/fluid-player#520]
**Describe the bug**
Mobile (specificlaly iOS) requires two taps to get the video started playing. Desktop only requires one click

**To Reproduce**
1. Go to any video where playButtonShowing is not set to false
2. Click on big play button
3. Second tap required to start video

**Expected behavior**
Single tap required to start video (considering play button is on screen)

**Screenshots or Links**
While on mobile navigate to https://www.fluidplayer.com/ - player at bottom of page, check "Show play button"

**Desktop (please complete the following information if relevant):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest

**Smartphone (please complete the following information if relevant):**
 - Device: iPhone XS Max
 - OS: iOS 13
 - Browser: Safari

**Affected version**
v2 (current), v3 (current)

**Additional context**
None

**Comment by Daisum** [comment]
I think this is a duplicate of my issue: https://github.com/fluid-player/fluid-player/issues/511

**Comment by donwilson** [comment]
Can confirm this is a duplicate of #511
