### ISSUE TITLE
Controls API in v3.0.4 not working [FP_ERROR] Playback error DOMException

### ISSUE THREAD

**Issue by det66** [fluid-player/fluid-player#522]
var player = fluidPlayer('thisPlayer');
 				player.pause();

does not pause the player but gives an error in console log:

[FP_ERROR] Playback error DOMException: The play() request was interrupted by a call to pause().
(anonymous) @ fluidplayer.min.js:8
Promise.catch (async)
i.play @ fluidplayer.min.js:8
i.play @ fluidplayer.min.js:8
t.playPauseToggle @ fluidplayer.min.js:8
t.initialPlay @ fluidplayer.min.js:8
play (async)
i.play @ fluidplayer.min.js:8
i.play @ fluidplayer.min.js:8
t.playPauseToggle @ fluidplayer.min.js:8
n @ fluidplayer.min.js:8

**Expected behavior**
Pause the player with no console error

**Smartphone **
 - Device: Samsung Galaxy S10, Chrome mobile emulation
 - Browser Chrome
 - Version 85.0.4183.83

**Affected version**
 v3.0.4

**Additional context**
Working with Fluidplayer 2.4.11

**Comment by Addvilz** [comment]
```
var player = fluidPlayer('thisPlayer');
player.pause();
```
Not a bug. Why are you even pausing the player immediately after initialization?
