### ISSUE TITLE
Controls API in v3.0.4 not working [FP_ERROR] Playback error DOMException 2nd try

### ISSUE THREAD

**Issue by det66** [fluid-player/fluid-player#523]
<script>
			var player = fluidPlayer('thisPlayer');
			var playfromad = false;
			player.on('play', function() {
				if(playfromad == false){
					$("#body_overlay").remove();
					var body_overlay = $("#body_overlay_template").clone();
					body_overlay.attr("id", "body_overlay");
					$("body").prepend(body_overlay);
					body_overlay.show();
					$("#box_content").show();
					$("#player_thinge").hide();
					player.pause();
				}
				//playfromad = false;
			});
			$("#player_thinge").click(function(){
				player.play();
			})
			$(".adv-close, .btn-close").click(function(){
				$("#body_overlay").remove();
				$("#box_content").hide();
				player.play();
				playfromad = true;
				return false;
			});
		</script>

This is a script that controls an intermediary page and it works fine with Fluidplayer 2.4.11

In v3.0.4 it does not pause the player but gives an error in console log:

[FP_ERROR] Playback error DOMException: The play() request was interrupted by a call to pause().
(anonymous) @ fluidplayer.min.js:8
Promise.catch (async)
i.play @ fluidplayer.min.js:8
i.play @ fluidplayer.min.js:8
t.playPauseToggle @ fluidplayer.min.js:8
t.initialPlay @ fluidplayer.min.js:8
play (async)
i.play @ fluidplayer.min.js:8
i.play @ fluidplayer.min.js:8
t.playPauseToggle @ fluidplayer.min.js:8
n @ fluidplayer.min.js:8

Expected behavior
Pause the player with no console error

**Smartphone **

Device: Samsung Galaxy S10, Chrome mobile emulation
Browser Chrome
Version 85.0.4183.83
Affected version
v3.0.4

Additional context
Working with Fluidplayer 2.4.11

**Comment by Addvilz** [comment]
Please, don't create duplicate tickets. From your code example it seems that you are attempting to pause the player during initialization, when it is not in fact even playing. This error can only be encountered if you attempt to pause the player when it is not initialized for playback and this is never supposed to work this way. I suspect in 2.4.11 this error was somehow masked.

Simplified - you are calling "pause" inside "play", but "play" is asynchronous - you must NOT call "pause" inside "play".
