### ISSUE TITLE
Mobile View Rotate Landscape to activate Full Screen

### ISSUE THREAD

**Issue by Vegas10128** [fluid-player/fluid-player#524]
When user rotates mobile and tablet devices from portrait to landscape. The entire web page is displayed in a landscape form with the video. 

I am creating a Feature request to fix this and allow Landscape rotation on mobile devices to activate full screen view mode.

**Comment by Addvilz** [comment]
I see how this could be useful. Not as default behavior though, we could implement this via option flag.

**Comment by Vegas10128** [comment]
This would be very nice! I hope the development team can make this an option! Most of my apps are TWA apps and this would be a great experience for users who are using them.

**Comment by Addvilz** [comment]
FYI there is an API that can toggle fullscreen - although fullscreen on screen rotate is not a built in option, you can add this feature yourself too - https://docs.fluidplayer.com/docs/api/controls/#togglefullscreen and just toggle it using orientationchange event. 

See more here: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event

**Comment by HariPriyaKuberSingh** [comment]
@Vegas10128 - can you please confirm if the issue is still reproducible or does this require any fix?

**Comment by HariPriyaKuberSingh** [comment]
@Vegas10128 - can you please confirm if the issue is still reproducible ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
