### ISSUE TITLE
Disable Video Pause?

### ISSUE THREAD

**Issue by Undefined-Variables** [fluid-player/fluid-player#525]
Is there a simple way to disable the pause feature? I want videos to play and not pause when clicked... I have gone though the script (fluidplayer.js) and nothing I have tried disables it.

**Comment by Addvilz** [comment]
There is no way to do that. What would be the use case?

**Comment by Undefined-Variables** [comment]
I have a customer who wants a player setup in this way, I have explained many times that video is watched online because of the convenience of watching what you like with the choice to pause etc but he is adamant he wants it this way... 

What can I say, the customer is always correct :/

**Comment by Addvilz** [comment]
You can try to workaround this by hooking into pause event and emitting a play request immediately. But the UX will be poor. 

I am not sure we want this as a core feature.

**Comment by Undefined-Variables** [comment]
I agree... Yeah that makes sense, I will give that ago. Thank you.
