### ISSUE TITLE
Pictures in the form of single thumbnails

### ISSUE THREAD

**Issue by glsheff** [fluid-player/fluid-player#53]
Thanks for the player.
There is not enough support for this type of thumbnails:
```
<?xml version='1.0' encoding='utf-8'?>
<lists>
<pic src='thumb/1.jpg'/>
<pic src='thumb/2.jpg'/>
<pic src='thumb/3.jpg'/>
</lists>
```
(pictures in the form of single thumbnails)

**Comment by Danny15** [comment]
Hi @glsheff, we are glad you're enjoying the player. Regarding the support for these thumbnails we will look to discuss it when considering future improvements, but for now this is not possible. Thank you for your feedback

**Comment by majamee** [comment]
@glsheff Did you maybe have a look at the documentation over here:
https://docs.fluidplayer.com/preview_configuration/
https://github.com/fluid-player/fluid-player/issues/161

It is now possible. Not exactly in the format as you described, but in WebVTT format which should be evenly good. Does this maybe already solve your issue?

**Comment by Addvilz** [comment]
I would consider above a workaround. Closing now, please, reopen if still relevant.
