### ISSUE TITLE
contextMenu.links labels are not working after play

### ISSUE THREAD

**Issue by jewishmoses** [fluid-player/fluid-player#530]
**Describe the bug**
Wrong label "play" (and sometimes "pause"...) instead of "Wikipedia" (for example) when setting links within contextMenu.links only after clicking the play button

**To Reproduce**
1. create a simple fluid player instance with the following settings:
```js
var player = fluidPlayer("player", {
    layoutControls: {
        contextMenu: {
            controls: true,
            links: [
                {
                    href: "https://wikipedia.org",
                    label: "Wikipedia"
                }
            ]
        }
    }
});
```
2. Click play
3. Right click on player

**Screenshots or Links**
--
![](https://i.imgur.com/qw6mCGh.png)
--
https://codepen.io/jewishmoses/pen/JjKPYXr

**Desktop (please complete the following information if relevant):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 81

**Affected version**
v3.0.4

**Comment by HariPriyaKuberSingh** [comment]
@jewishmoses - can you please confirm if the issue is still reproducible ?

**Comment by jewishmoses** [comment]
> @jewishmoses - can you please confirm if the issue is still reproducible ?

Yep, still is, you can check the code pen: https://codepen.io/jewishmoses/pen/JjKPYXr
