### ISSUE TITLE
Few Bugs or poblems I had while setup V3

### ISSUE THREAD

**Issue by hawkiq** [fluid-player/fluid-player#533]
I just trying FluidPlayer for few hours and noticed few things Maybe i do it wrong while configuring the player

Steps to reproduce the behaviour:
1. Configure default configuration for player, taken from doc website
2. I noticed few thing doesn't work as required , like **subtitles i have to choose language every time** i refreshed the page ,  button `controlForwardBackward` **doesn't appear with controls**.
3. I see error in console Log `[FP_ERROR] Playback error DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.`
4. Ads can't be skip and nothing shows skip after x seconds

I've attached sample 
https://osama.app/samples/

**Comment by Addvilz** [comment]
> button controlForwardBackward doesn't appear with controls

controlForwardBackward is misconfigured in your code - it's an object, with key show, not a boolean.

> Ads can't be skip and nothing shows skip after x seconds

Your VAST tag has no skip offset. The player has no way to know after how many seconds you want to allow the ad to be skipped. See https://github.com/fluid-player/fluid-player/blob/master/test/static/vpaid_linear.xml - look for skipoffset. 

> I see error in console Log 

You have enabled auto play - auto play does not and will not work without user interaction in most browsers. There is no way around this.

> subtitles i have to choose language every time

Yes. This is how it works. If you would like to propose a change here, please open a feature request.
