### ISSUE TITLE
Vast Url doesn't just work on fluidplayer

### ISSUE THREAD

**Issue by mozgbrasil** [fluid-player/fluid-player#535]
**Describe the bug**

++

The following vast URL does not work in fluidplayer

https://bs.serving-sys.com/Serving/adServer.bs?c=23&cn=display&pli=1075789602&gdpr=${GDPR}&gdpr_consent=${GDPR_CONSENT_68}&ord={timestamp]

++

**To Reproduce**

++

The following vast URL does not work in fluidplayer

https://bs.serving-sys.com/Serving/adServer.bs?c=23&cn=display&pli=1075789602&gdpr=${GDPR}&gdpr_consent=${GDPR_CONSENT_68}&ord={timestamp]

I isolated the code in the following environment

https://codesandbox.io/s/test-fluidplayer-v3html-ckh3r

keep the browser console open then click on play

You will see that an error should be displayed

https://secure-ds.serving-sys.com/BurstingCachedScripts/VPAID/HTML5_1_40_0_0/VPAIDAPI.js

	VPAIDAPI.js:84 Uncaught TypeError: Cannot read property 'appendChild' of null
		at za.d.load (VPAIDAPI.js:84)
		at Aa.d.load (VPAIDAPI.js:87)
		at sa.d.load (VPAIDAPI.js:76)
		at ra.d.j (VPAIDAPI.js:75)
		at wa.d.M (VPAIDAPI.js:64)
		at wa.d.xa (VPAIDAPI.js:80)
		at t.b (VPAIDAPI.js:7)
		at u.d.b (VPAIDAPI.js:8)
		at qa.d.yb (VPAIDAPI.js:9)
		at qa.d.b (VPAIDAPI.js:9)

++

I made tests with this URL using other services and player that works as expected with the interactive video being shown

++

This player allows you to perform the test

https://www.openplayerjs.com/

When entering the vast URL we see that it works as expected

++

This player allows you to perform the test

https://flowplayer.com/developers/tools/ad-tester

When entering the vast URL we see that it works as expected

++

This player allows you to perform the test

https://adplayer.pro/developer/vast_inspector

When entering the vast URL we see that it works as expected

++

This service allows you to perform the test

https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector

When entering the vast URL we see that it works as expected

++

This service allows you to perform the test

http://test-a-tag.com/#

When entering the vast URL we see that it works as expected

++

This service allows you to perform the test

https://demo.brid.tv/inspector

When entering the vast URL we see that it works as expected

++

**Expected behavior**

++

Interactive video will be shown

++

**Screenshots or Links**
If applicable, add screenshots or links to help explain your problem. **DO NOT** include links to NSFW webpages. Preferably create code to reproduce using https://jsfiddle.net

**Desktop (please complete the following information if relevant):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser: chrome
 - Version: Versão 86.0.4240.75 (Versão oficial) 64 bits

**Affected version**

All version

https://codesandbox.io/s/test-fluidplayer-v1html-xhuht

https://codesandbox.io/s/test-fluidplayer-v2html-mn6tv

https://codesandbox.io/s/test-fluidplayer-v3html-ckh3r

**Comment by Addvilz** [comment]
> You will see that an error should be displayed

I see several errors - none from FluidPlayer, one from https://bs.serving-sys.com VPAIDAPI.js

**Your reproduce code is not helpful** as you are referencing a real, and what seems to be a production ad server. Nearly every person viewing the video can and might get different VAST/VPAID response.

As I mentioned in the other ticket, you MUST provide the error details - including full error text and exception stack trace, if available. And it is entirely up to you to check WHY a third party VAST/VPAID code might not work with FluidPlayer - realistically, there is no way for us to ensure compatibility with every ad server, platform, and provider out there.

**Comment by mozgbrasil** [comment]
Good afternoon

Thank you so much for interacting, sorry for any mistake

I will be carrying out further analysis and if necessary I will communicate
