### ISSUE TITLE
Player loops even when it should not

### ISSUE THREAD

**Issue by Tony-MF** [fluid-player/fluid-player#537]
Hi,

The player loops the video even though loop is not defined or when loop is set to false.

You can see it on your player here - https://www.fluidplayer.com/. The first video on the page (in the mobile phone). I suspect it's because of the preroll as the next player (without preroll) doesn't loop.

I'm checking it in Chrome Version 86.0.4240.111 (Official Build) (x86_64)

**Comment by Addvilz** [comment]
The video you linked is supposed to be looping.
