### ISSUE TITLE
Separate main video events from ad events

### ISSUE THREAD

**Issue by sp4r74cus** [fluid-player/fluid-player#538]
Currently the VAST preroll triggers the play, end etc events, which makes it hard to use (thought of counting the events, but preroll/ads will not always play).

Solution, create a set of events for the main video, and another for the ads.

Thanks

**Comment by HariPriyaKuberSingh** [comment]
@sp4r74cus - can you please confirm if the issue is still reproducible ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
