### ISSUE TITLE
merge video and audio on player 

### ISSUE THREAD

**Issue by mdoulabi** [fluid-player/fluid-player#539]
fluid player can merge video(webm or mkv or mp4 only video) and audio(m4a or mp3 only audio) on player?
i have video with 2 audio and i want can change audio
please answer , thank u .

**Comment by Addvilz** [comment]
Fluid Player (or any other HTML5 player) can not merge audio and video on the fly. There is a way to encode video with multiple audio tracks, however, Fluid Player has no support for this feature.

**Comment by HariPriyaKuberSingh** [comment]
Marking the ticket as closed since fluid player doesn't support this feature
