### ISSUE TITLE
Video playback stops when I change resolution

### ISSUE THREAD

**Issue by DrW3b** [fluid-player/fluid-player#54]
When I change video resolution the video playback stops. I must click pause button and click play again for continue playback.

**Comment by cian-exads** [comment]
Hi @DrW3b, I've tested locally and have had not had the issue you're describing. Could you let me know the browser and device you are using to see this? Please also ensure you are using the most up to date version of Fluid Player.

**Comment by DrW3b** [comment]
Problem solved, preload attribute was set to "none". I switch to "metadata"
