### ISSUE TITLE
Cursor not showing

### ISSUE THREAD

**Issue by guidenumber** [fluid-player/fluid-player#543]
Windows 10 x64 + Chrome 87.0.4280.67
(also in any latest version of all major browsers: Mozilla, Opera, IE)

Fluid player 3.0.4 (reproducible on this page: https://docs.fluidplayer.com/docs/overview/)

Cursor gets disappeared while hovering over player frame.

**Comment by Addvilz** [comment]
Unable to reproduce - tried on Windows, exact same Chrome version. Works as expected. Please, make sure your site CSS is not interfering with anything.
