### ISSUE TITLE
New event suggestion, onError

### ISSUE THREAD

**Issue by F4brizio** [fluid-player/fluid-player#545]
### New Event API

**onError**: Fired when an error occurs after initialization or reproduction video.

- Invalid mp4 url (Broken Link)
- Invalid format

Something like this:
`player.on('onError', function(){ console.log('The video could not be played!'); });`

**Comment by HariPriyaKuberSingh** [comment]
@F4brizio - can you please confirm if the issue is still reproducible ?

**Comment by F4brizio** [comment]
Yes please.

**Comment by marcofbb** [comment]
I need it :(

**Comment by DaRealCoda3** [comment]
Bro I got more than that ... 

BloxkOnlyVibez ... I'm bro let's connect

**Comment by leroybm** [comment]
Duplicated of #241, we have an internal ticket to take care of this. Closing.
