### ISSUE TITLE
Default Subtitle file at video start

### ISSUE THREAD

**Issue by hawkiq** [fluid-player/fluid-player#548]
at my website I have only one subtitle file and I would like to make it default when video starts, but seems i can't make this in Fluid player is there any workaround ?

**Comment by HariPriyaKuberSingh** [comment]
@hawkiq - can you please confirm if you could still face the above issue  ?

**Comment by HariPriyaKuberSingh** [comment]
@hawkiq - can you please confirm if you could still face the above issue ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
