### ISSUE TITLE
thumbnail not load when src with space

### ISSUE THREAD

**Issue by paipancon** [fluid-player/fluid-player#549]
I use a VTT file to load the thumbnail image, but it does not work when the src with space.

**Comment by HariPriyaKuberSingh** [comment]
@paipancon - Can you please confirm if the issue is still reproducible ?

**Comment by HariPriyaKuberSingh** [comment]
@paipancon - Can you please confirm if the issue is still reproducible ?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .
