### ISSUE TITLE
htmlOnPauseBlock doesn't work properly

### ISSUE THREAD

**Issue by DrW3b** [fluid-player/fluid-player#55]
When I use this feature and I start video playback banner appears. I must pause playback and play again for make it disappear.

**Comment by cian-exads** [comment]
Hi @DrW3b, this was an issue which had been resolved in a recent release. Can you please confirm if you are using the latest version of Fluid Player, and if so the browser and device you are seeing this on?

During testing we did notice an issue with the htmlOnPauseBlock feature, which we look to resolve. Thank you!

**Comment by DrW3b** [comment]
Solved. Problem happens because vast.xml I don't need this feature for now, so I remove it.
