### ISSUE TITLE
No tracking events called for subsequent ads

### ISSUE THREAD

**Issue by adeelmiraj** [fluid-player/fluid-player#550]
**Describe the bug**
Tracking events called for the first ad only. For the subsequent ads no tracking events are called.

**To Reproduce**
Steps to reproduce the behaviour:
1. Initialise the player with multiple preroll ads
2. Start playback and monitor the network tab of the dev tools
3. Tracking events are called for the first ads but not for any subsequent ad

**Expected behaviour**
The tracking events should be called for every single ad.

**Comment by HariPriyaKuberSingh** [comment]
@adeelmiraj - Can you please confirm if the issue is still reproducible?

**Comment by HariPriyaKuberSingh** [comment]
Moving the ticket to closed since there is no input from the reporter .

**Comment by h4xxr** [comment]
Hi.. I can reproduce this in Chrome and Edge but not Firefox, which works as expected. Demonstration can be made available on request
