### ISSUE TITLE
Allow mouse cursor to be visible while video plays, click video to pause/unpause

### ISSUE THREAD

**Issue by sinni800** [fluid-player/fluid-player#554]
**Is your feature request related to a problem? Please describe.**
We have a site where we mostly have quick videos. It is pretty annoying to our users that the mouse cursor disappears on hovering the videos, also that they can't click to pause.

**Describe the solution you'd like**
An option to stop disappearing the mouse cursor when hovering the video, also allow click to pause.

**Comment by leroybm** [comment]
Hi @sinni800, this seems to be a bug, as by default Fluid Player allows clicking the video to pause, and the mouse doesn't disappear. Can you provide us with a demo on Codepen with this issue? Feel free to look at the [guidelines for bug reports](https://github.com/fluid-player/fluid-player/blob/master/CONTRIBUTING.md#reporting-a-bug) for more help setting up the demo.

**Comment by sinni800** [comment]
I checked the current state again, and it's all fine nowadays. I think the issue might have been caused by us stll using prototype js which mangled around in the global js namespace of the browser. I have in the meantime completely thrown prototype out of our site, going for a vanilla JS approach.

I completely forgot about creating this issue, I am sorry for the inconvenience.

**Comment by leroybm** [comment]
Thanks for the response @sinni800, cosing the issue since it's not a problem anymore.
