### ISSUE TITLE
Play main video after preRoll ends not work

### ISSUE THREAD

**Issue by Barahten** [fluid-player/fluid-player#556]
After the end of the postRoll playback and pressing the Play button, the main video is not played.

An error appears in the console [Error] (204): [FP_ERROR] Timeout error. Failed to play video?

Example here - https://codepen.io/barahten/pen/XWNdPKB

Sometimes everything works correctly, sometimes it doesn't

When this does NOT work, the player shows the duration of the post-roll video instead of the duration of the main video

**Comment by HariPriyaKuberSingh** [comment]
The fix is now live. @Barahten  - Can you please confirm if the issues is fixed ?

**Comment by HariPriyaKuberSingh** [comment]
Closing the ticket since there is no update from the reporter on the issue
