### ISSUE TITLE
More than one VAST tag

### ISSUE THREAD

**Issue by angelcasana** [fluid-player/fluid-player#56]
Hello, I would like to know if is it posible to put more than one VAST tag. Example: 3 video ads tags. If 1st does not serving video ad calls the second, etc.

Thank you and best regards

**Comment by cian-exads** [comment]
Hi @angelcasana, multiple VAST tags are not currently supported. This is something we have discussed and we will be considering it in development planning. Thank you for your feedback.

**Comment by Danny15** [comment]
Hi @angelcasana, just to make you aware we have released Fluid Player 1.2  with improvements for supporting multiple vast tags with possibility to show not only preroll video ads but also at different times of the video (preRoll, midRoll, postRoll). I know this does not cover the exact issue you raised which we are still considering for future development but just wanted to update you with our current improvements.

**Comment by bharath-exads** [comment]
#348

**Comment by bharath-exads** [comment]
Hi,

We are supporting
1. Fallback ad URL if the main one fails
2. Multiple Ads (back to back)
https://docs.fluidplayer.com/ad_configuration/#adlist
