### ISSUE TITLE
Allow customizing playbackRates

### ISSUE THREAD

**Issue by sfdjo435** [fluid-player/fluid-player#560]
Hello, it would be nice to allow customization of playbackRates. For example, now you can't choose 0.25x as playbackRate.

YouTube for example allows multiple playback rates, 0.25x, 0.5x, 0.75x, 1x, 1.25x, 1.5x, 1.75x, 2x.

Instead of the current static ones. By setting defaults we can make this fully compatible with older configurations.

**Comment by Aaarrrsss5417** [comment]
#560


در تاریخ سه‌شنبه ۳ ژانویهٔ ۲۰۲۳،‏ ۱۹:۱۶ fpfcarvalho <
***@***.***> نوشت:
