### ISSUE TITLE
adText not working

### ISSUE THREAD

**Issue by GeekTNT** [fluid-player/fluid-player#57]
Here's a sample code showing that adText is just not showing:
https://jsfiddle.net/GeekTnT/aLnt1vz8/

BTW: is it possible to do the following:
- display "play" button in the center of the screen before playing the video?
- make the logo image clickable?

thanks

**Comment by Danny15** [comment]
Hi @GeekTNTdotCom. The adText parameter shows the text only during ads, however the example will not have ads showing and therefore this text will not be used.

A play button showing before playback has been discussed before and is something we intend to implement in a future release.

Clickable logo is not currently possible.

**Comment by Danny15** [comment]
Hi @GeekTNTdotCom, we have just released Fluid Player v1.2 and our latest changes include a parameter 'logoUrl' which allows an optional URL. If the user clicks the logo this URL will be opened in a new tab. See https://github.com/fluid-player/fluid-player for details on our latest release.

With regards your other request for a play button in center before playing the video, we are working to implement this in future release.
