### ISSUE TITLE
Auto generate video thumbnail(s) for WordPress featured image

### ISSUE THREAD

**Issue by canugurlu** [fluid-player/fluid-player#570]
Hi.

I've using Fluidplayer in my WordPress video site.

When I uploading a video to WordPress, I add a featured image with my hand manually.

How to get random video thumbnail(s) for my WP post featured image in Fluidplayer?

Is that possible?

**Comment by Addvilz** [comment]
Hi. Sorry, this is out of scope for the player itself, you need to generate the thumbnail using some other means. It could potentially be done in WordPress itself.
