### ISSUE TITLE
ATv || HK1 + Vivaldi | Opera

### ISSUE THREAD

**Issue by Zalext** [fluid-player/fluid-player#571]
Hi,

**Describe the bug**
**HK1 X3 TvBox | Amlogic 905x3 - ARM Cortex A55 x 4 | Mali-G31MP | Android 9 | Custom Rom**

On [Scabelum.tv/Directos](Scabelum.tv/Directos) (and rest of the site - account needed) there is no Video.
Playing with Browser Flags you can achieve Audio.

**To Reproduce**
1. Go to: [Scabelum.tv/Directos](Scabelum.tv/Directos)
2. Click on: Video to watch
3. Scroll down to: Not applicable
4. See error: No Video, just Audio (with some Flags)

**Expected behavior**
Working Video and Audio

**Screenshots or Links**
Extended explanation: [VForum](https://forum.vivaldi.net/topic/53152/hk1-tv-box-video/)

![image](https://user-images.githubusercontent.com/28935637/115381484-e78ed100-a1d3-11eb-9d73-e0ffdaee9fb4.png)

**Smartphone (please complete the following information if relevant):**
 - OS: Android 9 PIE - Customized by seller - Not Android Tv Certified
 - Model: HK1 X3 TvBox | Amlogic 905x3 - ARM Cortex A55 x 4 | Mali-G31MP | Android 9 | Custom Rom
 - Browser: [Vivaldi](https://vivaldi.com/android/) Browser Snap & Stable | [Opera](https://www.opera.com/mobile/opera) Mobile Dev & Stable 
 - Version: Latest Vivaldi since 3.6, now 3.7 | Opera since 61, now 62

**Affected version**
Fluid Player: 2.4.11

**Additional context**
It works fine on Chrome | Kiwi | FireFox - Latest and previous
_- Sometimes works on Opera Mini -_

If you follow the VForum link, you can see that happens as well on other sites where on **Xiaomi RedMi Note 7 Pro | A 10 | MIUI 12 | CN Rom** those browsers works just fine, so can be related to the ATv instead of the Player itself.

Related to Browser codecs, certification¿?

YouTube works fine,
Pending to update with other common, Vimeo and similar.

Thank you

**Comment by Addvilz** [comment]
There is no way for us to debug this - simply because we have no way to debug your specific device. 

My best guess? It's codecs or DRM. But really, could be anything. Is there anything useful in browser console output? Can you access that somehow?

**Comment by leroybm** [comment]
@Zalext I imagine this is not a problem since it's quite old and you haven't responded. Can I close this?

**Comment by Zalext** [comment]
Hi,
Havent seen your previous comment.

Currently that site is not accessed from this device anymore so you could close the report.


Thanks for your help
