### ISSUE TITLE
some m3u8 streams work on pc but not on embedded system

### ISSUE THREAD

**Issue by Slluxx** [fluid-player/fluid-player#572]
I am currently working on a homebrew for a gaming console which lets you watch TV via this player.

Some streams work both on my pc and my console, but others only work on my pc. I dont know why and where else to ask but here.

This is an example stream that works on both pc and console: 
https://zdf-hls-16.akamaized.net/hls/live/2016499/de/veryhigh/master.m3u8

This is an example stream that only works on pc and **not** on console:
https://fox-foxnewsnow-samsungus.amagi.tv/playlist.m3u8

Does anyone have a clue why the Fox stream is not working and how i could make it work?
Thanks in advance

Edit: Since its a gaming console, i dont have access to a proper debugger. Ive tried my best with vorlon.js but the experience is miserable at best. The console gives me a basic "Video could not be loaded" alert. Remember, other streams work fine though.

**Comment by HariPriyaKuberSingh** [comment]
@Slluxx  - We have our dev team to look into the issue. Below are the comments from the dev 
"The Nintendo Switch [doesn't officially have a browser,](https://en.wikipedia.org/wiki/Nintendo_Switch#Media_support) however, it has a hidden browser that can be opened using the methods described [here](https://www.lifewire.com/access-nintendo-switch-web-browser-4583984), but as suggested in the same article, videos can’t be played on the Nintendo Switch browser, as Fluid Player uses HTML5 video, it also doesn’t work.
The user mentions trying to run the player on a [Homebrew](https://en.wikipedia.org/wiki/Homebrew_(video_games)), described as "Homebrew, when applied to video games, refers to games produced by hobbyists for proprietary video game consoles which are not intended to be user-programmable.”, as it’s a hobbyist project and not intended to be user-programmable, it can be assumed that the user is implementing a custom browser without having the official documentations or permissions from Nintendo."

**Comment by Slluxx** [comment]
Yes, the nintendo switch does not oficially have a browser. However HTML5 videos can be played if the browser is opened through other methods (for example homebrews). The browser thats opened in the linked article only has a subset of functionality.

Also, in my issue i stated that some streams work and some doesnt. Implying that `[...] but as suggested in the same article, videos can’t be played on the Nintendo Switch browser [...]` is not true.

However i opened this issue on 2 May 2021, and now its the 23rd of august 2022 - over a year later. I do not care about this anymore.
