### ISSUE TITLE
Fluid player ad tag macros

### ISSUE THREAD

**Issue by rahulb1234** [fluid-player/fluid-player#579]
What are the standard macro placeholders that are used in Fluidplayer for passing dynamic information through tag?

I have been using Fluidplayer for video ad serving on webpage and need to understand what standard macros need to changed in order to pass all the necessary information to the ad server or demand partner.

macros that need to be passed are :
height
width
page URL
Cachebuster
us privacy
autoplay
mute

Can anyone who have been using Fluidplayer explain how to pass these macros through tag?

**Comment by leroybm** [comment]
The only current macro is `[ERRORCODE]`. We are limited by what[ IAB describes here](https://interactiveadvertisingbureau.github.io/vast/vast4macros/vast4-macros-latest.html). Are you still trying to implement this? If so, can you please take a look at the list and respond with the needed macros?

**Comment by sergiomcsousa** [comment]
@rahulb1234 Hi Raul, is this still an issue or can I close this issue? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
