### ISSUE TITLE
Use with Revive Adserver inline video fails with error "Access-Control-Allow-Origin' header in the response must not be the wildcard '*'"

### ISSUE THREAD

**Issue by trzczy** [fluid-player/fluid-player#58]
I prepared a site with Fluid Player to get VAST data from Revive Adserver. Pre-roll inline video ads do not work and chrome gives an error:

Failed to load http://rigby.ga/www/delivery/fc.php?script=bannerTypeHtml:vastInlineBannerTypeHtml:vastInlineHtml&format=vast&nz=1&zones=pre-roll%3D1: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://rigby.ml' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Any ideas?
Thanks

**Comment by Danny15** [comment]
Hi @trzczy, we're unsure what the cause may be, if you could provide additional details to help us identify it. You mention that this is occurring on Chrome, does it work on other browsers? Could you provide a test page where we can see this occur?

**Comment by cian-exads** [comment]
Hi @trzczy, is this issue still occurring? Can you provide a test page if so?

**Comment by gjonsson** [comment]
Hey, i know it's late answer but hopefully helps someone. In Revive Adserver, you can change in "lib/max/Delivery/common.php" find "function MAX_commonSetNoCacheHeaders"

**And change** 
`//` Also send default CORS headers
MAX_header('Access-Control-Allow-Origin: `*');`
**to something like this.**
`//` Also send default CORS headers
MAX_header('Access-Control-Allow-Origin: https://www.yourwebsite.com');
MAX_header('Access-Control-Allow-Credentials: `true');`

**Comment by Addvilz** [comment]
Fluid Player requests metadata over HTTP(s) using `XMLHttpRequest` with credentials enabled. Wildcard origins are not allowed when credentials are sent using `XMLHttpRequest`. For CORS request to be valid here, response must include exact origin and `Access-Control-Allow-Credentials` header must be `true` in response.

**Comment by Addvilz** [comment]
We should make this an option - whether or not to include credentials.
