### ISSUE TITLE
How to set Authorization header in player?

### ISSUE THREAD

**Issue by DoanhNV** [fluid-player/fluid-player#580]
How can i add Request Header like **Authorization** to the video request?

Can you show me?

**Comment by XanXus96** [comment]
any news?

**Comment by Hitmandagod05** [comment]
<video id='hls-video'>
    <source src='stream_hls.m3u8' type='application/x-mpegURL'/>
</video>

<script>
fluidPlayer(
    'hls-video',
    {
        layoutControls: {
            fillToContainer: true
        }
    }
);
</script>

**Comment by leroybm** [comment]
The video request itself is made by the browser by default, for HLS it uses `hls.js` and for dash it uses `dashjs`. We have [callbacks for the requests](https://docs.fluidplayer.com/docs/configuration/advanced/#xhr-configuration), but the video itself is loaded by the browser. Are you still having this issue?

**Comment by sergiomcsousa** [comment]
@DoanhNV Is this still an issue or can I close the issue? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
