### ISSUE TITLE
Can I set Request Header?

### ISSUE THREAD

**Issue by EvilBozkurt** [fluid-player/fluid-player#582]
Can I set setRequestHeader data when i using fluid player with CDN? I want to try this to avoid that error: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

Another question...
I don't know much about Node JS. How can I download the player and use it with PHP? Maybe it's a very simple process but I couldn't :(  As far as I understand it doesn't work without Node components. And I don't know how to use this in vanilla PHP. I want to develop a WordPress plugin with this player.

**Comment by leroybm** [comment]
Hi @EvilBozkurt, you need to add the compiled javascript files to your page, our use the CDN. To compile you will need node just for the compilation process. 

As for the requests, we have a callback for this [here](https://docs.fluidplayer.com/docs/configuration/advanced/#xhr-configuration).

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
