### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by uwejan** [fluid-player/fluid-player#59]
in addition to the nice features implemented ,The ability to add Multi Captions"srt"/"vtt" would be good .

**Comment by Danny15** [comment]
Hi @saddamuwejan, thank you very much for your feedback. We will keep this in mind when planning features for future releases.

**Comment by bharath-exads** [comment]
#348

We are adding Multiple Subtitles (VTT) support

**Comment by bharath-exads** [comment]
Hi,

Please check our latest release
https://docs.fluidplayer.com/subtitles/
