### ISSUE TITLE
How to dynamically change the title ? 

### ISSUE THREAD

**Issue by SAMYEL06** [fluid-player/fluid-player#598]
Hello ! 

I've tried to put a div with some php in "title:" option, and make it update via setinterval function.

The value is passed from php to the title option of the player, but when it updates at the interval, the title vanishes and nothing is shown. 

Am I doing something wrong ?

**Comment by leroybm** [comment]
@SAMYEL06 you can add it dynamically but just on the player initialization, if you want to reset the player, you need to call `.destroy()` on the instance beforehand. Is this still an issue?

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
