### ISSUE TITLE
HLS Support

### ISSUE THREAD

**Issue by VinceG** [fluid-player/fluid-player#6]
First, Great work.

Was wondering if this will support HLS or streaming?

Thank You.

**Comment by MarinYotovski** [comment]
Hello VinceG,

Thank you for the question.
Unfortunately, at this point streaming is not supported. Nevertheless, the player functionality should be relatively easy to extend with such a feature.
We will constantly be reviewing our roadmap and will be taking requested features into consideration.

Kind Regards!

**Comment by golikov** [comment]
Support for HLS streaming has been added as part of v2.2.0
