### ISSUE TITLE
Re: 16:9 Aspect ratio - Not working with fillToContainer: true

### ISSUE THREAD

**Issue by padmalakshmi143** [fluid-player/fluid-player#601]
A clear and concise description of what the problem is.
When I enabled the fillToContainer: true option, video doesn't show 16:9 ratio, can you please help.
**Additional context**
Have referred all the documents but couldn't found any such option.

**Comment by padmalakshmi143** [comment]
can anyone please help.

**Comment by sergiomcsousa** [comment]
@padmalakshmi143 Is this still an issue? Can I close this? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
