### ISSUE TITLE
VPAID not working

### ISSUE THREAD

**Issue by estelleal** [fluid-player/fluid-player#602]
Hello,

I'm trying to make this VPAID working : https://rtr.innovid.com/r1.5554946ab01d97.36996823;cb=1982
But it doesn't on your player, that's normal ?

Thanks

**Comment by sergiomcsousa** [comment]
@estelleal Is this still and issue? Can I close this? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
