### ISSUE TITLE
Stops working with time

### ISSUE THREAD

**Issue by Le1Tatsuhi** [fluid-player/fluid-player#603]
I add the video from a cdn, via the URL... But after a few hours, the player fails

**Comment by leroybm** [comment]
Hi @Le1Tatsuhi, is this still an issue?

**Comment by sergiomcsousa** [comment]
@Le1Tatsuhi Is this still and issue? Can I close this? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
