### ISSUE TITLE
How to configure the player to work on iframe videos?

### ISSUE THREAD

**Issue by animemandir** [fluid-player/fluid-player#605]
I tried using the fluid player for <video> tag videos, It works fine with it, but when the video is in <iframe> it doesn't work.
Is there any way in which the player can use iframe vids?

![image](https://user-images.githubusercontent.com/78192713/136748231-0bd3ac61-e593-499d-8d17-778a4de35475.png)
The above image shows the player used with video tag. It doesn't work when I try to change video src onlick.

![image](https://user-images.githubusercontent.com/78192713/136748386-96d97d17-81ab-4c15-a933-b7fccf666b04.png)

**Comment by Joel2B** [comment]
to play the video you need to reset the video source, try this
```js
var video = document.querySelector('video');
video.src = 'source.mp4';
video.load();
video.play();
```

**Comment by leroybm** [comment]
@animemandir Is this still an issue?

**Comment by sergiomcsousa** [comment]
@Joel2B Is this still and issue? Can I close this? Thank you!
