### ISSUE TITLE
How to remove download option 

### ISSUE THREAD

**Issue by adikami5665** [fluid-player/fluid-player#606]
I have tried every combination but I cannot remove the download option from the player. Currently my site is on the pc local host and here is the code 
<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<video id="video-id"><source src="https://archive.org/download/1-real-life-battle-royaletyaqi6fqvnu/%5B2019-04-11%5D-Real%20Life%20Battle%20Royale-3840x2160-%5BTyAQI6fqVNU%5D.ia.mp4" type="video/mp4" />
<script>
    var myFP = fluidPlayer(
        'video-id',	{
	"layoutControls": {
		"controlBar": {
			"autoHideTimeout": 3,
			"animated": true,
			"autoHide": true
		},
		"htmlOnPauseBlock": {
			"html": null,
			"height": null,
			"width": null
		},
		"autoPlay": false,
		"mute": false,
		"allowTheatre": true,
		"playPauseAnimation": false,
		"playbackRateEnabled": false,
		"allowDownload": false,
		"playButtonShowing": false,
		"fillToContainer": false,
		"posterImage": ""
	},
	"vastOptions": {
		"adList": [],
		"adCTAText": false,
		"adCTATextPosition": ""
	}
}
</script> 

I tried 1 and 0 as well but cannot remove the download button. This is a main thing for my site, please help

**Comment by Joel2B** [comment]
everything works fine, you just forgot to close the parenthesis of the fluidPlayer() function.
```html
<script>
    var myFP = fluidPlayer("video-id", {
        layoutControls: {
            controlBar: {
                autoHideTimeout: 3,
                animated: true,
                autoHide: true,
            },
            htmlOnPauseBlock: { html: null, height: null, width: null },
            autoPlay: false,
            mute: false,
            allowTheatre: true,
            playPauseAnimation: false,
            playbackRateEnabled: false,
            allowDownload: false,
            playButtonShowing: false,
            fillToContainer: false,
            posterImage: "",
        },
        vastOptions: {
            adList: [],
            adCTAText: false,
            adCTATextPosition: "",
        },
    });
</script>
```

**Comment by leroybm** [comment]
@adikami5665 Is this still an issue?

**Comment by sergiomcsousa** [comment]
@Joel2B Is this still and issue? Can I close this? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
