### ISSUE TITLE
More intelligent read-ahead for HLS playback

### ISSUE THREAD

**Issue by Tomas-M** [fluid-player/fluid-player#607]
When I specify HLS video (m3u8 playlist) as a source for fluid-player, it starts to preload the .ts video files even if the user didn't start the palyback yet. More importantly, it downloads (preloads) the video like crazy. Basically it downloads all .ts video blocks regardless of the speed of playback, resulting in unnecessary data bandwidth for both the server and client, and unnecessary memory consumption (video can have gigabytes in total).

I think this is a bug. See youtube player how it handles videos - it preloads some data, but then stops preloading while the video is played, to save bandwidth, it is unnecessary to load all 100s of MB of the video into memory, since if the user is playing the video, he does not need to download it as a whole, just few blocks ahead are fine

I suggest to add some intelligent logic to read-ahead only so much for smooth playback, but not more, or maybe at least an option to STOP READ AHEAD at all.

Thank you for consideration

**Comment by Joel2B** [comment]
you have to configure hls so that it doesn't do that, by default it downloads 60MB of fragments/ts,
setting the maxBufferSize property to 30 will limit it to download 30MB, 
more info at [https://github.com/video-dev/hls.js/blob/master/docs/API.md#maxbuffersize](https://github.com/video-dev/hls.js/blob/master/docs/API.md#maxbuffersize)

**Comment by Tomas-M** [comment]
Does it apply to fluid player at all? It seems to me this setting is for hls.js only, which is a different project, right? I am not sure how to configure it for fluid player. Do I need to load the hls.js script as well?

**Comment by Tomas-M** [comment]
I think I've found this setting.
There is a documentation how to get the hls.js instance: https://docs.fluidplayer.com/docs/api/utility/
player.hlsInstance();

So it is possible to set
player.hlsInstance().config.maxBufferSize = 2*1000*1000; // 2MB buffer

It does not make any effect though (setting remains at 60MB) so I worked around this by making an interval to permanently set this each second, I'm not sure why it cannot be set directly just once

setInterval(function(){
   player.hlsInstance().config.maxBufferLength = 5;
   player.hlsInstance().config.maxBufferSize = 2000000;
},1000);

This works for me, though I don't understand much why I need to do it this way.

**Comment by Joel2B** [comment]
you can configure hls through "configureHls" which returns a default configuration.

```js
configureHls: (options) => {
    options.maxBufferLength = 5;
    options.maxBufferSize = 2 * 1000 * 1000;

    console.log(options);
    
    return options;
},
```

https://docs.fluidplayer.com/docs/configuration/advanced/

**Comment by Tomas-M** [comment]
Ah, now I understand, thank you! :)
