### ISSUE TITLE
Need Playback speed more playback speed

### ISSUE THREAD

**Issue by Sun121232** [fluid-player/fluid-player#608]
I want to there 0.25,0.50,0.70, 1.50,1.70 how i add that can u please help

**Comment by Joel2B** [comment]
editing this line you can add the values you want
[https://github.com/fluid-player/fluid-player/blob/master/src/fluidplayer.js#L2493](https://github.com/fluid-player/fluid-player/blob/master/src/fluidplayer.js#L2493)

**Comment by leroybm** [comment]
@Sun121232 Now you can edit this in the player config https://docs.fluidplayer.com/docs/configuration/layout/#controlbar. Let me know if I can close this ticket.

**Comment by sergiomcsousa** [comment]
@Joel2B Is this still and issue? Can I close this? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
