### ISSUE TITLE
Can't get to work the Advertise Skip button 

### ISSUE THREAD

**Issue by openaspace** [fluid-player/fluid-player#609]
Hi.
I can't get to works the skip button on the start pre roll, also i see a layer over the preroll video with a link, where to set this link?

This is my configuration with the SKIP problem:

<video id="video-id"><source src="https://myserver.dev/testabr1/live/playlist.m3u8" type="application/x-mpegURL" />
<script>
    var myFP = fluidPlayer(
        'video-id',	{
	"layoutControls": {
		"controlBar": {
			"autoHideTimeout": 4,
			"animated": true,
			"autoHide": true
		},
		"htmlOnPauseBlock": {
			"html": null,
			"height": null,
			"width": null
		},
		"autoPlay": false,
		"mute": false,
		"allowTheatre": true,
		"playPauseAnimation": true,
		"playbackRateEnabled": false,
		"allowDownload": false,
		"playButtonShowing": true,
		"fillToContainer": true,
		"posterImage": "https://mywebsite.dev/wp/wp-content/uploads/2021/11/diretta_live-1.png"
	},
	**"vastOptions": {
		"adList": [
			{
        "roll": "preRoll",
				"vastTag": "https://mywebsite.dev/wp/adsant/preroll.xml",
				"adText": "Spot",
        "adCTAText": false,
	  		"skipButtonCaption" :          "Skip ad in [seconds]",
            "skipButtonClickCaption" :     'Skip ad <span class="skip_button_icon"></span>',
            "adText":                     null,
            "adTextPosition":             'top right',
            "adCTAText" :                  'Visit now!',
            "adCTATextPosition":          'bottom right',
            "vastTimeout":                5000,
            "showPlayButton":             true,
            "maxAllowedVastTagRedirects": 1,
			}
		],**
		
	}
})
</script>

**Comment by Joel2B** [comment]
if the pre-roll doesn't have the skipoffset tag it will not show the skip button, this is decided in:
https://github.com/fluid-player/fluid-player/blob/master/src/modules/vast.js#L494
https://github.com/fluid-player/fluid-player/blob/master/src/modules/adsupport.js#L45
https://github.com/fluid-player/fluid-player/blob/master/src/modules/adsupport.js#L94

and regarding the link you can configure it using "landingPage".

**Comment by openaspace** [comment]
> if the pre-roll doesn't have the skipoffset tag it will not show the skip button, this is decided in:
> https://github.com/fluid-player/fluid-player/blob/master/src/modules/vast.js#L494
> https://github.com/fluid-player/fluid-player/blob/master/src/modules/adsupport.js#L45
> https://github.com/fluid-player/fluid-player/blob/master/src/modules/adsupport.js#L94
> 
> and regarding the link you can configure it using "landingPage".

Really really thank you!
I have solved.

<Creative sequence="1" id="1">
<Linear skipoffset="00:00:05">
<Duration>00:02:30</Duration>

Fluid player is the best player ever :)

**Comment by leroybm** [comment]
Closing since the issue seems to be resolved :)

**Comment by buzashop1998** [comment]
can share your solve code?
