### ISSUE TITLE
How to properly get back to stream after stream was lost

### ISSUE THREAD

**Issue by tomasgrunt** [fluid-player/fluid-player#612]
How to properly solve this situation. Camera is streaming, then there is signal drop, so I find out that src m3u8 is not available and I add poster image "Please wait", then I get stream working back so I call play function, but there is created src attribute (blob) in video tag. How can I create new one blob src? Or is there another procedure how to solve stream interuption?

Thank you

**Comment by Joel2B** [comment]
you can try the hls recovery methods
https://github.com/video-dev/hls.js/blob/master/docs/API.md#fifth-step-error-handling
listening for error events, identify yours and try to recover the stream

**Comment by leroybm** [comment]
@tomasgrunt Is this still an issue?

**Comment by tomasgrunt** [comment]
Probably not, thank you.

st 6. 9. 2023 v 16:22 odesílatel Leroy Medeiros ***@***.***>
napsal:
