### ISSUE TITLE
Process not defined when using fluid-player with gatsbyjs v3

### ISSUE THREAD

**Issue by illogic-al** [fluid-player/fluid-player#613]
**Describe the bug**
After importing fluid-player into a gatsby project and attempting to use it, the build step passes, but actually loading it in a browser fails with `process is not defined` error. 

**To Reproduce**
1. Create a gatsby v3 project
2. import fluid-player
3. Use fluid-player component as documented (setting up ref, etc)
4. start `gatsby develop` 
5. navigate to page with fluid-player component
4. See error: `process is not defined`

**Expected behavior**
Page loads and displays video as expected.

**Screenshots or Links**
If applicable, add screenshots or links to help explain your problem. **DO NOT** include links to NSFW webpages. Preferably create code to reproduce using https://jsfiddle.net

**Desktop (please complete the following information if relevant):**
 - OS: macOS 11.6
 - Browser: Vivaldi
 - Version : 4.3

**Affected version**
v3.0.0

**Additional context**
A PR will be created to fix the issue.

**Comment by leroybm** [comment]
The issue is still reproducible in Gatsby 5
