### ISSUE TITLE
How can I pass options as variable?

### ISSUE THREAD

**Issue by tomasgrunt** [fluid-player/fluid-player#616]
How can I pass options for player as variable? E.g.:

This does not work:
videoOptions = `
	                   layoutControls: {
                            contextMenu: {
                            controls: false,
                           }`;

myFP = fluidPlayer('video-id', { videoOptions });

Thank you

**Comment by Joel2B** [comment]
would be as follows

```js
const videoOptions = {
    layoutControls: {
        contextMenu: {
            controls: false,
        },
    },
};

const myFP = fluidPlayer('video-id', videoOptions);
```

**Comment by tomasgrunt** [comment]
When I wrote this:

const videoOptions = {
    layoutControls: {
        contextMenu: {
            controls: false,
        },
    },
};

const myFP = fluidPlayer('video-id', { videoOptions });

I got error:

Uncaught TypeError: Cannot set properties of undefined (setting 'layoutControls')
    at c.t.init (fluidplayer.js:2341)

**Comment by Joel2B** [comment]
you don't need to put braces between the `videoOptions` constant

```js
// bad
const myFP = fluidPlayer('video-id', { videoOptions });

// good, test this code
const myFP = fluidPlayer('video-id', videoOptions);
```

**Comment by tomasgrunt** [comment]
Great, that was it. Thank you
