### ISSUE TITLE
fluid player does not play the vast file from adsterra with the video in wordpress when shortcode or script is used in html section of text block

### ISSUE THREAD

**Issue by tomardotcom** [fluid-player/fluid-player#617]
**Describe the bug**
fluid player does not play the vast file from adsterra with the video in wordpress when shortcode or script is used in html section of text block

**To Reproduce**
1. Go to '...' add a text block and insert shortcode for fluid player
2. Click on '....' insert video file path and vast file path
3. Scroll down to '....' save and publish the changes
4. See error '...' only video is playing and no vast ad is played

**Expected behavior**
vast ad should run in the beginning of the video as expected

**Screenshots or Links**
![Screenshot adding shortcode](https://user-images.githubusercontent.com/51581113/143602435-40b3ceee-c40a-4e7c-b8ea-3ddc800f0d3b.png)
![Screenshot adding script](https://user-images.githubusercontent.com/51581113/143602472-eadfd0f2-3270-46ea-a98c-93087a33e416.png)

**Desktop (please complete the following information if relevant):**
 - OS: [e.g. iOS] MacOS Big Sur 11.2.2
 - Browser [e.g. chrome, safari] Safari 14.0.3
 - Version [e.g. 22] Wordpress 5.8.2

**Smartphone (please complete the following information if relevant):**

**Affected version**
For example, v3.0.0

**Additional context**

**fluid player shortcode used is given below-**

<p style="text-align: center;">
[fluid-player
video="http://www.goldordiamond.com/wp-content/uploads/2021/11/Nostradamus-Forecast.mp4"
vast_file="https://www.videosprofitnetwork.com/watch.xml?key=1ea0299b70f3627b672be85bc792aa61"
layout="default"
allow-download="true"
playback-speed-control="true"
responsive="true"
]</p>

**fluid player script used is given below-**

<p style="text-align: center;">
<link rel="stylesheet" href="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.css” type="text/css">
<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script> 
<video id="my-video" style="width: 600px; height: 325px;" controls="controls" width="300" height="150">
<source src="http://www.goldordiamond.com/wp-content/uploads/2021/11/Nostradamus-Forecast.mp4" type="video/mp4" /></video> 
<script type="text/javascript">
var player = fluidPlayer(
"my-video",
{
vastOptions: {
adList: [
{
roll: "preRoll",
vastTag: "https://www.videosprofitnetwork.com/watch.xml?key=1ea0299b70f3627b672be85bc792aa61"
},
{
roll: "midRoll",
vastTag: "https://www.videosprofitnetwork.com/watch.xml?key=1ea0299b70f3627b672be85bc792aa61",
timer: 8
},
{
roll: “midRoll",
vastTag: "https://www.videosprofitnetwork.com/watch.xml?key=1ea0299b70f3627b672be85bc792aa61",
timer: 10
},
{
roll: "postRoll",
vastTag: "https://www.videosprofitnetwork.com/watch.xml?key=1ea0299b70f3627b672be85bc792aa61"
}
]
}
}
);
</script></p>

**Comment by Joel2B** [comment]
i replicated your scenario and the player breaks.

apparently there is a problem with the script that loads the ad.
https://greedseed.world/vpaid/newYtVpaid.php?sid=400&key=400

try with other players to see if it happens the same thing.

**Comment by MariaAlmeidaMJ** [comment]
After having analyzed this error, it is concluded that the error is not from our code, but rather a problem with Vpaid. On our side, there is nothing we can do.
