### ISSUE TITLE
Live streaming  buffer problem

### ISSUE THREAD

**Issue by openaspace** [fluid-player/fluid-player#618]
Hello,
I'm using Nimble HLS streaming with chunk duration and count of  6 seconds, 
when the streaming start it buffer some seconds, but this buffer became less and less and after some time , the buffer is very small and the stream experience continuous stops and start....

As I can see is a player issue and not a server configuration.
How to solve this?

Really thank you.

**Comment by Joel2B** [comment]
probably hls.js needs to be configured, if you could provide the m3u8 source, we could test it.

**Comment by openaspace** [comment]
Hello, thank you for the support. 
Now the stream server is off. I could send  you the link in private?

What you mean for "to be configured".
I'm, coming from TheoPlayer that was working out of the box and the same stream works correctly.

**Comment by leroybm** [comment]
Hi @openaspace, as this issue is old I would suggest updating Fluid Player if you still have this problem, otherwise you can try changing the configuration of  `hls.js`, you can check the [API docs here](https://github.com/video-dev/hls.js/blob/master/docs/API.md). I'll leave a sample of how you can change the settings within Fluid Player:

```javascript
var instance = fluidPlayer('fluid-player', {
    modules: {
        configureHls: (options) => ({
            maxMaxBufferLength: 30, // Max length of buffered video
            startLevel: 4, // Starting quality level - 4 is usually Full HD (1080p)
            ...options,
        })
    }
});
```

**Comment by leroybm** [comment]
Closing the issue due to inactivity, @openaspace feel free to open a new issue if you still have this problem
