### ISSUE TITLE
How to embed it with a video element inside a shadowroot element ?

### ISSUE THREAD

**Issue by anuragvohraec** [fluid-player/fluid-player#624]
Hi Team,

I use `lit-html` based templating library for my project.
The vido players lie inside a nested shadow root element.
how do I add fluid player to a video tag deeply nested in a shadow root tree ?

**Comment by leroybm** [comment]
@anuragvohraec this should work as normal, you first need to add a `<video>` tag to your DOM, then you call `fluidPlayer`, either passing the id or the `<video>` element itself. Is this still an issue for you?

**Comment by anuragvohraec** [comment]
> @anuragvohraec this should work as normal, you first need to add a `<video>` tag to your DOM, then you call `fluidPlayer`, either passing the id or the `<video>` element itself. Is this still an issue for you?

Yes the problem persist for video player inside shadow element.
If I pass the video element itself, I still get errors:
![image](https://github.com/fluid-player/fluid-player/assets/53807480/56d4fb2b-5a9e-493c-b7a9-fe2fe1802837)

This is how my shadow element is layed out :

![image](https://github.com/fluid-player/fluid-player/assets/53807480/3f5f4686-acbc-409f-a984-3d9ee93a7063)

**Comment by leroybm** [comment]
@anuragvohraec thanks for the response, just tested this with lit-html and could reproduce the issue. I will create an internal issue to take a look at this.

**Comment by leroybm** [comment]
@anuragvohraec Can you check if this issue is still persisting? The latest release tries to address the problem

**Comment by sergiomcsousa** [comment]
No answer from the reporter. Closing the ticket.
