### ISSUE TITLE
Infinite loading in Firefox

### ISSUE THREAD

**Issue by Kimarnic** [fluid-player/fluid-player#625]
Im on the latest Firefox 96.0.3 and when I try to play a video using this player it infinite loads and gives me a
[Error] (204): [FP_ERROR] Timeout error. Failed to play video?
and
Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: mozilla::MediaResult __cdecl mozilla::WMFVideoMFTManager::ValidateVideoInfo(void): Can't decode H.264 stream because its resolution is out of the maximum limitation

On Edge works but not on Firefox, any fix?

**Comment by Joel2B** [comment]
You may be better helped if you provide an online example using the font you are having problems with.

using the same source but with a different player, does the same thing happen?

**Comment by Kimarnic** [comment]
It's NSFW, should I share it? if yes, how?
Edge works but on Firefox it doesn't, i can't choose a different player

**Comment by Joel2B** [comment]
I am not sure if it can be sent nsfw
you could send an email to jb.win@hotmail.com to test it.

although as it says in the error, the resolution of the video is out of the limit, is it 4k or more?

**Comment by leroybm** [comment]
@Kimarnic since this is quite old, are you still having this issue?

**Comment by sergiomcsousa** [comment]
@Kimarnic Is this still and issue? Can I close this? Thank you!
