### ISSUE TITLE
run the code from self webhosting

### ISSUE THREAD

**Issue by openaspace** [fluid-player/fluid-player#626]
Hello 
I have copied all the repository on a folder of my web server cached with cloudflare.

The web page run the code url from my hosting, but when I inspect the page after the live streaming is started, I see that the file 
vendors~hlsjs.a08460db836c4bc384ad.min.js is loaded from your CDN with the following url.

https://cdn.fluidplayer.com/3.0.4/vendors~hlsjs.a08460db836c4bc384ad.min.js

Where I'm wrong?
Thank you.

**Comment by Joel2B** [comment]
try replacing the fp cdn with yours in:
https://github.com/fluid-player/fluid-player/blob/master/package.json#L27

**Comment by leroybm** [comment]
@openaspace Did you manage to try the the @Joel2B solution?

**Comment by leroybm** [comment]
Closing the issue due to inactivity
