### ISSUE TITLE
Duplicated control bar on a video

### ISSUE THREAD

**Issue by alice-luc** [fluid-player/fluid-player#627]
**Describe the bug**
I've faced an issue with duplicating control panel on playing video. I've tried different configurations and none solved the issue.

**To Reproduce**
1. Integrate the latest version(v3/current, it's 3.0.3 for now) using cdn
2. Use the basic script:
var player = fluidPlayer(
   'my-video',
    {
    }
);
3. Try to load any video

**Expected behavior**
Video should be played with the default settings as it shown in the documentation

**Screenshots or Links**
<img width="1027" alt="Снимок экрана 2022-02-05 в 23 19 41" src="https://user-images.githubusercontent.com/72791938/152818885-848a34b6-60b6-4dde-90e5-fa5a6b803c45.png">

**Desktop (please complete the following information if relevant):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version latest

**Affected version**
 v3.0.3

**Additional context**
Im not sure weather it is a global issue, or

**Comment by Joel2B** [comment]
by default fluidplayer removes the default "controls" from video
https://github.com/fluid-player/fluid-player/blob/master/src/fluidplayer.js#L1810

check if it has the "controls" attribute in the video tag, you can remove it once the player starts, with the function "playerInitCallback", or hide it with css.

**Comment by leroybm** [comment]
@alice-luc Have you been able to fix this? Thanks @Joel2B for the comment!

**Comment by alice-luc** [comment]
i guess so @leroybm 
its been a while)
