### ISSUE TITLE
vastTag Xml File issue

### ISSUE THREAD

**Issue by RajuProgmattic** [fluid-player/fluid-player#629]
when i use server XML file then i have cors issue alway and when i use xmlfile=`xml element` then show error blocked:other .plz solve this issue

**Comment by leroybm** [comment]
Hi @RajuProgmattic, are you still having this issue? Usually CORS is an issue between your domain and the ad server.

**Comment by sergiomcsousa** [comment]
@RajuProgmattic Is this still and issue? Can I close this? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
