### ISSUE TITLE
How to Install FluidPlayer to Weebly

### ISSUE THREAD

**Issue by ecchirealm** [fluid-player/fluid-player#63]
having some trouble installing fluidplayer in weebly, would appreciate some help, thanks!

**Comment by Danny15** [comment]
Hi @ecchirealm , in order to help you, can you provide us with more information about how you are trying to integrate Fluid Player with Weebly. Do you have access to code to integrate or is it widget based integration you are trying with Weebly?. Thank you

**Comment by cian-exads** [comment]
Hi @ecchirealm, do you have an update as to how this integration is going? Can you provide additional details if you still require assistance?

**Comment by majamee** [comment]
@ecchirealm You can also have a look at https://alpine-dash-hls.gq
This could help you in that way, that it is a tool chain which automatically generates all files for you including html for fluid player which can be hosted on basically any webspace. The generated files are basically drag'n'drop and you can just include the video of your choice in your page of choice by using an iframe or embedded to include the generated html file. ;)

**Comment by Addvilz** [comment]
Not enough details to proceed with this issue.
