### ISSUE TITLE
how to auto add (auto generate) video title in fluid-player ?

### ISSUE THREAD

**Issue by rsk1987** [fluid-player/fluid-player#633]
Hello Anyone,
can you tell me how to auto add (auto generate from video) video thumbnail in fluid-player ?

**Comment by leroybm** [comment]
Hi @rsk1987, Fluid Player doesn't support this right now. As for a custom implementation, I imagine that you can setup a server that can return an image based on your video source.

**Comment by sergiomcsousa** [comment]
@rsk1987 is this still an issue? Can this ticket be closed? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
