### ISSUE TITLE
Is it possible to make user autoplay fluid player videos 

### ISSUE THREAD

**Issue by N30Z3N** [fluid-player/fluid-player#634]
So I saw while setting up player in website autoplay option can be modified 
regardless what site has enabled is there any method to user can autoplay videos ? like modifying elements in browser or something ?

**Comment by Joel2B** [comment]
you mean a menu in the control bar with the "autoplay" toggle option?

**Comment by leroybm** [comment]
@N30Z3N I'm curious as I don't quite understand this as well. Can you check the previous comment?

**Comment by sergiomcsousa** [comment]
@N30Z3N Is this still an issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
