### ISSUE TITLE
Subtitles overflow

### ISSUE THREAD

**Issue by XanXus96** [fluid-player/fluid-player#635]
**Describe the bug**
I have a video with multiple subtitles (300+) that surpass the screen

**To Reproduce**
add more than 25 subtitles to a video

**Expected behavior**
A scroll on the subtitles (optional possibility to set a max height) or subtitles groupping by language

**Screenshots or Links**
![image](https://user-images.githubusercontent.com/39890594/157999657-e1bc0841-005f-4c16-b702-d9544a38cc01.png)

**Desktop (please complete the following information if relevant):**
 - OS: Windows11
 - Browser chrome
 - Version [98

**Affected version**
v3.0.0

**Comment by Joel2B** [comment]
you can limit it with this

```css
.fluid_subtitles_list {
    height: 195px;
    overflow: auto;
}
```
