### ISSUE TITLE
Dual Audio standard Language?

### ISSUE THREAD

**Issue by pixelstock** [fluid-player/fluid-player#636]
Hello buddys

How can I add this option for fluidplayer to detect a default language?
And the videos start without audios, any solution?

**Comment by Joel2B** [comment]
> How can I add this option for fluidplayer to detect a default language?

do you mean that detects the language of the browser (user), for the audios of hls , dash...?

> And the videos start without audios, any solution?

you can use the "mute" property of `layoutControls`, to start the muted videos

**Comment by leroybm** [comment]
@pixelstock is this still an issue for you?

**Comment by Indpradeep** [comment]
Hdjejejsjjd

**Comment by sergiomcsousa** [comment]
@pixelstock Is this still an issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
