### ISSUE TITLE
Fluid Player Vast Issue [In Video Ad Not Showing Up]

### ISSUE THREAD

**Issue by ecchirealm** [fluid-player/fluid-player#64]
<link rel="stylesheet" href="vast.css" type="text/css"/>
<script src="vast.js"></script>

<video id="my-video" controls style="width: 640px; height: 360px;">
    <source src="main_video.mp4" type="video/mp4" />
</video>

<script type="text/javascript">
    var testVideo = fluidPlayer(
        "my-video",
        "http://syndication.exoclick.com/splash.php?idzone=2893020"
    );
</script>

**Comment by Danny15** [comment]
Hi @ecchirealm , I have checked your account and this zone relates to an In-Stream ad format which it looks like you are trying to integrate. I can also see that the script you are using (<script src="vast.js"></script>) is from a old version of Fluid Player. You should be able to resolve the issue of the in-Stream ad showing by using our updated Javascript and CSS files. Example:

`<link rel="stylesheet" href="https://cdn.fluidplayer.com/current/fluidplayer.min.css" type="text/css"/>
<script src="https://cdn.fluidplayer.com/current/fluidplayer.min.js"></script>

<video id='my-video' controls style="width: 640px; height: 360px;">
	<source src='vid.mp4' type='video/mp4' />
</video>

<script type="text/javascript">
	var testVideo = fluidPlayer(
        'my-video',
        '<VAST URL>'
        );
</script>`

Please let us know if this resolves your issue or if you still experience any further issues after updating these scripts.

We will also review if we are displaying these old scripts in any of our integration examples and update if so. Thank you

**Comment by cian-exads** [comment]
Closing this issue as it has been open for some time now, and the integration of in-stream VAST tags is outlined in detail in the [Fluid Player Docs](https://docs.fluidplayer.com/ad_configuration/) ad configuration section.
