### ISSUE TITLE
HLS issue

### ISSUE THREAD

**Issue by tjalveg** [fluid-player/fluid-player#644]
The fluid-player is great, but HLS gives a 404 after some change around 18. april 2022:

![image](https://user-images.githubusercontent.com/61010475/164466355-360dafe5-a2be-438b-90e2-a7f0490ba948.png)

Adding the referenced file in code like this gives a CORS error:

<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<script src="https://cdn.fluidplayer.com/v3/current/vendors~hlsjs.11e90f13091b93b6d9a2.min.js"></script>

![image](https://user-images.githubusercontent.com/61010475/164466851-b42b14eb-2409-438d-bf54-b4c3cb03c6e0.png)

![image](https://user-images.githubusercontent.com/61010475/164466948-a572506e-1f34-41d4-a383-bdd49c74cac2.png)

Some change in hls.js that needs to be resolved in Fluid?

**Comment by Minervatra** [comment]
Hi! Same problems here. I am getting 
**Uncaught (in promise) ChunkLoadError: Loading chunk 3 failed.
(timeout: https://cdn.fluidplayer.com/3.0.0/vendors~hlsjs.min.js)** 
error. Please check this problem! Thanks!

**Comment by apurvakarthik** [comment]
@Minervatra could you check for this issue again? I suppose it should be solved in version 3.1.0 or in the newer version post that.

**Comment by HariPriyaKuberSingh** [comment]
moving the ticket to done since there is no update from the reporter

**Comment by XanXus96** [comment]
same problem here
