### ISSUE TITLE
npm install fluid-player@^3.0.0

### ISSUE THREAD

**Issue by Michael2626** [fluid-player/fluid-player#646]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

> [npm install fluid-player@^3.0.0](var player = fluidPlayer(target [, options)

**Comment by HariPriyaKuberSingh** [comment]
@Michael2626  -  Could be please elaborate on the issue for the dev team to resolve it.

**Comment by muuki88** [comment]
I assume tht @Michael2626 means that there has been no npm updates on npmjs.org for newer releases.
The last published release was 3.0.4. The repo states that 3.8.0 is the latest version.

**Comment by leroybm** [comment]
@Michael2626 is your case what @muuki88 commented? If so, now the NPM version is always up to date with the latest releases.

**Comment by sergiomcsousa** [comment]
@Michael2626 Is this still an issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
