### ISSUE TITLE
fluidplayer.min.js CDN bug

### ISSUE THREAD

**Issue by andyxszav** [fluid-player/fluid-player#651]
In CDN link https://cdn.fluidplayer.com/3.0.0/fluidplayer.min.js

(r.style.display="none"),a&&(a.style.display="none"),l&&(l.style.display="none"),d&&(d.style.display="none")}

Hier must be display block to show the skip ad button when VAST video is playing.

**Comment by HariPriyaKuberSingh** [comment]
moving the ticket to Done since there is no feedback from the user
