### ISSUE TITLE
Set Cookie on Vast Ad

### ISSUE THREAD

**Issue by razor1907** [fluid-player/fluid-player#653]
**Is your feature request related to a problem? Please describe.**
When adding a vast ad it is loaded on every pageview or refresh

**Describe the solution you'd like**
Set a cookie so that the vast ad appears 1x per 12 or 24 etc hour/minute

**Comment by leroybm** [comment]
@razor1907 this should be controlled by your ad server. It should send an empty VAST response when no ad should be played

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
