### ISSUE TITLE
Set the latest version as latest release

### ISSUE THREAD

**Issue by Tony-MF** [fluid-player/fluid-player#654]
Hi @fpfcarvalho,

Thanks for all the commits. Do you think you can set the latest commit (now v3.2.1) as the latest release?

I believe when I'm loading https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js I get v3.0.4 instead of the latest one.

Thanks

**Comment by Tony-MF** [comment]
Bump

**Comment by leroybm** [comment]
@Tony-MF Now the CDN is always updated to the last release, can I close this?
