### ISSUE TITLE
hls buffering too much data

### ISSUE THREAD

**Issue by ashmodai1972** [fluid-player/fluid-player#655]
I am having problems trying to implement fluid player.  The problem is that it is buffering 2 1/2 minutes instead of about 30 seconds.  Is there a place for this to be configured?  I tried to set the maxBufferLength but it didn't seem to work.  I looked at the example on https://docs.fluidplayer.com/docs/streaming/hls/ and it buffers half of the 9 minute video almost immediately.

Thanks for any help.

**Comment by leroybm** [comment]
Hi @ashmodai1972, currently this can be done by using the module hook `configureHls`, here is a sample on how to this:
```javascript
var instance = fluidPlayer('fluid-player', {
    modules: {
        configureHls: (options) => ({
            maxMaxBufferLength: 30, // Max length of buffered video
            startLevel: 4, // Starting quality level - 4 is usually Full HD (1080p)
            ...options,
        })
    }
});
```
Let me know if this helps you with your problem.
