### ISSUE TITLE
VAST AD Releted

### ISSUE THREAD

**Issue by rajukumar1995** [fluid-player/fluid-player#658]
i am using vast ad feature in fluid player .i want call api on every ad play .how can i do that plz explain .i am using reactjs

**Comment by websitefavourite** [comment]
I'm also interested in this, anyone know if this is possible?

**Comment by sergiomcsousa** [comment]
@rajukumar1995 Is this still an issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
