### ISSUE TITLE
Saving the last known user location

### ISSUE THREAD

**Issue by txmondv** [fluid-player/fluid-player#659]
I haven't found a feature to save the last known user location. With that I mean that when the user leaves the page, the current progress in the video and maybe the video itself for the whole player could be saved and then progressed to a file or alike. When the video is finished the progress of course would not have to be saved.

Having a general last known user location for the whole project and not only per file would support streaming-service like projects with many videos.

If there already is a similar feature, please let me know.

**Comment by sergiomcsousa** [comment]
@txmondv Is this still an issue? Can I close this ticket? Thank you!

**Comment by txmondv** [comment]
Thank you for your reply, I completely forgot about this post, I'm sorry. This is not an issue anymore and the ticket can be closed :)
