### ISSUE TITLE
Video plays at first, then stop working after few seconds.

### ISSUE THREAD

**Issue by holuwadamilare** [fluid-player/fluid-player#661]
It automatically stop playing video after few seconds, I can't play neither pause. Please, I'm not a backend developer, I would prefer a basic solution to this.
Thanks.
![Screenshot (63)](https://user-images.githubusercontent.com/25038418/174461905-9c7b7def-34ae-43a1-97f0-b517885f97e0.png)

**Comment by leroybm** [comment]
@holuwadamilare Are you still having this issue?

**Comment by sergiomcsousa** [comment]
@holuwadamilare Is this still an issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
