### ISSUE TITLE
Test files!! And  picturtre  in picture

### ISSUE THREAD

**Issue by laszkris** [fluid-player/fluid-player#662]
Hi!
In the  master folder "test html" samples htmls are not  working.... Only just this  code showing:
<%= htmlWebpackPlugin.tags.headTags %> 
What is the  solution for the testing the sample players code if these html-s  are not working?
And..
Can it possible to disable the  Firefox "picture in picture" button from the  video screen?
https://ibb.co/1vhmywC
Thanks

**Comment by leroybm** [comment]
For the tests to work you need to run the following commands.

`yarn install` 
`yarn start`

**Comment by sergiomcsousa** [comment]
@laszkris Is this still an issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
