### ISSUE TITLE
Autoplay in chrome

### ISSUE THREAD

**Issue by laszkris** [fluid-player/fluid-player#663]
Hi!

It is possible to autoplay in chrome browser?
Thanks

**Comment by leroybm** [comment]
@laszkris You can enable the autoPlay property, but it's up to the browser to allow or disallow it, depending on the user settings and browser policy.

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
