### ISSUE TITLE
localStorage not available in Chrome incognito mode is breaking JS

### ISSUE THREAD

**Issue by Cisney-Gassai** [fluid-player/fluid-player#667]
**Describe the bug**
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

Evaluating: "typeof (localStorage) !== 'undefined'" in setPersistentSettings triggers this issue when the browser denies the access to localStorage, which happens when the user is in incognito mode or always blocking third-party cookies, this only happens when the player is embeded within an iframe.

**To Reproduce**
1. Go to 'chrome://settings/cookies'
2. Click on 'Block third-party cookies in incognito'
3. Check fluid-player console WITHIN an iframe

**Expected behavior**
Skip setPersistentSettings and keep going.

**Desktop (please complete the following information if relevant):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103.0.5060.114

**Affected version**
v3.0.4 and beyond, didn't check older.

**Additional context**
A simple try-catch can solve this issue, not only for users with incognito mode but also those that block third-party cookies always. A fallback alternative to localStorage would also work.

**Comment by Sr-Jon** [comment]
Hello, the same thing is happening to me. Is there any way to disable js cookies?

That seems to be the problem...

**Comment by HariPriyaKuberSingh** [comment]
The fix is live. Can you please confirm if the issue is reproducible ?

**Comment by leroybm** [comment]
@Cisney-Gassai @Sr-Jon have you taken a look at this since the fix was released?

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
