### ISSUE TITLE
Add more custom events and Add more options for developers

### ISSUE THREAD

**Issue by gibigate** [fluid-player/fluid-player#674]
**Is your feature request related to a problem? Please describe.**
Problem with creating own modules. When i try to add event listener to player dom in my module, i get error:
```Cannot read properties of null (reading 'addEventListener')```
So module run before fluid player initialization

**Describe the solution you'd like**
Add custom events when fluid player initialization.

**Describe alternatives you've considered**
Rewrite fluidplayer in some places for easy external modules integrate. Add ability to rewrite fluidplayer functions. For example i want rewrite default player click behaviour in this part of code:
```
self.domRef.player.addEventListener(listenTo, () => self.playPauseToggle(), false);
```
I cant change anything in this situation, only rewrite fluidplayer core code (thats bad for upgrading in future)

**Additional context**

**Comment by leroybm** [comment]
@gibigate Is there any list of events that you think FP should expose? This seems really specific for your implementation, so it would be nice to know what are you trying to implement with this

**Comment by sergiomcsousa** [comment]
@gibigate Is this still an issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
