### ISSUE TITLE
Mobile on click show control bar instead of pausing video

### ISSUE THREAD

**Issue by hioer688** [fluid-player/fluid-player#675]
Hi,I want the player to show the control bar when clicking on the video while the video is being played. It doesn't work on mobile devices. It pauses the video even if the control bar is not visible. I want to pause the video only when the control bar is visible.

I can do it if I know how I can find the status of the control bar.thank you！

**Comment by EdyNakal1991** [comment]
Urmmm menarik

**Comment by leroybm** [comment]
We have a ticket tracking this issue, @hioer688 I'll let you know if there is any development

**Comment by sergiomcsousa** [comment]
@hioer688 the fix for this was fixed in Sep 2023, can this be closed? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
