### ISSUE TITLE
IOS icon bug on fullscreen exit

### ISSUE THREAD

**Issue by gibigate** [fluid-player/fluid-player#676]
When user exitting from fullscreen mode, the fullscreen icon doesn't change

**Comment by OrlaKinsella** [comment]
Hi @gibigate - we're currently looking into this now and haven't been able to reproduce this issue. 
Is this problem still persisting for you? If so, could you let us know some additional details such as the version of iPhone this is happening on, and the browser you're seeing it on?
Thanks!

**Comment by HariPriyaKuberSingh** [comment]
@gibigate  - Could you please confirm if the issue is persisting?  if yes, can you give us additional information on the same as requested by @OrlaKinsella ?

**Comment by HariPriyaKuberSingh** [comment]
Closing the ticket since there is no response from the reporter. If the issues persist, can you please open a new ticket to address the issue? Please add all the requested details as mentioned in earlier comments. Thank you
