### ISSUE TITLE
Need WordPress Plugin

### ISSUE THREAD

**Issue by mAdorRahman** [fluid-player/fluid-player#678]
Hi there,
I know this is an excellent player! But why **don't you have a WordPress plugin?** _Could you please work on it?_
Thank you.

**Comment by leroybm** [comment]
@aburke10 You may be able to just add the HTML code for Fluid Player with your own configuration, a plugin would be just a way to abstract this. Have you tried to do that?

**Comment by sergiomcsousa** [comment]
Is this still an issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
