### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by Naharanak2** [fluid-player/fluid-player#693]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Links**
If applicable, add screenshots or links to help explain your problem. **DO NOT** include links to NSFW webpages. Preferably create code to reproduce using https://jsfiddle.net

**Desktop (please complete the following information if relevant):**

**Smartphone (please complete the following information if relevant):**

**Affected version**
For example, v3.0.0

**Additional context**

**Comment by leroybm** [comment]
@Naharanak2 You may have forgotten to add a description, is there any issue that we can help with?

**Comment by leroybm** [comment]
Closing the issue as it lacks any description, please create a new issue if there is a problem that we can help you with
