### ISSUE TITLE
Mouse disapears 

### ISSUE THREAD

**Issue by LogoJK** [fluid-player/fluid-player#694]
**Describe the bug**
Mouse also disappears when controllbar hides and doesn't reappear! 

**To Reproduce**
Just wait until the controllbar (and mouse) disappears and then move the mouse. The controllbar reappears, but the mouse stays hidden.

**Expected behavior**
Mouse reappears when moved

**Screenshots or Links**
No point

**Desktop (please complete the following information if relevant):**
 - OS: Windows 11
 - Browser: tested on: edge, opera
 - Version: newest at post from issue

**Smartphone (please complete the following information if relevant):**
/

**Affected version**
I think v3.0.0

**Comment by OrlaKinsella** [comment]
Hi @LogoJK - this issue should be fixed in the latest version of Fluid Player. 
Please check using the latest version and close this issue if this has been solved.
Thanks so much!

**Comment by OrlaKinsella** [comment]
As there's been no response, closing this issue. If this issue persists, please feel free to re-open this issue with additional details. Thanks!
