### ISSUE TITLE
Posterimage

### ISSUE THREAD

**Issue by tekinc** [fluid-player/fluid-player#695]
Hi,

I'm using fluidplayer as my audio player. How can I set the posterimage to always be displayed?

**Comment by leroybm** [comment]
Hello @tekinc, this isn't fully supported by Fluid Player right now. I recommend trying to customise the player for this, `posterImage` is the function that adds the poster image, and it's removed on `playPauseToggle`, both are found on `fluidplayer.js`.

**Comment by HariPriyaKuberSingh** [comment]
@tekinc - Can you please confirm if the suggestion proposed by @leroybm helped you ? If yes, can we please close the ticket ?

**Comment by leroybm** [comment]
Closing ticket due to inactivity.
