### ISSUE TITLE
Custom progressbar?

### ISSUE THREAD

**Issue by tekinomikata** [fluid-player/fluid-player#698]
I would like to customize the colors of the video progress bar, is that possible with just css without having to modify and recompile the whole thing? If not what would I need to do such customization?

**Additional context**
Currently it looks like this:
![image](https://user-images.githubusercontent.com/59887008/199833598-85332809-a04c-40b7-99d6-564c2c6bc96e.png)
And I would like to give it a bit more coloring and make it slightly bigger, for example
![image](https://user-images.githubusercontent.com/59887008/199833711-52d85396-7b9f-4eda-927f-739af08f5974.png)

**Comment by gibigate** [comment]
set primaryColor option

**Comment by tekinomikata** [comment]
> set primaryColor option

primary color alone does not do the buffer and background modifications.

**Comment by leroybm** [comment]
If your intention is to modify it completely you can do it via CSS, but you will need to override the current defaults, example:
```css
.fluid_controls_progress, .fluid_controls_buffered, .fluid_controls_currentprogress {
    height: 6px !important;
}

.fluid_controls_currentpos {
    width: 16px !important;
    height: 16px !important;
    top: -5px !important;
    border-radius: 8px !important;
}

.fluid_controls_currentprogress {
    background: darkorange !important;
}

**Comment by tekinomikata** [comment]
> If your intention is to modify it completely you can do it via CSS, but you will need to override the current defaults, example:
> 
> ```css
> .fluid_controls_progress, .fluid_controls_buffered, .fluid_controls_currentprogress {
>     height: 6px !important;
> }
> 
> .fluid_controls_currentpos {
>     width: 16px !important;
>     height: 16px !important;
>     top: -5px !important;
>     border-radius: 8px !important;
> }
> 
> .fluid_controls_currentprogress {
>     background: darkorange !important;
> }
> ```

Thanks, that is exactly the direction I was looking for.

```
.fluid_controls_progress
{
    height: 8px !important;
    background: #282828 !important;
    opacity: .75 !important;
}
```
