### ISSUE TITLE
Without using the config is there an event on the player I can use to change the hls source as soon as the player is ready?

### ISSUE THREAD

**Issue by tekinomikata** [fluid-player/fluid-player#699]
I understand I can use the source tag and the hls config callbacks however dude to some rendering between php and javascript I need to run a javascript after I have instantiated the player with:
```
var myPlayer = fluidPlayer('player', myConfig));
```
Past that moment is there a way to run `hls.loadSource("my source to load");` as soon as the player is ready?

I couldn't find an event that lets me get an instance of the hls, I understand I can create a new instance by doing:
```
var hls = new myPlayer.hlsInstance();
```
And from there call the loadSource but for that to work I need and event that I can use that would give me a moment after the player is ready to receive a new source.

I thou that using the video onloadstart would be a good location but apparently it can still fail at that point, so maybe some one here would know if the player instance it self have an event I can use that would be more appropriate for this.

**Comment by leroybm** [comment]
Hi @tekinomikata, if you want the internal instance of `hls.js` you can get it through the `onBeforeInitHls` callback, [here is the docs](https://docs.fluidplayer.com/docs/configuration/advanced/). Does this helps with the issue?

**Comment by tekinomikata** [comment]
> Hi @tekinomikata, if you want the internal instance of `hls.js` you can get it through the `onBeforeInitHls` callback, [here is the docs](https://docs.fluidplayer.com/docs/configuration/advanced/). Does this helps with the issue?

Thanks for the reply, can that only be used within the modules arg? can I not use it from say:
```js
var myPlayer = fluidPlayer('player', config);
myPlayer.onBeforeInitHls...
```
Due to how I am handing the config to the player I am unable to add the event on it, so I had to resort to a separated approach.

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
