### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by jdc20181** [fluid-player/fluid-player#7]
Can you give me a working live demo? 

Just wanna see it in action xD

**Comment by MarinYotovski** [comment]
Hello jdc20181,

Thanks for contacting us.

Yes, a live working demo can be seen on the Fluid Player website: https://www.fluidplayer.com/
You can also download the project and open the /examples folder.

Kind Regards,
Marin Yotovski

**Comment by jdc20181** [comment]
Thanks!
