### ISSUE TITLE
Start screen only image poster and vast on mobile.

### ISSUE THREAD

**Issue by ERI123** [fluid-player/fluid-player#70]
1. When you go on a video page 
[REDACTED]
you do not see any player there only a poster image of the video. So is very difficult for the user to understand where is the video and click.
Need the control buttons to be always visible before the video is clicked and used to control if he wants the play button or not in the middle.

2. On iPhone after pressing the play button vast advertisement do not starts. Needs to press again the play button. Also, there is no skip button.

**Comment by Danny15** [comment]
Hi @ERI123 , thank you for your comments.

1. A play button showing in the middle has been discussed before and is something we intend to implement in a future release. Currently the video controls by default do not show initially. We will take this into consideration when planning features for future releases.

2. Thank you for raising this issue. We are now reviewing this behavior on iOS devices and will hope to have improvements for this in one of our future releases.
