### ISSUE TITLE
Video doesn't play at all, but vast ads do

### ISSUE THREAD

**Issue by huntergames79** [fluid-player/fluid-player#700]
Hello,
 I have tried to implement the video it all seems to work except that the video won't play, only the vast ad shows as soon as the page load!
the video can be seen here: https://huntergames.online/about.html  note: need to scroll to see it!

I would greatly appreciate anyone's help, thank you in advance!

**Comment by leroybm** [comment]
Hi @huntergames79, it seems that your player is loading a youtube url as source, Fluid Player supports the same formats as HTML5 video (mp4, webm, ogg), as well as hls and dash for streaming.

**Comment by huntergames79** [comment]
So it means that a google drive share link doesn't work? You need to see this video that this person made it work: https://www.youtube.com/watch?v=v529dXuFRAA

**Comment by leroybm** [comment]
If the source url responds with a supported and well formed media file it will work

**Comment by leroybm** [comment]
@huntergames79 are you still having issues with this?

**Comment by sergiomcsousa** [comment]
@huntergames79 is this still and issue? Can I close this ticket? Thank you!

**Comment by huntergames79** [comment]
yes, but you can close it! Thank you

Oscar Medina Matiz
