### ISSUE TITLE
How to Get Latest Version (3.9.0 at time of this post)

### ISSUE THREAD

**Issue by jbeatty88** [fluid-player/fluid-player#701]
On the documentation "Quick setup" page it says to upgrade to 3.9.0 but as far as I can tell, the actual latest released version is 3.0.4 which doesn't seem to work at all with latest versions of React so I was hoping 3.0.4 => 3.9.0 would work better with React.

Is 3.9.0 going go be released to NPM? Or is 3.0.4 the actual latest version and the message on in the docs is wrong? 

**Additional context**
![image](https://user-images.githubusercontent.com/37627395/202892769-2ba9a06d-2763-4eab-9e99-9509e8534173.png)

**Comment by leroybm** [comment]
@jbeatty88 I believe that the released versions are now the same on the CDN and on NPM, and the docs is updated. Are you having any problems with the latest version?

**Comment by sergiomcsousa** [comment]
@jbeatty88 is this still and issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
