### ISSUE TITLE
CurrentTime reset after switch HLS source on IOS

### ISSUE THREAD

**Issue by gibigate** [fluid-player/fluid-player#702]
**Describe the bug**
I have several HLS sources, after switching to other source on IOS, the current time resets to 0
In desktop on other platforms with HLS supported, it's worked fine

**To Reproduce**
No testing url, try yourself

**Expected behavior**
time continued

**Smartphone (please complete the following information if relevant):**
 - Device: iphone12
 - OS: ios16
 - Browser Chrome, safari
 - Version Last

**Affected version**
3.9.0

**Additional context**
it's only HLS source problem without HLS.js support

**Comment by OrlaKinsella** [comment]
Hi @gibigate - this should now be solved with the latest release of Fluid Player. Please take a look and close this issue if this has been solved! Thanks :)

**Comment by OrlaKinsella** [comment]
Closing this issue now - it should be solved with the latest release of Fluid Player. If the issue re-occurs, please feel free to reopen this issue. Thanks!
