### ISSUE TITLE
AutoHide Control bar only works on Safari with autoplay disabled (3.9.0)

### ISSUE THREAD

**Issue by k0nr4d** [fluid-player/fluid-player#703]
**Describe the bug**
Autohide functionality of the control bar appears to only work if autoplay is set to false. With autoplay set to true, it does not hide the controlbar after the timeout period. The functionality seems to work as expected on other browsers and Windows.

**To Reproduce**
<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
        <video id="thisPlayer">
            <source title='Best Quality' src="1.mp4" type='video/mp4'>
            <source title='Low Quality' src="2.mp4" type='video/mp4'>
        </video>
       <script type="text/javascript">
         var myFluidPlayer = fluidPlayer(
		   'thisPlayer',
			{
				"layoutControls": {
					"controlBar": {
						"autoHideTimeout":    3,
						"animated":           true,
						"autoHide":           true
					},
					"autoPlay": true,
					"playbackRateEnabled": true,
					"allowTheatre": true,
					"title": "<? echo addslashes($rrow['title']); ?>",
					"posterImage": "poster.jpg", 
					"timelinePreview": {
						"file": 'webvtt.vtt',
						"type": 'VTT'
					}
				},
				"vastOptions": {
					"adList": [
						{
							"roll": 'preRoll',
							"vastTag": '<? echo $fluidplayer_vast_preroll; ?>',
							"adText": 'Advertisement'
						},
						{
							"roll": 'midRoll',
							"vastTag": '<? echo $fluidplayer_vast_midroll; ?>',
							"timer": <? echo (int)$fluidplayer_vast_midroll_timer; ?>,
							"adText": 'Advertisement'
						},
						{
							"roll": 'postRoll',
							"vastTag": '<? echo $fluidplayer_vast_postroll; ?>',
							"adText": 'Advertisement'
						},
					]
				}
			}
		);
      </script>

**Expected behavior**
Setting autoplay true causes autohide to fail under MacOS + Safari. Setting it to false it works as expected.

**Desktop (please complete the following information if relevant):**
 - OS: Mac OS (latest)
 - Browser: Safari
 - Version: Safari 16

**Affected version**
v3.9.0

**Comment by OrlaKinsella** [comment]
Closing this, see above comment.
