### ISSUE TITLE
VAST - Safari in iOS returns NotAllowedError and doesn't play

### ISSUE THREAD

**Issue by Tony-MF** [fluid-player/fluid-player#705]
**Describe the bug**
It does not happen all the time, but it is frequent (~50% of the cases). When using a real iOS device (Safari on Mac doesn't trigger this for me). The player gets stuck (see screenshot) and the console shows the following error:

_NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission._

In other browsers, it works smoothly.

I found a similar bug reported here - https://github.com/fluid-player/fluid-player/issues/286, but it's closed without any explanation.

**To Reproduce**
Try to play a VAST ad on a real iPhone device. 

**Expected behavior**
If VAST is empty, it should play the video. Otherwise, it should play the ad.

**Screenshots or Links**
![IMG_48CB0B74731E-1](https://user-images.githubusercontent.com/73653258/210411332-c2a3de8d-7806-43a9-a945-9a028b478fe8.jpeg)

**Smartphone (please complete the following information if relevant):**
 - Device: iPhone XR

 - OS: iOS16.1
 - Browser: Safari
 - Version: the latest, not sure

**Affected version**
v3.0.4

**Additional context**

**Comment by leroybm** [comment]
Hi @Tony-MF, there are a couple of things that may be causing this issue:

* Your video server is not returning the correct content type header, or the video is not supported by Safari, or;
* The user is not interacting with the page before playing the video.

Both of these conditions should be met for a video to be played in Safari. Could you verify this in your scenario?

**Comment by leroybm** [comment]
Closing the issue due to inactivity, @Tony-MF please check the comment above and reopen the issue it if necessary.
