### ISSUE TITLE
Fluidplayer can´t play videos but vast ads can be played

### ISSUE THREAD

**Issue by Shady137** [fluid-player/fluid-player#710]
Hi, i have a blog that is nsfw content.

I use fluidplayer to share videos from Google drive with the share link

It had always worked well for me but today it stopped playing the video

The strange thing is that on all the devices that have my account open, it plays the video normally but on any other device it only plays the ad

Permissions on drive are enabled for anyone to see

Everything is correct, since a few days ago it was working normally

I would like to know what information i need so that someone can help me

I leave the blog link

www.archivoscalientes.com

**Comment by Joel2B** [comment]
the problem that you have is that you are using drive, google limits the times that a file can be used, you need to upload your content elsewhere to avoid this problem.

![image](https://user-images.githubusercontent.com/58922368/213092739-04ea6b84-e418-4123-a02c-3849645af8a3.png)

**Comment by Shady137** [comment]
What other server can I use to store and play the videos?

**Comment by Joel2B** [comment]
there are many ways to do what you want but that is not discussed here because it's not a fluidplayer issue.

upload your content on sites that allow you to upload this type of content, then get their video sources and insert them into this player.

**Comment by leroybm** [comment]
Closing the issue since it's related to video hosting and not Fluid Player, @Shady137 feel free to open a new issues if necessary.
