### ISSUE TITLE

<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<video id="video-id"><source src="video.mp4" type="video/mp4" />
<script>
    var myFP = fluidPlayer(
        'video-id',	{
	"layoutControls": {
		"controlBar": {
			"autoHideTimeout": 3,
			"animated": true,
			"autoHide": true
		},
		"htmlOnPauseBlock": {
			"html": null,
			"height": null,
			"width": null
		},
		"autoPlay": false,
		"mute": true,
		"allowTheatre": true,
		"playPauseAnimation": false,
		"playbackRateEnabled": false,
		"allowDownload": false,
		"playButtonShowing": false,
		"fillToContainer": false,
		"posterImage": ""
	},
	"vastOptions": {
		"adList": [],
		"adCTAText": false,
		"adCTATextPosition": ""
	}
});
</script>

### ISSUE THREAD

**Issue by Phamkhang135** [fluid-player/fluid-player#713]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Links**
If applicable, add screenshots or links to help explain your problem. **DO NOT** include links to NSFW webpages. Preferably create code to reproduce using https://jsfiddle.net

**Desktop (please complete the following information if relevant):**

**Smartphone (please complete the following information if relevant):**

**Affected version**
For example, v3.0.0

**Additional context**

**Comment by OrlaKinsella** [comment]
Hi @Phamkhang135 - can you tell us more about this? 

What is the bug you're facing? If you could provide us with a description of the issue, that would be great. 
Any additional detail you can provide us with - such as the device you're using and the browser would also be really helpful!

**Comment by OrlaKinsella** [comment]
Hi @Phamkhang135 - seeing as no additional details were provided we'll close this issue. If you're still having an issue, please feel free to re-raise it and provide further details so that we can look into it for you.
Thanks!

**Comment by josenovo** [comment]
Hola, encontre un error en la V3, algunas m3u8 no se pueden reproducir con la V3, sin con la V2, concretamente el reproductor queda cargando y nunca termina de cargar. Note este error con una url en concreto, desconozco si es por compativilidad del explorador o que la V3 no proporciona alguna decodificacion que la V2 si.
