### ISSUE TITLE
Picture in Picture mode

### ISSUE THREAD

**Issue by genna87** [fluid-player/fluid-player#715]
A Picture-in-Picture mode activated by a button in the controlBar and a layoutControls setting to enable/disable it.

**Comment by leroybm** [comment]
Hello @genna87, we have opened an internal ticket to track this, we will let you know on any development

**Comment by leroybm** [comment]
@genna87 We've developed a Mini Player feature for Fluid Player. It's already live and we have a few improvements coming along the way for the following weeks. You can check it out at [this documentation](https://docs.fluidplayer.com/docs/configuration/layout/#miniplayer).

Does this fit your needs for this issue?

FYI @abelhoyos

**Comment by genna87** [comment]
That's awesome. I'll look into it as soon as possible! THANKS

**Comment by leroybm** [comment]
@genna87 I'll close this ticket since the feature was released and there was no further comment, if you find any problems with the current implantation feel free to create a new issue
