### ISSUE TITLE
Can't get to works fluidplayer with signed dynamic url's

### ISSUE THREAD

**Issue by openaspace** [fluid-player/fluid-player#723]
I'm using this signed chunk withtout result, no error in the debug, simply doesn't play anything..
Fluid player support dynamic signed chunks?

**THE CODE**
https://github.com/Softvelum/paywall-code-samples-wmsauth/blob/master/php/basic-hls-stream-based.php

**I see in the source code the (first) correct url but nothing start:**
//str2.mydomain.pro:443/vodalias/videofilename.mp4/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MjAyMy0wNC0xM1QxNzo1NDowMVomaGFzaF92YWx1ZT1mZVArbCtxZGZtV2VXdnQrYkhXUHpzbmU2VnhBRmk3dGhieTd3NjBnaW1nPSZ2YWxpZG1pbnV0ZXM9MSZzdHJtX2xlbj01OA==';

every time I reload the page the wmsAuthSign= string change correctly..but nothing else..!

**Comment by openaspace** [comment]
Hello, 
there is or not the support for this kind of usage?

Thank you.

**Comment by leroybm** [comment]
@openaspace Is it possible to create a codepen with the issue so I can have a better look? I'm not sure what you mean by dynamic signed chunks. I see that you are using a .m3u8 stream, Fluid Player uses `hls.js` to handle that, maybe their docs can also help.

Here is a template for a codepen with FP https://codepen.io/exadsleroy/pen/QWmWPeo

**Comment by openaspace** [comment]
@leroybm hello. but the code can't works on codepen.io - it need to run on a server with password access to the streaming server in the php code..

With flowplayer it works correctly..
What I see with fluid player is that it get only the first time string and stop to works without the dynamic token chunk

**Comment by leroybm** [comment]
Can you run both Fluid Player and hls.js with debug on, to get the logs?
```javascript
    var instance = fluidPlayer('fluid-player', {
        debug: true,
        modules: {
            configureHls: (options) => ({
                ...options,
                debug: true,
            })
        }
    });
```

**Comment by leroybm** [comment]
@openaspace Did you try getting the logs for this one?

**Comment by leroybm** [comment]
@openaspace Taking a look at this again, this seem like an issue with `hls.js` itself, since it's this package that handles loading the media. The version that FP uses was recently updated, maybe that helped with your issue?

You can also try to run your media here: https://hlsjs.video-dev.org/demo/, if it works there, it's probably an issue with Fluid Player.

**Comment by sergiomcsousa** [comment]
@openaspace is this still and issue? Can I close this ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
