### ISSUE TITLE
error: Hls is not defined

### ISSUE THREAD

**Issue by stongabuse** [fluid-player/fluid-player#728]
after changing the quality and updating the page, such an error appears in the console, how can I fix it?

```
caught ReferenceError: Hls is not defined
    at e.initialiseHls (fluidplayer.min.js:2:153594)
    at e.initialiseStreamers (fluidplayer.min.js:2:152662)
    at C.t.init (fluidplayer.min.js:2:162826)
    at A (fluidplayer.min.js:2:216854)
    at (index):84:22
e
```

**Comment by JacobSteelsmith** [comment]
We are seeing this error on a previously working application in production. The console is reporting: GET https://cdn.fluidplayer.com/v3/current/vendors~hlsjs.491d368314208e630ab2.min.js net::ERR_ABORTED 404 (Not Found). Loading the URL manually shows the file is indeed not found.

**Comment by JacobSteelsmith** [comment]
Looks like my issue was our error. Using the latest from the CDN works fine. Thanks.

**Comment by leroybm** [comment]
Glad that it's working fine now @JacobSteelsmith! Closing the issue.
