### ISSUE TITLE
ControllFarwordBackword

### ISSUE THREAD

**Issue by AfzalHaq61** [fluid-player/fluid-player#729]
Farword and Backword not Working

**Additional context**
```fluidPlayer(
    'my-video',
    {
        layoutControls: {
            controlForwardBackward: {
                show: true // Default: false
            }
        }
    }
);```

according to this code. the button is showd but when i click its not working. I think i should add time to this but dont know hot to add it.

**Comment by leroybm** [comment]
Hi @AfzalHaq61 , can you create a demo showing the issue? I've created a codepen for this and it seems to be working normally https://codepen.io/exadsleroy/full/poQgJKo

Additionally any information about your test environment is welcome

**Comment by leroybm** [comment]
@AfzalHaq61 have you taken a look at the previous comment?

**Comment by sergiomcsousa** [comment]
@AfzalHaq61 is this still an issue? Can this ticket be closed? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
