### ISSUE TITLE
Could not find a declaration file for module 'fluid-player'

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [fluid-player/fluid-player#731]
When using angular, or ionic, I can't import fluid-player module because it doesn't have types.

`ng new fluid-proj`  
`pnpm i fluid-player`  

inside a component.ts:  
import fluidPlayer from 'fluid-player';

Whatever version 3 of fluid-player, Ionic 6, angular 14

The error message that is shown:  
Could not find a declaration file for module 'fluid-player'. '/dados/tutorials/angular/fluid-proj/node_modules/.pnpm/fluid-player@3.15.0/node_modules/fluid-player/src/index.js' implicitly has an 'any' type.

![print-fluid](https://user-images.githubusercontent.com/32627919/237868984-de7f2317-048e-4e97-8138-30e17bcf5e0d.png)

**Comment by leroybm** [comment]
Hi @danilobatistaqueiroz, thanks for reporting the issue. Unfortunately Fluid Player is not currently typed, and we don't have a types package for it. You can work around the issue by adding `@ts-ignore` to that line, or creating a `fluidPlayer.d.ts` file with `declare module 'fluid-player';` as it's content.

**Comment by leroybm** [comment]
@danilobatistaqueiroz We released a types file with the npm version of Fluid Player. Can you update and check that it works?

**Comment by sergiomcsousa** [comment]
@danilobatistaqueiroz is this still an issue? Can this be closed? Thank you!
