### ISSUE TITLE
can't read resolution from video on cloudflare stream

### ISSUE THREAD

**Issue by openaspace** [fluid-player/fluid-player#738]
playing a video from cloudflare stream it always use a lower resolutions instead of the 1080p

**Comment by leroybm** [comment]
Can you share your code @openaspace ? In the case of `hls.js` streams, it will choose the quality based on the user internet connection.

**Comment by leroybm** [comment]
@openaspace You can configure hls following the example at [our documentatin](https://docs.fluidplayer.com/docs/streaming/hls/#customizing-hls), the `startLevel` value is what controls the starting resolution. You can check the [hls.js documentation for this as well](https://github.com/video-dev/hls.js/blob/master/docs/API.md#startlevel). 

I'm not sure how does this works for dash, but you can take a look at their documentation if it's the case. If you need the dash.js instance you can check[ this docs](https://docs.fluidplayer.com/docs/api/utility/#dashinstance).

Unfortunately to know what exactly is the 1080p stream source, you should check with your API provider. But AFAIK `4` is usually 1080p or close. This would be how you set it for hls.js.

```javascript
fluidPlayer('fluid-player', {
    modules: {
        configureHls: (options) => ({
            startLevel: 4,
            ...options,
        })
    }
});
```

Let me know if this helps.

**Comment by sergiomcsousa** [comment]
@openaspace is this still an issue? Can this ticket be closed? Thanks!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
