### ISSUE TITLE
Failed to resolve import "cheerio/lib/api/traversing"

### ISSUE THREAD

**Issue by gusantoscode** [fluid-player/fluid-player#743]
**Describe the bug**
I just created a simple component and I get this error

**To Reproduce**
1. Install using "yarn add fluid-player"
2. Create a simple component
3. See error

**Screenshots or Links**
COMPONENT: https://jsfiddle.net/kuqr8vbm/

ERRORS:

![Error 1](https://imgur.com/Yzg6a3y.png "Error 1")
![Error 2](https://imgur.com/rsEE0NK.png "Error 2")

**Desktop (please complete the following information if relevant):**
 - OS: Linux
 - Browser Vivaldi

**Affected version**
I just test in *3.17.0*

**Comment by gusantoscode** [comment]
> I am also facing the same issue. Any resolution?

I haven't gotten any solution yet.

**Comment by leroybm** [comment]
@gusantoscode @aadi-rajat Thanks for reporting the bug, this is an issue related with a recent code change, could you try version 3.16.0?

I'll let you know when this is fixed.

**Comment by aadi-rajat** [comment]
@leroybm  Same error with 3.16.0 as well.

**Comment by leroybm** [comment]
@aadi-rajat @gusantoscode could you update to the latest version (3.18.0) and see if it's all working? I've tested in a React project and it seems that it builds now

**Comment by gusantoscode** [comment]
> @aadi-rajat @gusantoscode could you update to the latest version (3.18.0) and see if it's all working? I've tested in a React project and it seems that it builds now

Now it's working.

**Comment by aadi-rajat** [comment]
> @aadi-rajat @gusantoscode could you update to the latest version (3.18.0) and see if it's all working? I've tested in a React project and it seems that it builds now

Yes, it's working for me as well. Thanks
