### ISSUE TITLE
Combine fluidplayer with hls module to single js

### ISSUE THREAD

**Issue by saeedrm6** [fluid-player/fluid-player#758]
Hello
By default after build project , fluid player and hls module file are separated.
For seo issues and performance of loadings I have to combine fluidplayer and hls module to a single js file.
How can I do?

**Comment by leroybm** [comment]
Hi @saeedrm6, to do this you will need to edit how the project is built. Fluid Player uses webpack, so I suggest taking a look at that, you can start at https://webpack.js.org/configuration/. To build the project you can use `npm run build`.

**Comment by mostafadish** [comment]
Good morning

**Comment by sergiomcsousa** [comment]
@saeedrm6 is this still an issue? Can this ticket be closed? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
