### ISSUE TITLE
Method loadVpaid create frame without body

### ISSUE THREAD

**Issue by aheadweb** [fluid-player/fluid-player#765]
**Describe the bug**
The problem is with media files of the javascript type.
When the executing script accesses the body tag `document.body.appendChild` . The executable script crashes with an error
`Uncaught TypeError: Cannot read properties of null (reading 'appendChild')`

This is due to the fact that when creating a vpaidIframe, no body element is created

**To Reproduce**
[Build a demo with an error](https://codepen.io/aheadweb/pen/OJrpQQg)

**Expected behavior**
The advertisement starts playing. If you paste the link into other players that support VPAID everything will work

**Affected version**
v3.0.0

**Additional context**
Adding this line to the source code solves the problem
`vpaidIframe.contentWindow.document.querySelector('html').appendChild(document.createElement('body'))`
Maby 

Maybe I should create PR?

**Comment by aheadweb** [comment]
Found the same problem - https://github.com/fluid-player/fluid-player/issues/422

**Comment by aheadweb** [comment]
Hi @leroybm. Can I do PR somehow?

**Comment by leroybm** [comment]
@aheadweb Yeah, if you have something, you can open a PR and I'll review it!

**Comment by leroybm** [comment]
@aheadweb I've created a PR, can you take a look? https://github.com/fluid-player/fluid-player/pull/771

**Comment by sergiomcsousa** [comment]
@aheadweb this issue was fixed and the release was done on the 19th of October. Can you please confirm if it fixed so I can close?

**Comment by sergiomcsousa** [comment]
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.
