### ISSUE TITLE
fallbackVastTags may not be working

### ISSUE THREAD

**Issue by gibigate** [fluid-player/fluid-player#774]
**To Reproduce**
Just try this option yourself, it's not working with empty vast, broken vast or incorrect vast url
The player doesn't even try to load some URL from fallbackVastTags

**Expected behavior**
If vastTag empty or broken or failed when loading, fluidplayer should try to load URLs from fallbackVast

example:
```
{
    roll: 'preRoll',
    vastTag: "some vast url with error or empty or incorrect url",
    fallbackVast : [correct_vast1, correct_vast2],
}
```

<img width="379" alt="Снимок экрана 2023-11-02 в 19 10 41" src="https://github.com/fluid-player/fluid-player/assets/1709390/f9a9f334-07ac-42c2-bd79-a6aa7d086748">

**Comment by biguz** [comment]
also saw this issue

**Comment by sergiomcsousa** [comment]
An internal ticket was created to take care of this issue. Thank you!

**Comment by sergiomcsousa** [comment]
@gibigate the fix for this issue is now live. Take into account that the cache can take up to 24h to update and for you to see the changes. If everything is ok, can you please close the ticket? thanks!
