### ISSUE TITLE
Rewind error

### ISSUE THREAD

**Issue by biguz** [fluid-player/fluid-player#775]
Rewind causes redirect to home page at least on Android devices

**Comment by sergiomcsousa** [comment]
An internal ticket was created to take care of this issue. Thank you!

**Comment by ZentoDH** [comment]
Hi @biguz Could you check if this bug stil persists? I've tried to replicate rewind on android 7.1.1 and it worked how I would expect. Could you maybe make a codepen or something similar and also mention your android version. It'll be easier to debug if something is wrong, thanks!

**Comment by sergiomcsousa** [comment]
@biguz Does the problem persist? We didn't create an internal ticket since @ZentoDH is still waiting for the extra information. Thanks!

**Comment by biguz** [comment]
This issue was caused, with default android navigation feature(Forward and Back navigation). Left and right padding on timeline bar helps reduce this effect.
