### ISSUE TITLE
fluidplayer issue full screen controlBar not hide after 3 secunds 

### ISSUE THREAD

**Issue by saman-magnus** [fluid-player/fluid-player#781]
This problem is also visible in the latest version. 3.28.0
This problem can be seen on the official site where there is a demo player.
At full screen controlBar not hide after 3 Seconds or i try to change it from fluidplayer.min.js ( autoHide: true, autoHideTimeout: 3, animated: true)
But unfortunately I didn't get anywhere,

Regards {MagNus}

**Comment by ZentoDH** [comment]
Hi, how're things? I've tried to replicate this but couldn't seem to do so. Could you make a codepen of this issue? Also what browser are you using? maybe it's a problem in one browser but not the other. Thanks!

**Comment by saman-magnus** [comment]
its not a bug , only have to change 
 autoHide: true, autoHideTimeout: 3, animated: true)
to
 autoHide: ;0, autoHideTimeout: 3, animated: ;0)
thank u ...
