### ISSUE TITLE
onMainVideoEnded event fired before PostROLL (3.27.0)

### ISSUE THREAD

**Issue by gibigate** [fluid-player/fluid-player#782]
How to catch the actual end of main video event? In this version of player if the main video ends, the onMainVideoEnded event is called and after that the postroll is played. It's bug for me. After the main video i want to show some custom related content in player holder, it's improssible with current player behaviour

**Comment by ZentoDH** [comment]
Hi there, could you make a codepen with the bug you're running into? You can add the code for the custom content at the end. Then I can look into potential fixes and see if I can help you out.

**Comment by sergiomcsousa** [comment]
@gibigate were you able to provide the necessary information to @ZentoDH? can you please provide some feedback so we can move to possibly open an internal ticket? Thanks!

**Comment by sergiomcsousa** [comment]
Closing this ticket due to a lack of feedback. If the problem persists please open the ticket again. Thank you!
