### ISSUE TITLE
theatreAdvanced is not working and breaks player

### ISSUE THREAD

**Issue by leroybm** [fluid-player/fluid-player#790]
**Describe the bug**
Following the documentations to add theatreAdvanced the player breaks, as we can see on the attached codepen

**To Reproduce**
```javascript
fluidPlayer("video-id", {
  layoutControls: {
    posterImage: "https://www.fluidplayer.com//images/valerian-thumbnail.jpg",
    theatreAdvanced: {
      theatreElement: 'id'
    }
  }
});

```
**Expected behavior**
The player should not break

**Screenshots or Links**
https://codepen.io/leroybm-the-vuer/pen/ZEPQroW

**Desktop (please complete the following information if relevant):**
 - OS: macOs
 - Browser: chrome
 - Version 120.0.6099.129 (Official Build) (arm64)

**Affected version**
v3.29.0

**Comment by sergiomcsousa** [comment]
An internal ticket was created to take care of this issue. Thank you!

**Comment by sergiomcsousa** [comment]
@leroybm The fix for this issue is now live, could you confirm and close if ok? Thank you!

**Comment by leroybm** [comment]
@sergiomcsousa All good, closing issue.
