### ISSUE TITLE
'htmlOnPauseBlock' don't work anymore since 3.28.0

### ISSUE THREAD

**Issue by drsheep404** [fluid-player/fluid-player#793]
Hi,

I saw the function 'htmlOnPauseBlock' don't work anymore since version 3.28.0.

Here two examples.
**Version 3.27.0:**
https://jsfiddle.net/vk1hez8a/
![3 27 0](https://github.com/fluid-player/fluid-player/assets/100703779/8decb18b-c1e8-421a-9c74-5c8ef1a3ef5e)

**Version 3.30.0:**
https://jsfiddle.net/7hatv6yk/
![3 30 0](https://github.com/fluid-player/fluid-player/assets/100703779/5eeddea1-f071-41ae-a8f1-060ae0e80711)

So Version 3.28.0, 3.29.0 and 3.30.0 are affected by this.
I also checked syntax, but don't see any changes from 3.28 and above.

**Comment by sergiomcsousa** [comment]
An internal ticket was created to take care of this issue. Thank you!

**Comment by ZentoDH** [comment]
Hi there, sorry for the late reponse. This has been fixed in the latest FP version: https://github.com/fluid-player/fluid-player/pull/804
Thanks!
