### ISSUE TITLE
Mid Roll is not working with Live stream videos

### ISSUE THREAD

**Issue by virangaj** [fluid-player/fluid-player#796]
Hello Fluid Player Community,

I'm currently integrating Fluid Player into my project and have encountered an issue that I hope to get some guidance on. I've successfully implemented both pre-roll ads and ad banners across my content, and everything works perfectly with regular video playback. However, when it comes to live streaming content, I've noticed a discrepancy in how mid-roll VAST tags are handled.

**Issue Description:**
- **Pre-roll ads** work flawlessly across all content types, including live streams and regular videos.
- **Ad banners** are displaying as expected.
- However, **mid-roll VAST tags**, while functioning perfectly during the playback of regular videos, do not seem to trigger at all during live streams.

**Implementation Details:**
- I've followed the standard setup for implementing VAST tags as outlined in the Fluid Player documentation.
- The same VAST tags are being used for both live streams and regular video content to ensure consistency in testing.
- I've verified that the mid-roll cue points are correctly defined and that they work as expected in regular video playback.

**Questions:**
1. Are there any known limitations or additional configurations needed for mid-roll ads to work with live streaming content in Fluid Player?
2. Could this issue be related to how live stream cue points are handled versus those in regular video content?
3. Is there a recommended approach or workaround to get mid-roll VAST tags working for live streams?

Any insights, suggestions, or guidance on this matter would be greatly appreciated. I'm eager to ensure a seamless ad experience across all types of content and hope to resolve this discrepancy with mid-roll ads in live streams.

**Test environment**
 - fluid-player cdn
 - Windows 11
 - Chrome browser

Thank you in advance for your time and assistance.

**Comment by sergiomcsousa** [comment]
@ZentoDH can you please provide some feedback here? Do you think it's necessary to create an internal ticket? If so please let me know. Thank you!

**Comment by ZentoDH** [comment]
Hey @virangaj sorry for the delay. Looks like this is a bug. We'll make an internal ticket of this.

**Comment by sergiomcsousa** [comment]
@virangaj the fix for this was released 1 month ago. I will close this ticket but if the ticket still persist please re-open the ticket. Thank you!
