### ISSUE TITLE
Is it possible to add your own element to control's interface?

### ISSUE THREAD

**Issue by DunderAlexander** [fluid-player/fluid-player#799]
I'd like to add another element to default layout so it would only be visible when we pause or hover over the video. Is it possible to add to `fluid_video_wrapper_video-page-player`?

**Comment by sergiomcsousa** [comment]
@ZentoDH can you please provide feedback here? Is it necessary to create an internal ticket? Thank you!

**Comment by ZentoDH** [comment]
@DunderAlexander Sorry for the massive delay. 

We have an option called `htmlonpauseblock`. Does that do what you're looking for?
https://docs.fluidplayer.com/docs/configuration/layout/#htmlonpauseblock

If not, you can always use JS with queryselector and appendchild to add other HTML elements to FP. 

Let me know if you have more questions.

**Comment by sergiomcsousa** [comment]
@DunderAlexander since there's no feedback on this issue I will close this ticket. If the problem still persists please let us know and open it again. Thank you!
