### ISSUE TITLE
Several players on the page with VAST support

### ISSUE THREAD

**Issue by eagleowla** [fluid-player/fluid-player#8]
Hello!

How I can use more than one player on the page with VAST (and Exoclick InVideo Ad) support? As I understand, in the layout: 'browser' mode I can't use VAST, BTW Exoclick InVideo Ad isn't working too.
In any other layout mode I see [object HTMLDivElement] message before each player on the page.

Thank you!

**Comment by MarinYotovski** [comment]
Hello @eagleowla,

You can set multiple players on the same page and all of them can display VAST ads. Here is a simple example:
```
var testVideo = fluidPlayer(
    'my-video',
    'http://example.com/vast.xml'
);

var testVideo2 = fluidPlayer(
    'my-video-2',
    'http://example.com/vast2.xml'
);
```
The browser layout also supports VAST, as well as InVideo ads. Also, I don't see the message [object HTMLDivElement] in the current version of Fluid Player.

So, may I ask you to provide some more details - for example on which site is the player deployed, so that we can check?

Thank you in advance,
Marin

**Comment by namethatporn** [comment]
I very strongly disagree with the above solution. It is not dynamic and makes using this player in most situations IMPOSSIBLE.

Does the player support objects or not? For example, this neat code that should do the trick, but doesn't:
```
<video class="video" width="600" height="400">
    <source src="1.mp4" type="video/mp4"/>
</video>
<video class="video" width="600" height="400">
    <source src="2.mp4" type="video/mp4"/>
</video>
<script>
	var videos = document.getElementsByClassName("video");
	for (i = 0; i < videos.length; i++) {
		fluidPlayer(videos[i], {
			vastOptions: {
				adList: [
					{
	                    roll: 'preRoll',
	                    vastTag: 'vast.xml',
	                }
				]
			}
		});
	}
</script>
```
Having said all that, I think this issue should be opened up and figured out. Brutally doing copy paste on the initialisation code is very ExoClick, but not acceptable as a dynamic solution.

**Comment by namethatporn** [comment]
Working code for dynamically adding multiple videos:
<video id="1" width="600" height="400">
    <source src="1.mp4" type="video/mp4"/>
</video>
<video id="2" width="600" height="400">
    <source src="2.mp4" type="video/mp4"/>
</video>
<script>
	var videos = document.getElementsByTagName("video");
	for (i = 0; i < videos.length; i++) {
		fluidPlayer(videos[i].id, {
			vastOptions: {
				adList: [
					{
	                    roll: 'preRoll',
	                    vastTag: 'vast.xml',
	                }
				]
			}
		});
	}
</script>
