### ISSUE TITLE
Why Google Drive video is not playing?

### ISSUE THREAD

**Issue by ujjally** [fluid-player/fluid-player#800]
Why Google Drive video is not playing anymore?

Example URL:
https://drive.google.com/uc?export=download&id=1zez2XkoY_Fu5oRntktaVIPqkW96rk8ob
https://drive.google.com/u/0/uc?id=1zez2XkoY_Fu5oRntktaVIPqkW96rk8ob&export=download

console error log:
[FP_ERROR] Playback error DOMException: The element has no supported sources.
[Error] (202): Failed to play video.

**Comment by leroybm** [comment]
Google Drive simply doesn't allow a video to be embedded in a third party website via the `video` tag, it returns 403. You can check it here on the network requests: https://leroy-experiments.glitch.me/fluid-player/800.html

**Comment by ZentoDH** [comment]
@ujjally 
If you mean. if there is a way to play video that are hosted on google drive, yes. It's a bit weird but upload a video to google drive and play it in the browser. Right click on the video and inspect it. There in the `<video>` tag you can find the `src` of the video. Copy and paste that into the video source of FP and it should work.

Just tested it myself and it works.

**Comment by sergiomcsousa** [comment]
@ujjally since there's no feedback on this issue I will close this ticket. If the problem still persists please let us know and open it again. Thank you!
