### ISSUE TITLE
doubleclickFullscreen dont working

### ISSUE THREAD

**Issue by MSGCZ** [fluid-player/fluid-player#805]
`fluidPlayer(`
`    'my-video',`
`    {`
`        layoutControls: {`
`            doubleclickFullscreen: true, // Default true`
`        }`
`    }`
`);`

This function does not working. Don't you know why?

I used **Fluid Player** v**3.32.0**.

And I tested in browsers **Google Chrome**, **Opera**, **Edge**, **Firefox**, **Iron**, **Vivaldi**, **DuckDuckGo**.

**Comment by sergiomcsousa** [comment]
@ZentoDH can you please provide feedback here and if necessary create an internal ticket? Thanks!

**Comment by ZentoDH** [comment]
Weird, this is indeed a bug. I'll create an internal ticket.

**Comment by sergiomcsousa** [comment]
@MSGCZ A fix was released for this issue 2 weeks ago. Can you please confirm if everything is ok and close the ticket if so? Thank you!

**Comment by MSGCZ** [comment]
**Many thanks!** You are the best.

_Working since version 3.37.0_

**Comment by MSGCZ** [comment]
**Many thanks!** You are the best.

_Working since version 3.37.0_
