### ISSUE TITLE
Ads cannot be displayed when XML content has two Creative tags.

### ISSUE THREAD

**Issue by wangyegg1989** [fluid-player/fluid-player#809]
**Describe the bug**
If the child tag of the first Creative tag is not Linear, it will not load. Can you get the second tag if the first tag is not supported?

[this is not work]
![wrong](https://github.com/fluid-player/fluid-player/assets/30452999/6b9ef912-243c-4687-a700-3dabb654a34a)

**Affected version**
For example, v3

**Comment by sergiomcsousa** [comment]
@wangyegg1989 an internal ticket was created. Thank you!

**Comment by sergiomcsousa** [comment]
@wangyegg1989 The fix for this issue is now live. Could you please pull the latest changes, confirm and let me know if we can close the ticket? Thank you!

**Comment by sergiomcsousa** [comment]
Closing the ticket since the fix has been live for more than 14 days. Please feel free to re-open if there is any issue.
