### ISSUE TITLE
Support for VAST ViewableImpression

### ISSUE THREAD

**Issue by klaussilveira** [fluid-player/fluid-player#820]
Currently, the player is unable to follow IAB's Viewable Impression events, as defined:

> Watching at least 2 seconds of the video where at least 50% of the ad’s pixels are visible on the screen

Implemention should be similar as other events, but view intersection needs to be calculated and current time during intersection must be tracked.

**Comment by sergiomcsousa** [comment]
Hi @klaussilveira 
Thanks for both raising the issue and providing a solution! For new features, we need the product team to review the tickets, and then the code has to go through a code review by the FP lead. I'll open an internal ticket so we can move forward with this.

Could you please create issues for any other features you'd like to implement? This will help me create the internal tickets and expedite the process.

Thanks again for your contribution!

@ZentoDH fyi

**Comment by klaussilveira** [comment]
Thanks! Created a couple of those with some additional details. Let me know if you guys have a VAST-related roadmap, I would be happy to contribute in areas that you guys already planned to work on.

**Comment by ZentoDH** [comment]
Hi @klaussilveira  I'm so sorry this is taking a while. The combination of vacations, figuring out a flow/system here internally for community PR's and how PO would make inputs here, has slowed this down a bit. Just looked at your PR, it looks good. Just added one comment there: https://github.com/fluid-player/fluid-player/pull/821#pullrequestreview-2269206782

**Comment by ZentoDH** [comment]
@klaussilveira This is now live in our new update. Thank you so much for your contribution!
*Note*: If you use `https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js`, it takes 24h for the cache to update.
