### ISSUE TITLE
H265 support

### ISSUE THREAD

**Issue by tomasgrunt** [fluid-player/fluid-player#824]
Hi,

will be there H265 video support? Or is it even possible?

Thank you

**Comment by sergiomcsousa** [comment]
@ZentoDH Can you please provide feedback here? Thank you!

**Comment by klaussilveira** [comment]
I don't think this is something that Fluid Player can solve. Codecs have to be implemented by the browsers: https://caniuse.com/hevc

**Comment by ZentoDH** [comment]
Hi @tomasgrunt, thanks for the interest in Fluid Player. @klaussilveira is right about this one, thanks for the clarification. Is there a certain something you're trying to do with FP, maybe I can help out?

**Comment by ZentoDH** [comment]
It's been 3 weeks since a reply, hence closing it. @tomasgrunt If you have any other questions, feel free to open a new ticket. We're happy to help if you have any problems or general questions to implement Fluid Player into your project.
