### ISSUE TITLE
Sorry 

### ISSUE THREAD

**Issue by Kasamsun151a** [fluid-player/fluid-player#828]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Links**
If applicable, add screenshots or links to help explain your problem. **DO NOT** include links to NSFW webpages. Preferably create code to reproduce using https://jsfiddle.net

**Desktop (please complete the following information if relevant):**

**Smartphone (please complete the following information if relevant):**

**Affected version**
For example, v3.0.0

**Additional context**

**Comment by ZentoDH** [comment]
Hi there @Kasamsun151a 

Not sure if something went wrong? If you need any help you can always make a new issue. Going to close this one. Happy to help if you need it!
