### ISSUE TITLE
On Safari needs to click the play button two times to play a video.

### ISSUE THREAD

**Issue by ERI123** [fluid-player/fluid-player#83]
I have found two errors on Safari.
1. Needs to click the play button two times to play a video.
example: https://www.fluidplayer.com/ This happened also with VAST video.

2. when you change video quality( from SD to HD ). The video starts from the beginning, not from the point that you was watching.

**Comment by Danny15** [comment]
Hi @ERI123 , thank you for your comments. 

1. This is a issue we are aware of and are now reviewing this behavior and will hope to have improvements for this in one of our future releases.

2. Could you provide further information on how you are applying this as I cannot reproduce this issue.

**Comment by ERI123** [comment]
2.
When you watch a video that is 20 min. 
You are in min 10 and you change to HD quality. It goes to 0 min, not to min 10 that you were watching.

**Comment by golikov** [comment]
Both issues are not present in v2.2.0

**Comment by PostMalone** [comment]
This issue seems to still be present. V3

Vast is empty.
