### ISSUE TITLE
Got a error tip "Invalid initializer - player target already is initialized"

### ISSUE THREAD

**Issue by andyzhou** [fluid-player/fluid-player#834]
I use fluid 3.29 as video player in the html page,  init multi unique players on same page,  setup unique video id per video div.

some time i got the follow error tip in the browser console:

"Invalid initializer - player target already is initialized", this is happened on follow js code

`if (o.classList.contains("js-fluid-player"))
                    throw "Invalid initializer - player target already is initialized";`

Can u guys help me, thanks.

**Comment by ZentoDH** [comment]
Hi @andyzhou thanks for using Fluid Player! Normally this error happens if you have used an ID more than once. For every new instance you make, you need to give it a different ID.

**Comment by sergiomcsousa** [comment]
@andyzhou Did Zento's feedback help you? Does the problem persist or can we close this issue? Thank you!

**Comment by sergiomcsousa** [comment]
@andyzhou I will close the ticket due to lack of feedback. If there is still an issue please open a new ticket/re-open this one. Thank you!
