### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'Parser') when using subtitles

### ISSUE THREAD

**Issue by chris-verclytte** [fluid-player/fluid-player#839]
**Describe the bug**
When enabling subtitles in layoutControls and providing a VTT track files, Chrome logs an error "Uncaught TypeError: Cannot read properties of undefined (reading 'Parser')".
Acutally, this part of the script is calling WebVTT as a global variable which is not available in Google Chrome.
Hence, subtitles are not display because they can't be parsed. 

**To Reproduce**
Just enable the subtitles, provide a VTT track file (as on website examples) and open in Chrome.

**Expected behavior**
I see no requirement for adding a polyfill or whatever when enabling so I just expect the feature to work without any additional code.

**Screenshots or Links**
<img width="547" alt="Capture d’écran 2024-09-27 à 11 12 26" src="https://github.com/user-attachments/assets/de278c3f-6b01-4626-a8e0-64fe505e6dcc">

<img width="446" alt="Capture d’écran 2024-09-27 à 11 12 53" src="https://github.com/user-attachments/assets/d10a8d53-1007-406c-bdee-7892f0592ad8">

**Desktop**
 - OS: MacOS Sonoma
 - Browser: Chrome Version 128.0.6613.138 (Build officiel) (x86_64)
 - fluid-player@3.36.0
 - using inside of a Vue app (v3.4)
 - using npm version

**Comment by sergiomcsousa** [comment]
@chris-verclytte an internal ticket was created to deal with this issue. Thank you!

**Comment by chris-verclytte** [comment]
I just updated context to ease the reproduction, hope it will help. 
Don't hesitate to ask if you need more information.

**Comment by sergiomcsousa** [comment]
A fix is now live for this issue. The cache can take 1 day so you can actually see the change but can you confirm and close this if ok? Thank you!

**Comment by sergiomcsousa** [comment]
@chris-verclytte I am closing the ticket since it passed 1 week, if the problem persists please feel free to re-open with extra info so we can continue working on it if necessary. Thank you!
