### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null

### ISSUE THREAD

**Issue by Perdator** [fluid-player/fluid-player#84]
I trying to integrate FP into my site instead of standard HTML5 player. And I see error in console:
**Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at XMLHttpRequest.<anonymous> (fluidplayer.min.js:1)**

Part of code: **r=a.getElementsByTagName("Impression")**

Error happened when we want to use responsive player such as:

`
   <video id='my-video' controls style="width: 640px; height: 360px;">
   <source src='/pages/vid.mp4' type='video/mp4' />
  </video>
    
   <script type="text/javascript">
  var testVideo = fluidPlayer('my-video','',{responsive:true});
</script>
`

Empty VAST tag causes this issue. Check it first.

**P.S. Sorry, but I don't know why inserting code here doesn't working.**

**Comment by Danny15** [comment]
Hi @Perdator, Thank you for raising this with us. With our latest version you do not need to set the second parameter as a empty string. We have a new option for VAST support called adList (Setup one or multiple VastTag) which is now available as one of the various options for tweaking the appearance and behavior of the player . This second empty parameter string can be removed in latest version as follows:

`<script type="text/javascript">
    var testVideo = fluidPlayer('my-video',{responsive:true});
</script>`

If you require VAST support then see our new adList option from our README: https://github.com/fluid-player/fluid-player

**Comment by Perdator** [comment]
Hi @Danny15 , oops, looks like I readed the outdated documentation
