### ISSUE TITLE
Fluid player does not handle screen resizing

### ISSUE THREAD

**Issue by chris-verclytte** [fluid-player/fluid-player#840]
**Describe the bug**
The fluid player currently does not support resizing screen : if more or less space becomes available, the player will keep the same dimensions. 

**To Reproduce**
1. Load a page with fluid player on it 
2. Resize screen
3. See that space available is not used or that component overflow when less space becomes available

**Expected behavior**
The player should use all space available.
Currently a static height and width is set on the video parent div (.fluid-component parent in Vue.js example). 
I am pretty sure a resize event listener is missing to get the player adapting to its parent height and width.

**Desktop (please complete the following information if relevant):**
 - OS: MacOS Sonoma
 - Browser: Chrome v128.0.6613.138 (Build officiel) (x86_64)

**Affected version**
v3.36.0

**Comment by sergiomcsousa** [comment]
@chris-verclytte closing the ticket due to Zento comment. If you still have issues, please feel free to open/re-open the issue.
