### ISSUE TITLE
Download button not showing please fix it immediately

### ISSUE THREAD

**Issue by Malati1432** [fluid-player/fluid-player#847]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZentoDH** [comment]
Hi there,

I've just tested the download button and it behaved as expected. Here's a codepen where I tested it: https://codepen.io/Zento-De-Houwer/pen/BaXmJOM

Could you give a bit more information about how you implemented it? Did you use the cdn or npm package. Stuff like that.

Thanks!

**Comment by sergiomcsousa** [comment]
@Malati1432 Can you please take a look into @ZentoDH comment above? thanks!
