### ISSUE TITLE
DOMException: Failed to load because no supported source was found

### ISSUE THREAD

**Issue by Perdator** [fluid-player/fluid-player#85]
**I found that FluidPlayer doesn't working in Chromium browser (but it's working in Chrome). It's make an exception:**

test_player.html:85 vast loaded
test_player.html:86 no vast
test_player.html:88 vast ended
test_player.html:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.
Promise (async)
switchToMainVideo @ fluidplayer.min.js:1
playMainVideoWhenVastFails @ fluidplayer.min.js:1
onErrorDetection @ fluidplayer.min.js:1

**Comment by Danny15** [comment]
@Perdator, thank you for raising this issue with us. I will pass this to our development team and we will review the behavior on Chromium.

**Comment by b202020** [comment]
Hi @Perdator ,

May I ask you to provide some more details about the video you are trying to play?

The Chromium browser doesn't supports all the video codec as Chrome. 
The supported https://www.chromium.org/audio-video codecs :
`
VP8
VP9
Theora [Except on Android variants]
H.264 [Google Chrome only]
MPEG-4 [Google Chrome OS only]`

**Comment by kristijanexads** [comment]
@Perdator this error is now handled, the error will be shown in the console if no codes are available and video can't be played.
