### ISSUE TITLE
Install fluid player on clipbucket ?

### ISSUE THREAD

**Issue by simplesampledot** [fluid-player/fluid-player#9]
Hello 

Someone know how to integrate fluid player on clipbucket ?

Thx

**Comment by cradonn** [comment]
Hi @simplesampledot,

Our integration documentation will be getting an overhaul in the coming weeks and this should help you somewhat. ClipBucket is not that familiar to us but we will flag it for review.

**Comment by LeoLuanElezi** [comment]
1 - Download fluid player
2 - copy and paste the fluid player in your file manager
3 -  embed video like this...

<link rel="stylesheet" href="//yourwebsite.com/fluid-player/fluidplayer.css" type="text/css"/>
<script src="//yourwebsite.com/fluid-player/fluidplayer.js"></script>

<video id="my-video" controls style="width: 640px; height: 360px;">
    <source src="The Video Link here" type="video/mp4" />
</video>

<script type="text/javascript">
	var testVideo = fluidPlayer('my-video');
</script>
