### ISSUE TITLE
Full Screen On Doubleclick

### ISSUE THREAD

**Issue by leventmuslim** [fluid-player/fluid-player#90]
How can I get player to go fullscreen when doubleclicked on the video? And when in full screen same double click should return player back to normal play size.

**Comment by Danny15** [comment]
Hi @leventmuslim, we don't have this functionality to go full screen with double click on video. We do provide keyboard shortcuts by key if this helps which requires the keyboardControl parameter to be set to true. When enabled you can use the f key to go to full screen mode.

 See our integration guide for further details: https://github.com/fluid-player/fluid-player#keyboard-shortcuts

**Comment by leventmuslim** [comment]
Then should this topic be considered as a feature request? I’m sure other Fluid Player users would agree if you take some kind of poll to this.
I’m aware of the ‘F’ key shortcut, I’ve read the code samples pdf file, and the right click on the video also allows me to go fullscreen.
But, you know I‘m not asking this feature for myself but for my visitors. And users are used to take benefit from some common features of players, which I personally believe that this function alone would help Fluid to widen its usage among websites.
Could you kindly consider this seriously for the coming upgrade(s) as a build-in feature or as a plugin?

**Comment by Danny15** [comment]
Hi @leventmuslim, thank you for your comments. I have passed your request onto our development team and this will be taken into consideration for future releases.

**Comment by bharath-exads** [comment]
Hi,

Please try our latest release
https://docs.fluidplayer.com/layout_configuration/#doubleclickfullscreen
