### ISSUE TITLE
iOS iFrame = no fullscreen option in v2

### ISSUE THREAD

**Issue by majamee** [fluid-player/fluid-player#95]
### Expected behaviour
The player should offer the same functionalities like fullscreen option also when embedded via iFrame.
Plus the fullscreen option is working not in fullscreen, but inline anyways.

### Actual behaviour
On iOS 11/ Safari the fullscreen option is automatically cut-back to the dimension of the inline iFrame once Fluid Player gets loaded inside an iFrame. It is looking very odd as well, when switching into this pseudo "fullscreen" mode. (no offense, your player is working flawlessly about anywhere else)

### Environment

- Browser: Safari
- Version: latest
- Operating System: iOS
- Version: 11.2.6

### Steps to reproduce
- Fluid Player without iFrame: http://alpine-dash-hls.gq/player/fluid-player.html
- Same Fluid Player loaded via iFrame: http://alpine-dash-hls.gq/demos/fluid-player with `allowfullscreen` parameter

```
<iframe src="../../player/fluid-player.html" type="text/html" frameborder="0" allowfullscreen width="100%" height="1080"><p>Failed to load Fluid Player! I'm sorry :(</p></iframe>

```

**Comment by Danny15** [comment]
Hi @majamee, thank you very much for your comments. We have known issues with Fluid Player and iOS. Currently we are reviewing iOS behavior and we have started to look into its issues. We will consider your issue when we do.

**Comment by majamee** [comment]
Thank you, looking forward to it :)

**Comment by majamee** [comment]
Just one thing I noticed, most other JS based players switch on iOS to the system native player for true full screen playback and switching back once fullscreen mode is left. Maybe this could be a route worth considering? (FYI)

**Comment by leather-s** [comment]
Has fluid player ever offered true native iOS full screen in the past? I could have swore when I demoed fluid player i saw the native full screen featrue.

**Comment by majamee** [comment]
The native fullscreen option in the latest version for iOS is really great as well as the included dash support, I fear the issue when the player is inside an iframe still prevails though.
It can be tested here: http://alpine-dash-hls.gq/demos/fluid-player

**Comment by cian-exads** [comment]
Hi @majamee, in the latest version 2.2.1 of Fluid Player we have a fix to use native fullscreen for iOS devices. This fix is for iOS devices in general, and also fixes fullscreen from within an iframe.
