### ISSUE TITLE
VAST XML without <mediafiles> Tag and Version

### ISSUE THREAD

**Issue by random-git-username** [fluid-player/fluid-player#96]
I have a VAST XML which works in Googles Video Suite Inspector, but not when I give the same URL to the fluidPlayer Javascript Function.
If a &lt;mediafiles&gt; Tag is present, Fluidplayer works as expected. But without it, it does not and says in the console "[Error] (101): Failed to load Vast" and executes the "noVastVideoCallback" function.
Even though if I add the same XML to https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector it works fine and plays the video.
Any Idea why this is the case?
Also, does fluidplayer support VAST Version 2.0 and 3.0?

**Comment by Danny15** [comment]
Hi @random-git-username, Fluid Player supports VAST 3.0 / 4.0. Some features may not be implemented yet. We do support <MediaFiles> tag but currently only support the attribute delivery="progressive"

```
<MediaFiles>
              <MediaFile delivery="progressive" type="video/mp4"><![CDATA[pre-ad.mp4]]></MediaFile>
</MediaFiles>
```

Can you provide us with further information for your <mediafiles> Tag and/or snippet of XML code for this so we can review?. Thank you

**Comment by random-git-username** [comment]
Thanks for the reply! :)
The following VAST 3.0 XML works in Googles Video Inspector but NOT with fluidplayer:
<pre><code>
<VAST version="3.0">
<Ad>
<Wrapper>
<AdSystem>Improve Digital</AdSystem>
<VASTAdTagURI>
<![CDATA[ https://ad.360yield.com/advast?p=869114&w=4&h=3 ]]>
</VASTAdTagURI>
<Error>
<![CDATA[
https://ad.360yield.com/vastevent?e=error&error_code=[ERRORCODE]&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Error>
<Impression>
<![CDATA[
https://dsp.adfarm1.adition.com/cookie/?ssp=4&publisher_user_id=8a0f44d7-8cf7-45f5-a23a-c9ffad98ad83&publisher_dsp_id=105&publisher_call_type=redirect&publisher_redirecturl=https://ad.360yield.com/match
]]>
</Impression>
<Impression>
<![CDATA[
https://match.adsby.bidtheatre.com/idmatch?publisher_user_id=8a0f44d7-8cf7-45f5-a23a-c9ffad98ad83&publisher_dsp_id=69&publisher_call_type=redirect&publisher_redirecturl=https://ad.360yield.com/match
]]>
</Impression>
<Impression>
<![CDATA[
https://rs.gwallet.com/r1/cm/p59?push&amp;amp;&publisher_user_id=8a0f44d7-8cf7-45f5-a23a-c9ffad98ad83&publisher_dsp_id=125&publisher_call_type=redirect&publisher_redirecturl=https://ad.360yield.com/match
]]>
</Impression>
<Impression>
<![CDATA[
https://ad.360yield.com/vastevent?e=impression&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Impression>
<Creatives>
<Creative>
<Linear>
<TrackingEvents>
<Tracking event="creativeView">
<![CDATA[
https://ad.360yield.com/vastevent?e=creativeView&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="start">
<![CDATA[
https://ad.360yield.com/vastevent?e=start&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="firstQuartile">
<![CDATA[
https://ad.360yield.com/vastevent?e=firstQuartile&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="midpoint">
<![CDATA[
https://ad.360yield.com/vastevent?e=midpoint&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="thirdQuartile">
<![CDATA[
https://ad.360yield.com/vastevent?e=thirdQuartile&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="complete">
<![CDATA[
https://ad.360yield.com/vastevent?e=complete&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="mute">
<![CDATA[
https://ad.360yield.com/vastevent?e=mute&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="unmute">
<![CDATA[
https://ad.360yield.com/vastevent?e=unmute&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="pause">
<![CDATA[
https://ad.360yield.com/vastevent?e=pause&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="resume">
<![CDATA[
https://ad.360yield.com/vastevent?e=resume&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="rewind">
<![CDATA[
https://ad.360yield.com/vastevent?e=rewind&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="fullscreen">
<![CDATA[
https://ad.360yield.com/vastevent?e=fullscreen&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="close">
<![CDATA[
https://ad.360yield.com/vastevent?e=close&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="skip">
<![CDATA[
https://ad.360yield.com/vastevent?e=skip&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="collapse">
<![CDATA[
https://ad.360yield.com/vastevent?e=collapse&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
<Tracking event="expand">
<![CDATA[
https://ad.360yield.com/vastevent?e=expand&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</Tracking>
</TrackingEvents>
<VideoClicks>
<ClickTracking>
<![CDATA[
https://ad.360yield.com/click/YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==//
]]>
</ClickTracking>
<ClickTracking>
<![CDATA[
https://ad.360yield.com/vastevent?e=click&ic=YqaIvK4YtpCYxaucSVgzhLRaQBqXkJcT4vyykL5U4rbggaJteXuStagI83wGt8OrvM553HaK4Txo6UGK1cRgH4bXqSr2i5kr1dBD-zIhhIqdJqSu9JZRSJR9K8rejME31p8hEfzCiQryZn-cBDnBHJR0I6Zf7HIFgY8Ch26JXpqey2bNG.sOWcqRWYw11aU.0CTj5oDFdCIueTjzE6uyQXnz64N0ADtwPZ6gwwFZ7nYCgGGYK3.zlR-3T2Qe-djDPGn3oxYbygHoTZVlGCCmGkVNdEU7speFEIVfNG43n2vXFn5N19eexkZdbbijTXWhWYWV.4t53UikV9aMxCUbXVwAMJGi7AyIezn0G-uuA5tKpGmmAoIE9U.eTURi3jCjCPC8yOhJkTGnsArGTK8sa2p.O4UnLvzGAy6QuBLSHyIZtO5IJvIvA3JkTDdvUejxpsOKsXBNZ59mGo6XVUz-BJam6BOdg0fIN3zV8ceajL8xaJ5aG3JSZ.y0Ij6Ccfy9H6NwfzOnd62TaA==
]]>
</ClickTracking>
</VideoClicks>
</Linear>
</Creative>
</Creatives>
</Wrapper>
</Ad>
</VAST>
</code></pre>

**Comment by Danny15** [comment]
@random-git-username, thank you for attachment. Fluid Player currently does not support The <Wrapper> element. We support the The <InLine> element and the &lt;MediaFiles&gt; should be added to avoid "[Error] (101): Failed to load Vast" error and display ad.

i will pass your issues onto our development team so they can consider these in future releases.

**Comment by random-git-username** [comment]
Thanks for clarifying this.
Would you write again which elements it does and doesnt support? I those were interpretet as html tags.

**Comment by Danny15** [comment]
This example describes what we support: https://github.com/fluid-player/fluid-player/blob/v1.2.2/docs/demo/vastLinear.xml

And this is for nonLinear ads (Banners) : https://github.com/fluid-player/fluid-player/blob/v1.2.2/docs/demo/vastNonLinear.xml

Note: These apply to Version 2 aswell

Let us know if you need any further information and thank you for your comments

**Comment by random-git-username** [comment]
Thank you very much
