### ISSUE TITLE
Fluidplayer Version 2: player is not defined

### ISSUE THREAD

**Issue by random-git-username** [fluid-player/fluid-player#97]
It says "player is not defined" in the console when using the Fluidplayer Version 2 and calling the fluidPlayer() Function.
How do you fix this?
Thank you.

**Comment by majamee** [comment]
It sounds a little bit, like Fluid Player is not yet initialized when trying to call it. Please have a look here (scroll down) for working code (v2):
http://alpine-dash-hls.gq/demos/fluid-player

Please ensure to include the player ".js" and ".css" as well as initializing the player by the command
```
<body>
  <main role="main" id="main">
    <video id="player" controls>
      <source src="playlist.m3u8" type="application/x-mpegURL">
    </video>
  </main>

  <!-- Include fluidplayer.js and dash.js in your page -->
  <script src="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js"></script>
  <script src="https://cdn.dashjs.org/latest/dash.all.min.js"></script>

  <script>
    fluidPlayer('player');
  </script>
</body>
```

**Comment by Danny15** [comment]
Hi @random-git-username, could you provide an example of your integration code to help us debug your issue?. As @majamee suggested, please ensure that you have included the Fluid Player Javascript and CSS files. As per our documentation the following are required:


- The Javascript and CSS files of the player;

- An HTML5 <video> tag;

- A single Javascript line of code that attaches the player to the video tag.

Example Integration Using Optional Parameters:
```<link rel="stylesheet" href="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.css" type="text/css"/>
<script src="https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js"></script>

<video id='my-video' controls style="width: 640px; height: 360px;">
    <source src='vid.mp4' type='video/mp4' />
</video>

<script type="text/javascript">
fluidPlayer(
   'my-video',
    {
        layoutControls: {
            // Parameters to customise the look and feel of the player
        },
        vastOption: {
            // Parameters to customise how the ads are displayed & behave
        }
    }
);
</script>```

@majamee, Thank you for your suggestion here

**Comment by Danny15** [comment]
@majamee, Thank you for your suggestion here
