### ISSUE TITLE
[Error] (101): Failed to load Vast

### ISSUE THREAD

**Issue by dominicpranz** [fluid-player/fluid-player#98]
What does the error code
[Error] (101): Failed to load Vast
mean and where can I look up all the error codes?

Thanks!

**Comment by Danny15** [comment]
Hi @random-git-username, could you provide us with your Fluid Player integration code to help us resolve your issue? Thank you

**Comment by cian-exads** [comment]
@random-git-username have you additional information which can help us identify your issue?

**Comment by Addvilz** [comment]
Not enough information to reproduce the issue. Add more details and reopen the issue if the issue remains.
